### ISSUE TITLE
PricingDataNotLoadedError for a time range outside of simulation's timeframe

### ISSUE THREAD

**Issue by redboyhun** [enigmampc/catalyst#105]
Dear Catalyst Maintainers,

I tried to use the portfolio optimization script between 2017 AUG 1st and 2017 DEC 17th, but got a data error for a timeframe outside the simulation.

Error:
_[2017-12-18 11:47:10.832338] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Error traceback: /opt/miniconda2/envs/catalyst/lib/python2.7/site-packages/catalyst/exchange/exchange_bundle.py (line 1013)
**PricingDataNotLoadedError**:  Missing data for bitfinex dsh_usd in date range [**2017-02-02** 00:00:00+00:00 - **2017-08-01** 00:00:00+00:00]
Please run: `catalyst ingest-exchange -x bitfinex -f daily -i dsh_usd`. See catalyst documentation for details._

The error is confusing since I wanted to simulate between 2017 AUG 1st and 2017 DEC 17th

I tried a modified protfolio optimization with version 0.4.0:
Changes in script:
context.assets = symbols('btc_usd', 'eth_usd', 'ltc_usd', 'dsh_usd', 'xrp_usd')
start = datetime(2017, 8, 1, 0, 0, 0, 0, pytz.utc)
end = datetime(2017, 12, 17, 0, 0, 0, 0, pytz.utc)

Ingest command issued:
(catalyst) [root@catalyst catalyst_samples]# `catalyst ingest-exchange -x bitfinex -f daily -i btc_usd,eth_usd,ltc_usd,dsh_usd,neo_usd,xrp_usd --verbose --validate`
Ingesting exchange bundle bitfinex...
    [====================================]  Ingesting daily price data for xrp_usd on bitfinex:  100%
    [====================================]  Ingesting daily price data for neo_usd on bitfinex:  100%
    [====================================]  Ingesting daily price data for ltc_usd on bitfinex:  100%
    [====================================]  Ingesting daily price data for eth_usd on bitfinex:  100%
    [====================================]  Ingesting daily price data for btc_usd on bitfinex:  100%
    [====================================]  Ingesting daily price data for dsh_usd on bitfinex:  100%

Best regards,
redboyhun

# Environment

* Operating System: CentOS Linux  3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.13 :: Continuum Analytics, Inc.
* Python Bitness: 64
* How did you install Catalyst: `conda`
* Python packages: 
packages in environment at /opt/miniconda2/envs/catalyst:
alembic                   0.9.6                     <pip>
backports-abc             0.5                       <pip>
backports.functools-lru-cache 1.4                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
bcolz                     0.12.1                    <pip>
bleach                    2.1.2                     <pip>
boto3                     1.4.8                     <pip>
botocore                  1.8.13                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h1d4fec5_0
ccxt                      1.10.319                  <pip>
certifi                   2017.11.5                 <pip>
certifi                   2016.2.28                py27_0
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
configparser              3.5.0                     <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.1                    <pip>
decorator                 4.1.2                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.4.0                     <pip>
entrypoints               0.2.3                     <pip>
enum34                    1.1.6                     <pip>
functools32               3.2.3.post2               <pip>
futures                   3.2.0                     <pip>
html5lib                  1.0.1                     <pip>
idna                      2.6                       <pip>
intervaltree              2.1.0                     <pip>
ipykernel                 4.7.0                     <pip>
ipython                   5.5.0                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.0.5                     <pip>
Jinja2                    2.10                      <pip>
jmespath                  0.9.3                     <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.1.0                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
libgcc-ng                 7.2.0                h7cc24e2_2
libgfortran               3.0.0                         1
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mistune                   0.8.3                     <pip>
mkl                       2017.0.3                      0
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
networkx                  2.0                       <pip>
notebook                  5.2.2                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0
openssl                   1.0.2l               h077ae2c_5
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
pandocfilters             1.4.2                     <pip>
pathlib2                  2.3.0                     <pip>
patsy                     0.4.1                     <pip>
pexpect                   4.3.1                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py27_1
prompt-toolkit            1.0.15                    <pip>
ptyprocess                0.5.2                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2017.2                    <pip>
pyzmq                     16.0.3                    <pip>
qtconsole                 4.3.1                     <pip>
readline                  6.2                           2
requests                  2.18.4                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
s3transfer                0.1.12                    <pip>
scandir                   1.6                       <pip>
scipy                     0.19.1              np113py27_0
setuptools                36.4.0                   py27_1
simplegeneric             0.8.1                     <pip>
singledispatch            3.4.0.3                   <pip>
six                       1.11.0                    <pip>
sortedcontainers          1.5.7                     <pip>
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                        0
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1                     <pip>
tk                        8.5.18                        0
toolz                     0.8.2                     <pip>
tornado                   4.5.2                     <pip>
traitlets                 4.3.2                     <pip>
urllib3                   1.22                      <pip>
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                     <pip>
wheel                     0.29.0                   py27_0
widgetsnbextension        3.0.8                     <pip>
zlib                      1.2.11               ha838bed_2

**Comment by Knifespirit** [comment]
I had the same error with the currency eth_btc with poloniex

**Comment by fredfortier** [comment]
We'll try to replicate this issue with the same parameters.

**Comment by inevity** [comment]
Seems  like the ingest problem. I reingest, it pass ,but met another problem.
