### ISSUE TITLE
Incorrect order sale price in backtesting?

### ISSUE THREAD

**Issue by ielashi** [enigmampc/catalyst#118]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: macOS 10.13.1
* Python Version: Python 3.6.3
* Python Bitness: 64
* How did you install Catalyst: pip
* Python packages:

aiodns==1.1.1
aiohttp==2.3.6
alembic==0.9.6
apipkg==1.4
appnope==0.1.0
asn1crypto==0.24.0
async-timeout==2.0.0
atari-py==0.1.1
bcolz==0.12.1
bitfinex==0.2.6
bittrex==0.1.4
bleach==1.5.0
boto3==1.5.1
botocore==1.8.15
Bottleneck==1.2.1
btfxwss==1.1.14
cchardet==2.1.1
ccxt==1.10.393
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
click==6.7
codacy-coverage==1.3.9
contextlib2==0.5.5
coverage==4.4.2
cryptocompare==0.3
cryptography==2.1.4
cvxopt==1.1.9
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
decorator==4.1.2
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.4.0
entrypoints==0.2.3
enum34==1.1.6
execnet==1.5.0
future==0.16.0
Glances==2.11.1
gym==0.9.4
h5py==2.7.1
html5lib==0.9999999
httpretty==0.8.14
idna==2.6
intervaltree==2.1.0
ipdb==0.10.3
ipykernel==4.6.1
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.0.4
jedi==0.11.0
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.4.0
Keras==1.2.2
keras-rl==0.3.1
knapsack==0.0.3
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
Markdown==2.6.9
MarkupSafe==1.0
matplotlib==1.4.3
mem-top==0.1.5
mistune==0.8.1
multidict==3.3.2
multipledispatch==0.4.9
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.0
nose==1.3.7
notebook==5.2.1
numexpr==2.6.4
numpy==1.13.3
olefile==0.44
pachi-py==0.0.21
pandas==0.19.2
pandas-datareader==0.5.0
pandocfilters==1.4.2
parso==0.1.0
patsy==0.4.1
pexpect==4.3.0
pickleshare==0.7.4
Pillow==4.3.0
prompt-toolkit==1.0.15
protobuf==3.5.0
psutil==5.4.1
ptyprocess==0.5.2
py==1.5.2
PyAlgoTrade==0.18
pycares==2.3.0
pycparser==2.18
pyglet==1.3.0
Pygments==2.2.0
Pympler==0.5
PyOpenGL==3.1.0
pyparsing==2.2.0
PyScaffold==2.5.8
pytest==3.2.5
pytest-cov==2.5.1
pytest-forked==0.2
pytest-xdist==1.20.1
python-bittrex==0.2.1
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
PyYAML==3.12
pyzmq==16.0.3
qtconsole==4.3.1
raven==6.3.0
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
s3transfer==0.1.12
schedule==0.5.0
scipy==1.0.0
seaborn==0.8.1
simplegeneric==0.8.1
six==1.11.0
slackclient==1.1.0
sortedcontainers==1.5.9
SQLAlchemy==1.1.15
statsmodels==0.8.0
TA-Lib==0.4.10
tables==3.4.2
tensorflow==1.4.0
tensorflow-tensorboard==0.4.0rc3
terminado==0.6
testpath==0.3.1
tflearn==0.3.2
Theano==0.9.0
toolz==0.8.2
tornado==4.5.2
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.44.0
websockets==4.0.1
Werkzeug==0.12.2
widgetsnbextension==3.0.7
yarl==0.16.0
zipline-poloniex==0.1.2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

When I was playing around with backtesting, I noticed that the price at which an order is executed is equal to the price of the asset in the *next* trading period, not the current one.

Here's an example to explain what I mean. Consider this simple backtest run:

```
from catalyst import run_algorithm
from catalyst.api import order, record, symbol
import pandas as pd


def initialize(context):
  context.asset = symbol('btc_usd')
  context.first = True


def handle_data(context, data):
  print("=== New Trading Period ===")
  price = data.current(context.asset, 'price')

  print("Current price: %s" % price)
  print("Current positions: %s" % context.portfolio.positions)


  if context.first:
    context.first = False

    print("Placing order at price: %s" % price)
    order(context.asset, 1)


if __name__ == '__main__':
  run_algorithm(
      capital_base=10000,
      data_frequency='daily',
      initialize=initialize,
      handle_data=handle_data,
      exchange_name='bitfinex',
      algo_namespace='buy_and_hodl',
      base_currency='usd',
      start=pd.to_datetime('2015-03-01', utc=True),
      end=pd.to_datetime('2015-03-02', utc=True),
  )
```

The output for the code above is:

```
=== New Trading Period ===
Current price: 262.39999999
Current positions: {}
Placing order at price: 262.39999999
=== New Trading Period ===
Current price: 277.41
Current positions: {Trading Pair btc_usd(98871) Exchange: bitfinex, Introduced On: 2013-03-31 00:00:00+00:00, Base Currency: btc, Quote Currency: usd, Exchange Leverage: 1.0, Minimum Trade Size: 0.0020000000949949026 Last daily ingestion: 2017-12-22 00:00:00+00:00 Last minutely ingestion: 2017-12-22 00:00:00+00:00: Position({'asset': Trading Pair btc_usd(98871) Exchange: bitfinex, Introduced On: 2013-03-31 00:00:00+00:00, Base Currency: btc, Quote Currency: usd, Exchange Leverage: 1.0, Minimum Trade Size: 0.0020000000949949026 Last daily ingestion: 2017-12-22 00:00:00+00:00 Last minutely ingestion: 2017-12-22 00:00:00+00:00, 'amount': 1, 'cost_basis': 277.9926165083552, 'last_sale_price': 277.41, 'last_sale_date': Timestamp('2015-03-02 23:59:00+0000', tz='UTC')})}
```

Notice that, from the output above, the order, which was placed when the price of BTC was $262.39, has been executed at the price of $277.41, the price of BTC in the next trading period ('last_sale_price': 277.41). Is this intentional? The behavior I expected was that _'last_sale_price'_ would be equal to the price of BTC at the time I placed the order, which was 262.39.

**Comment by fredfortier** [comment]
This looks accurate to me. The ‘last_sale_price’ goes with
‘last_sale_date’, it tracks the current value of the market which useful to
calculate things like pnl. cost_basis is what you paid on average for each
unit of your position. For the original price of your order, look for the
orders list.

**Comment by ielashi** [comment]
The part that I don't understand is, in the example above the order was placed at "2015-03-01 23:59:00+0000", but the last sales date (and price) is that of the _next_ day "2015-03-02 23:59:00+0000". My expectation was that the _last_sale_price_ and _last_sale_date_ would be the date and price the order was placed. Am I missing something?

**Comment by fredfortier** [comment]
Yes, `last_sale_date` gets updated in every frame. It represents the last transaction in that frame. It's unrelated to your particular orders. This is simply a reference price to calculate the pnl.

**Comment by ielashi** [comment]
Sorry I don't think I have been clear with what I was intending to say. What I expect in a backtest is that, when I place an order at time X, the order is executed at the price in time X. What I see though, is that the order gets executed with the price at time X + 1. Is that intentional? Is my expectation incorrect?

**Comment by fredfortier** [comment]
Yes, I believe that the behavior is correct. The way that the backtesting simulation works is that it looks for open orders at the *before* each frame. If the price is within the limits of your order, it executes it. If you limit is removed from the current price, it might take several bars to execute it. 

Please reopen if you still believe that something is off.
