### ISSUE TITLE
set_max_leverage(1.0) does not allow order_target_percent(context.asset, 1.0)

### ISSUE THREAD

**Issue by damo1884** [enigmampc/catalyst#12]
set_max_leverage(1.0) does not allow order_target_percent(context.asset, 1.0)

Should be <= not <

**Comment by lacabra** [comment]
@damo1884 thanks for submitting this issue, can you please provide additional context, and/or give an example of what you are trying to do, and what is the problem you are encountering? The more information you provide, the easier it is to resolve it. Thank you.

**Comment by fredfortier** [comment]
I'm not sure if this is still applicable but I will unit test.

**Comment by lenak25** [comment]
@damo1884 , I am closing this due to low activity. Feel free to reopen if there is still an issue.
Thanks.
