### ISSUE TITLE
Suggestion: abstract retriable actions

### ISSUE THREAD

**Issue by caioaao** [enigmampc/catalyst#121]
All functions that have retriable actions are doing it with a copy-pasted recursion scheme. This is quite bad. First of all, recursion in python sucks. Run this snippet for a taste of it:

```python
def recur_sucks(idx):
    try:
        recur_sucks(idx+1)
    except:
        print("recur failed at %d" % idx)

recur_sucks(0)
```
Yeah, it prints `recur failed at 998` in my machine. It's not a problem for single functions, but it's possible to have retriable functions calling other retriable functions, potentially making several recursions.

More important: it makes the stack trace bigger, making it a pain to debug...

And the most important: this is a solved problem that could be abstracted with a simple function... Or even better, with battle-tested methods, like [mozilla-redo](https://github.com/mozilla-releng/redo): it's a ~250 LOC dependency...

Fault tolerance on a live-trading platform should be really important, and I feel it's lacking in catalyst.

**Comment by fredfortier** [comment]
Thanks for the suggestion. I see you point and agree that it can be
improved. We will look specifically into mozilla-redo.

**Comment by fredfortier** [comment]
I've tried it in one place for now (see commit). It seems to offer a bit less granularity (for example the ability to wrap the original exception when exceeding retry attempts) but it's an acceptable tradeoff.  We do want to make our error handling as strong as possible as we know that exchange APIs are unstable. Unless we find issues after further testing, we'll use this library where applicable since it does help code readability and potentially prevents issues with nested recursion.

**Comment by fredfortier** [comment]
Refactored all retries, it looks good on the surface but more testing required. It gave me a chance to review and consolidate the configuration. Here are the currently supported operations with retry:
```
        self.attempts = dict(
            get_transactions_attempts=5,
            order_attempts=5,
            synchronize_portfolio_attempts=5,
            get_order_attempts=5,
            get_open_orders_attempts=5,
            cancel_order_attempts=5,
            get_spot_value_attempts=5,
            get_history_window_attempts=5,
            retry_sleeptime=5,
        )
```
This can be configured in an algo like this:
```
context.attempts['order_attempts'] = 10
```
I believe that it covers them all but let me know if you see something missing.

**Comment by caioaao** [comment]
LGTM, good job :clap:
