### ISSUE TITLE
Algorithm unexpectedly shorting during paper trading

### ISSUE THREAD

**Issue by caioaao** [enigmampc/catalyst#122]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

Here's the docker image:
https://gist.github.com/caioaao/8f091b5a9050216577e80900916bdefe

# Description of Issue

I left an algorithm running for a while and, all of the sudden, it had an open short position. The basic outline of the algorithm is here:

```python
def initialize(context):
    context.set_long_only()
    context.assets = ... # list of traded assets



def close_open_orders(context, asset):
    orders = get_open_orders(asset)
    if orders:
        for order in orders:
            cancel_order(order)


def handle_data(context, data):
    for asset in context.assets:
        close_open_orders(context, asset)
        position = context.portfolio.positions[asset]

        if position.amount > 0:
            if signal_to_exit(...):
                order_target_percent(asset, 0)
        elif position.amount == 0:
            if signal_to_long(...):
                order_percent(asset, position_size)
```

I know that `set_long_only` doesn't check for outstanding orders by design, but I'm closing open orders, so there shouldn't be any concurrency issues making duplicate shorts. I had this same problem on backtesting before, but `close_open_orders` solved the issue.

**Comment by fredfortier** [comment]
By short position, I assume that you mean a negative cash value in your algo? Which exchange are you paper trading against? I can see how this could happen with open sell orders but I see that you are cancelling them. I'll try to replicate the same condition on my side.

**Comment by caioaao** [comment]
@fredfortier against poloniex. It looks like a "rare" concurrency issue, as it took nearly 24h to happen.

**Comment by fredfortier** [comment]
I suppose that it better than the alternative but it makes it harder to troubleshoot. 😄  Do you know which currency it is? I want to be as close as possible to maximize my chances of reproducing it. I have some long running algos with paper trading in live. I have not encountered such issue but I'm using Binance and skip frames on open orders.

**Comment by caioaao** [comment]
`xrp_usdt`. oh, and I have the `can_trade(asset)` check before everything that I forgot to put on the issue description. the algorithm is like this with `can_trade`:
```python
def initialize(context):
    context.set_long_only()
    context.assets = ... # list of traded assets



def close_open_orders(context, asset):
    orders = get_open_orders(asset)
    if orders:
        for order in orders:
            cancel_order(order)


def handle_data(context, data):
    for asset in context.assets:
        if not data.can_trade(asset):
            continue
        close_open_orders(context, asset)
        position = context.portfolio.positions[asset]

        if position.amount > 0:
            if signal_to_exit(...):
                order_target_percent(asset, 0)
        elif position.amount == 0:
            if signal_to_long(...):
                order_percent(asset, position_size)
```

**Comment by fredfortier** [comment]
Ok thanks for the details. I will investigate.

**Comment by fredfortier** [comment]
We fixed an issue with Poloniex. I ran live algos executing lots of trades for an extended period and was unable to reproduce this issue. I'll issue that it was a side-effect of other issues and marked fixed. Please let us know if you come across the same behavior again.

**Comment by fredfortier** [comment]
Please reopen if it's still happening in version 0.4.2.
