### ISSUE TITLE
Outdated examples after adding ccxt integration.

### ISSUE THREAD

**Issue by swilso793** [enigmampc/catalyst#125]
# Description of Issue

* What did you expect to happen?
Run example algorithms error free.
* What happened instead?
Example algorithms didn't run error free.
Here is how you can reproduce this issue on your machine:
Run example algorithms.
## What steps have you taken to resolve this already?
As far as i can tell you need to change all instances of 
`context.exchanges.values()[0]` 
to
`context.exchanges[exchange_name]`

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by swilso793** [comment]
exchange_name can be 'poloniex', 'bittrex', 'bitfinex'

**Comment by wnklb** [comment]
Isn't this a Python2/3 issue? Came across the same problem (using Python3.5) and `list(context.exchanges.values())[0]` fixed it for me.

**Comment by swilso793** [comment]
Isn't context.exchanges a 'ccxt' dictionary now? How can it have a values method?

**Comment by fredfortier** [comment]
I believe that we fixed the python 3 issues. Please let us know if you see anything else missing.
