### ISSUE TITLE
'invalid value encountered in log1p' encountered when running the beginner tutorial

### ISSUE THREAD

**Issue by johnny2678** [enigmampc/catalyst#126]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
`Linux catalyst 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

* Python Version: `$ python --version`
`Python 2.7.12`

* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
`64`

* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
`pip`

* Python packages: `$ pip freeze` or `$ conda list`
```
alembic==0.9.6
bcolz==0.12.1
boto3==1.5.7
botocore==1.8.21
Bottleneck==1.2.1
ccxt==1.10.534
certifi==2017.11.5
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.9.0
cyordereddict==1.0.0
Cython==0.27.3
decorator==4.1.2
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.4.0
futures==3.2.0
gyp==0.1
idna==2.6
intervaltree==2.1.0
jmespath==0.9.3
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==1.5.1
multipledispatch==0.4.9
networkx==2.0
numexpr==2.6.4
numpy==1.13.3
pandas==0.19.2
pandas-datareader==0.5.0
patsy==0.4.1
Pillow==3.1.2
pygobject==3.20.0
pyparsing==2.0.3
python-dateutil==2.4.2
python-editor==1.0.3
pytz==2017.3
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
s3transfer==0.1.12
scipy==1.0.0
six==1.10.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.0
statsmodels==0.8.0
tables==3.4.2
toolz==0.9.0
urllib3==1.22
virtualenv==15.0.1
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Just getting in to the project, very cool!  Was trying out the tutorial from the docs and hit this error in my normal python dev environment so I spun up a clean VM and am still getting the same error.

Algo I'm trying to run is `buy_btc_simple.py`.  The only modifications I've made from the tutorial is I'm using `poloniex` instead of `bitfinex` and the date range I'm using is `2017-01-01` to `2017-12-31`.

* What did you expect to happen?
successful example run

* What happened instead?
```
john@catalyst:~$ catalyst run -f algo/buy_btc_simple.py -x poloniex --start 2017-1-1 --end 2017-12-31 -c usd --capital-base 1000 -o buy_btc_simple_out.pickle
Running in backtesting mode.
[2017-12-31 12:33:00.551724] INFO: run_algo: running algo in paper-trading mode
[2017-12-31 12:33:02.256532] INFO: exchange_bundle: pricing data for [u'btc_usdt'] not found in range 2015-03-01 00:00:00+00:00 to 2017-12-28 00:00:00+00:00, updating the bundles.
    [====================================]  Ingesting daily price data for btc_usdt on poloniex:  100%
[2017-12-31 12:33:03.368525] INFO: Loader: Cache at /home/john/.catalyst/data/treasury_curves.csv does not have data from 1990-01-02 00:00:00+00:00 to 2017-12-28 00:00:00+00:00.
[2017-12-31 12:33:03.368731] INFO: Loader: Downloading treasury data for 'btc_usdt'.
[2017-12-31 12:33:04.894182] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Traceback (most recent call last):
  File "/usr/local/bin/catalyst", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/catalyst/__main__.py", line 102, in _
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/catalyst/__main__.py", line 287, in run
    stats_output=None,
  File "/usr/local/lib/python2.7/dist-packages/catalyst/utils/run_algo.py", line 346, in _run
    overwrite_sim_params=False,
  File "/usr/local/lib/python2.7/dist-packages/catalyst/exchange/exchange_algorithm.py", line 318, in run
    data, overwrite_sim_params
  File "/usr/local/lib/python2.7/dist-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/usr/local/lib/python2.7/dist-packages/catalyst/gens/tradesimulation.py", line 235, in transform
    yield self._get_daily_message(dt, algo, algo.perf_tracker)
  File "/usr/local/lib/python2.7/dist-packages/catalyst/gens/tradesimulation.py", line 291, in _get_daily_message
    dt, self.data_portal,
  File "/usr/local/lib/python2.7/dist-packages/catalyst/finance/performance/tracker.py", line 393, in handle_market_close
    account.leverage)
  File "/usr/local/lib/python2.7/dist-packages/catalyst/finance/risk/cumulative.py", line 165, in update
    self.algorithm_returns
  File "/usr/local/lib/python2.7/dist-packages/empyrical/stats.py", line 147, in cum_returns
    df_cum = np.exp(nancumsum(np.log1p(returns)))
RuntimeWarning: invalid value encountered in log1p
```

My `buy_btc_simple.py`:

```
from catalyst import run_algorithm
from catalyst.api import order, record, symbol
import pandas as pd


def initialize(context):
    context.asset = symbol('btc_usdt')


def handle_data(context, data):
    order(context.asset, 1)
    record(btc=data.current(context.asset, 'price'))


if __name__ == '__main__':
    run_algorithm(
        capital_base=1000,
        data_frequency='daily',
        initialize=initialize,
        handle_data=handle_data,
        exchange_name='poloniex',
        algo_namespace='buy_btc_polo_jh',
        base_currency='usd',
        start=pd.to_datetime('2017-01-01', utc=True),
        end=pd.to_datetime('2017-12-31', utc=True),
    )
```

## What steps have you taken to resolve this already?

tried a clean dev environment

# Anything else?

...

Sincerely,
John

**Comment by fredfortier** [comment]
I was able to replicate this with your algo but not the samples. I'm investigating.

**Comment by blackwatertepes** [comment]
+1

I'm having the **same issue**, with the **same example**, for the **same date range**, but for the **bitfinex exchange**.

**Comment by fredfortier** [comment]
It fails here: catalyst/finance/risk/cumulative.py:165 with these values: 
![screenshot 2018-01-03 16 16 02](https://user-images.githubusercontent.com/1474114/34540173-8f0daab0-f0a1-11e7-8328-f059f3aef8d0.png)
This list of number looks fine though. It correspond to the pnl of the algorithm every day which I revalidated.

Looking deeper, it fails on np.log1p with this list: 
![screenshot 2018-01-03 16 21 01](https://user-images.githubusercontent.com/1474114/34540349-3b107b58-f0a2-11e7-9eca-0d97e8c15a29.png)
Again, these numbers are looks fine to me, the correspond to the actual algo returns so we can't modify them. I'll implement a workaround and reach out to the zipline team for a more permanent solution.

**Comment by fredfortier** [comment]
I noticed that Quantopian rewrote `cum_returns()` (where the warnings are occurring) in the latest version of empyrical: https://github.com/quantopian/empyrical/blob/master/empyrical/stats.py. 

I tried replacing it and it fixed all the problems. Evidently, there is something about our crypto numbers (likely greater precision) which does not fit the old implementation and that Quantopian already caught. I'm going to see what I do to fix this, either upgrading empyrical or some kind of patch.

**Comment by fredfortier** [comment]
I was able to patch it. It's not pretty and it works. We'll need to rebase to latest zipline version soon which uses the latest empyrical. Just upgrading empyrical does not work because of common dependency issues.

**Comment by fredfortier** [comment]
This opened a bigger issue. I believe that the problematic behavior is fixed so I'm closing. We'll address this more broadly by rebasing to the latest zipline.

**Comment by Roconda** [comment]
Also ran into this issue using catalyst 0.4.4. Used empyrical 0.2.2 instead of 0.2.1, seems to solve it for me(Mac OS X, py 2.7ish).


`
pip install empyrical==0.2.2
`

**Comment by mrechung** [comment]
@Roconda That solution worked for me as well. Thank you!

**Comment by treethought** [comment]
I am experiencing this issue now as well occasionally for various algorithms.
The error is now occurring at `/catalyst/finance/risk/period.py", line 92, in calculate_metrics`. Looking at the file, I see that empyrical's `cum_returns` is still used and not the patch.

I'll try using the patch to see if it resolves the error, but figured I'd leave this info here for future reference.
