### ISSUE TITLE
Catalyst positions don't match with actual positions on Binance

### ISSUE THREAD

**Issue by quocble** [enigmampc/catalyst#132]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System:  Linux ip-172-30-0-229 4.4.44-39.55.amzn1.x86_64 #1 SMP Mon Jan 30 18:15:53 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.13 :: Continuum Analytics, Inc.
* Python Bitness: 64
* How did you install Catalyst: official conda
* Python packages: 

alembic                   0.9.6                     <pip>
backports.functools-lru-cache 1.4                       <pip>
bcolz                     0.12.1                    <pip>
boto3                     1.5.6                     <pip>
botocore                  1.8.20                    <pip>
Bottleneck                1.2.1                     <pip>
ccxt                      1.10.319                  <pip>
certifi                   2016.2.28                py27_0  
certifi                   2017.11.5                 <pip>
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.1                    <pip>
decorator                 4.1.2                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.4.0                     <pip>
futures                   3.2.0                     <pip>
idna                      2.6                       <pip>
intervaltree              2.1.0                     <pip>
jmespath                  0.9.3                     <pip>
libgfortran               3.0.0                         1  
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mkl                       2017.0.3                      0  
multipledispatch          0.4.9                     <pip>
networkx                  2.0                       <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0  
openssl                   1.0.2l                        0  
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
patsy                     0.4.1                     <pip>
pip                       9.0.1                    py27_1  
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0  
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2017.2                    <pip>
readline                  6.2                           2  
requests                  2.18.4                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     0.19.1              np113py27_0  
setuptools                36.4.0                   py27_1  
six                       1.11.0                    <pip>
sortedcontainers          1.5.7                     <pip>
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                        0  
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
TA-Lib                    0.4.10                    <pip>
tables                    3.4.2                     <pip>
tk                        8.5.18                        0  
toolz                     0.8.2                     <pip>
urllib3                   1.22                      <pip>
wheel                     0.29.0                   py27_0  
zlib                      1.2.11                        0  

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?

I'm running a live algo against Binance.  The positions are always greater than the actual positions on Binance, and this causes the sell to fail.

Actual differences:

Catalyst:
wings_btc 4019  (Binance: 4014)
gto_btc 17076  (Binance: 17059)
wtc_btc 467   (Binance: 466)
cdt_btc 32088   (Binance: 32055)

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Run live trading
2. Make at least one buy
3. Sell will fail on amount greater than actual

...

Sincerely,
Quoc

**Comment by fredfortier** [comment]
What are the differences? Binance orders will round up to the lot size. The
amount of the order and transaction objects will correspond to the amount
sent to Binance.

**Comment by quocble** [comment]
@fredfortier  - I don't know the root cause. I suspect binance take off some from the order for commission, so the value stored on catalyst is larger than the values on binance. As a result,  Sell order against the amount will fail.

**Comment by fredfortier** [comment]
I believe that this is resolved in the dev version. We currently sync the amount help in the exchange wallet with the exchange if the exchange amount is lower. This enables you to run multiple algos at once and to manual trading on the same wallet, just as long as you has enough position to cover the algo and avoid this issue. We'll plan to issue a release tomorrow as we have accumulated several worthwhile fixes and enhancements.

**Comment by fredfortier** [comment]
Please reopen if it's still happening in version 0.4.2.
