### ISSUE TITLE
Error on check balances in develop branch

### ISSUE THREAD

**Issue by caioaao** [enigmampc/catalyst#133]
It checks the `capital_base` against the free cash, so as soon as the algorithm buys something and the free cash goes below `capital_base`, the algo breaks.

**Comment by caioaao** [comment]
This is the check that fails: https://github.com/enigmampc/catalyst/blob/8d4caa2a1a9bfc79059199b01a8c307592309bd5/catalyst/exchange/exchange.py#L693

**Comment by fredfortier** [comment]
This is checking the free cash against the `base_currency` amount of the algo, not the `capital_base`. The difference between `capital_base` and `base_currency` is that `base_currency` is the cash value which gets updated when the algo buys something. This check insures that the free cash in the exchange does not go below the cash amount tracked by the algo, which would result in bad behavior when calling `order_target_percent(asset, 1)` for example.

Now, this check should always pass when the algorithm itself creates orders. It should only fail when cash value is lowered outside of the algorithm. This issue does not occur systematically but I will try to reproduce it.

**Comment by fredfortier** [comment]
I was able to reproduce this issue with Poloniex on a account low in cash: `catalyst.exchange.exchange_errors.NotEnoughCashError: Total btc amount on poloniex is lower than the cash reserved for this algo: 0.00718198 < 0.03. While trades can be made on the exchange accounts outside of the algo, exchange must have enough free btc to cover the algo cash.
`. It looks like its the cash value of the portfolio object with does gets updated after this check.

**Comment by fredfortier** [comment]
Fixed the root cause and re-tried under the same conditions.

**Comment by fredfortier** [comment]
Please reopen if it's still happening in version 0.4.2.
