### ISSUE TITLE
Position update fails (develop branch)

### ISSUE THREAD

**Issue by caioaao** [enigmampc/catalyst#134]
After closing a position, something went wrong and balances were out of sync. Catalyst keeps trying to update the position, but it doesn't work, so it keeps printing this message:
`[2018-01-02 12:32:02.069105] WARNING: Exchange: detected lower balance for btc_usdt on poloniex: 0.0 < [redacted], updating position amount`
The weird thing is that the position is not included in the statistics, but is still on the portfolio object

**Comment by fredfortier** [comment]
I do see that that it tries to perform this adjustment after a Poloniex buy order:
```
[2018-01-03 02:07:49.617403] WARNING: Exchange: detected lower balance for eth_btc on poloniex: 0.51352823 < 0.51481526, updating position amount
```
This is interesting because the position amount 0.51481526 comes from Poloniex. The original amount in the wallet before the transaction was 0. I looks like Poloniex takes its fee after the filling the order instead of deducting a commission amount during the order. Perhaps this can be improved at the CCXT level.

I do expect the program to adjust its position amount when finding a lower amount on the exchange. 

I haven't reproduced the particular issue yet.

**Comment by fredfortier** [comment]
I used sensitive settings on the `mean_reversion_simple.py` trading `btc_usd` on Poloniex. Other that the behavior mentioned above, I have not been able to make it crash.
```
Market | Type | Category | Price/Share | Amount | Fee | Total | Transaction Date
-- | -- | -- | -- | -- | -- | -- | --
  | ETH/BTC | Buy | Exchange | 0.05840490 | 0.51481526 | 0.00128704 ETH (0.25%) | 0.03006773 BTC | 2018-01-03 02:07:19
  | ETH/BTC | Sell | Exchange | 0.05830273 | 0.51252847 | 0.00007470 BTC (0.25%) | 0.02980710 BTC | 2018-01-03 02:02:09
  | ETH/BTC | Buy | Exchange | 0.05838698 | 0.51381300 | 0.00128453 ETH (0.25%) | 0.02999998 BTC | 2018-01-03 01:52:08
  | ETH/BTC | Sell | Exchange | 0.05825415 | 0.50802112 | 0.00007399 BTC (0.25%) | 0.02952034 BTC | 2018-01-03 01:51:55
  | ETH/BTC | Buy | Exchange | 0.05899895 | 0.50929435 | 0.00127324 ETH (0.25%) | 0.03004783 BTC | 2018-01-03 01:41:32
  | ETH/BTC | Sell | Exchange | 0.05890504 | 0.50806381 | 0.00007482 BTC (0.25%) | 0.02985269 BTC | 2018-01-03 01:40:51
  | ETH/BTC | Buy | Exchange | 0.05890000 | 0.50933715 | 0.00127334 ETH (0.25%) | 0.02999995 BTC | 2018-01-03 01:34:25
  | ETH/BTC | Sell | Exchange | 0.05854083 | 0.51174841 | 0.00007490 BTC (0.25%) | 0.02988327 BTC | 2018-01-03 01:32:10
  | ETH/BTC | Buy | Exchange | 0.05847597 | 0.51303098 | 0.00128258 ETH (0.25%) | 0.02999998 BTC | 2018-01-03 01:25:02
  | ETH/BTC | Sell | Exchange | 0.05818000 | 0.51836807 | 0.00007540 BTC (0.25%) | 0.03008325 BTC | 2018-01-02 23:59:18
  | ETH/BTC | Buy | Exchange | 0.05772925 | 0.51966723 | 0.00129917 ETH (0.25%) | 0.02999999 BTC | 2018-01-02 23:48:04
  | ETH/BTC | Sell | Exchange | 0.05764001 | 0.51785890 | 0.00007462 BTC (0.25%) | 0.02977477 BTC | 2018-01-02 23:47:42
  | ETH/BTC | Buy | Exchange | 0.05791667 | 0.51915679 | 0.00129789 ETH (0.25%) | 0.03006783 BTC | 2018-01-02 23:46:04
  | ETH/BTC | Sell | Exchange | 0.05808009 | 0.45501391 | 0.00003964 BTC (0.15%) | 0.02638760 BTC | 2018-01-02 23:43:56
  | ETH/BTC | Sell | Exchange | 0.05808010 | 0.06009013 | 0.00000873 BTC (0.25%) | 0.00348131 BTC | 2018-01-02 23:43:55
  | ETH/BTC | Buy | Exchange | 0.05828656 | 0.03300000 | 0.00008250 ETH (0.25%) | 0.00192345 BTC | 2018-01-02 23:40:0
```
I'll keep investigating tomorrow in context of finalizing our unit test coverage.

**Comment by caioaao** [comment]
Maybe It happened after placing a sell order and crashing, but I'm not sure, as I don't have the stack trace

**Comment by fredfortier** [comment]
Please reopen if it's still happening in version 0.4.2.
