### ISSUE TITLE
_run() takes exactly 26 arguments while __main__ using _run with 25 arguments

### ISSUE THREAD

**Issue by markguo40** [enigmampc/catalyst#137]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: MacOS Version 10.12.1
* Python Version: Python 2.7.13
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages:
alembic                   0.9.6                     <pip>
backports.functools-lru-cache 1.4                       <pip>
bcolz                     0.12.1                    <pip>
boto3                     1.5.8                     <pip>
botocore                  1.8.22                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0  
ccxt                      1.10.283                  <pip>
certifi                   2016.2.28                py27_0  
certifi                   2017.11.5                 <pip>
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.1                    <pip>
decorator                 4.1.2                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.4.2                     <pip>
futures                   3.2.0                     <pip>
idna                      2.6                       <pip>
intervaltree              2.1.0                     <pip>
jmespath                  0.9.3                     <pip>
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mkl                       2017.0.3                      0  
multipledispatch          0.4.9                     <pip>
networkx                  2.0                       <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0  
openssl                   1.0.2l               h492a243_5  
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
patsy                     0.4.1                     <pip>
pip                       9.0.1                    py27_1  
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0  
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2017.2                    <pip>
readline                  6.2                           2  
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     0.19.1              np113py27_0  
setuptools                36.4.0                   py27_1  
six                       1.11.0                    <pip>
sortedcontainers          1.5.7                     <pip>
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                        0  
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
tables                    3.4.2                     <pip>
tk                        8.5.18                        0  
toolz                     0.8.2                     <pip>
urllib3                   1.22                      <pip>
wheel                     0.29.0                   py27_0  
zlib                      1.2.11               hf3cbc9b_2  

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I was trying to follow the documentation tutorial and using catalyst run, but it throw a error

I type in catalyst run -f buy_btc_simple.py -x bitfinex --start 2016-1-1 --end 2017-9-30 -c usd --capital-base 100000 -o buy_btc_simple_out.pickle

And it gives me this error. I follow the tutorial and all the previous steps has been done:
Create buy_btc_simple.py file, ingest bitfinex data etc. 

* What did you expect to happen?
Backtesting buy_btc_simple.py

* What happened instead?
TypeError: _run() takes exactly 26 arguments (25 given)

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Install Conda
2. Follow [tutorial] (https://enigmampc.github.io/catalyst/beginner-tutorial.html)
3. Up until the point where you do catalyst run command

## What steps have you taken to resolve this already?
I look into the code. In the catalyst/catalyst/utils/run_algo.py, _run function takes an argument called analyze_live. Yet in catalyst/__main__.py, all the _run function call does not pass in this argument.

Maybe just add an default argument like analyze_live = True or False to solve this

Sincerely,
Zhanchen Guo

**Comment by fredfortier** [comment]
Got it, will fix asap.

**Comment by fredfortier** [comment]
Found the issue. I will publish a new release.

**Comment by fredfortier** [comment]
Fixed in new 0.4.3 release, thanks for reporting this!

**Comment by markguo40** [comment]
Great! Thanks!

**Comment by RobertSandiford** [comment]
Related?

catalyst run -f buy_xmr_simple.py -x bittrex --start 2017-1-1 --end 2018-12-31 -c usd --capital-base 1 -o buy_xmr_simple_out.pickle

Running in backtesting mode.
Traceback (most recent call last):
  File "c:\programdata\miniconda2\envs\catalyst\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\programdata\miniconda2\envs\catalyst\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ProgramData\Miniconda2\envs\catalyst\Scripts\catalyst.exe\__main__.py", line 9, in <module>
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 102, in _
    return f(*args, **kwargs)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\programdata\miniconda2\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 288, in run
    stats_output=None,
TypeError: _run() takes exactly 27 arguments (26 given)

**Comment by fredfortier** [comment]
Looking into this now.

**Comment by fredfortier** [comment]
Fixed. Thanks again for reporting this. We tend to focus too much on the `run_algorithm` interface and not enough on the CLI. We'll make sure that this does not occur again. We'll push a new release now to address this.

**Comment by RobertSandiford** [comment]
Cheers.

I like unit tests for this kind of thing ;)
