### ISSUE TITLE
 "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NgKK24/enigma-catalyst/ when trying to install

### ISSUE THREAD

**Issue by jm789** [enigmampc/catalyst#138]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux ip-172-31-9-14 4.9.70-25.242.amzn1.x86_64 #1 SMP Wed Jan 3 05:36:22 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.14 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages: # packages in environment at /home/ec2-user/anaconda2/envs/catalyst:
#
ca-certificates           2017.08.26           h1d4fec5_0
certifi                   2017.11.5        py27h71e7faf_0
intel-openmp              2018.0.0             hc7b2577_8
libedit                   3.1                  heed3624_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 7.2.0                h7cc24e2_2
libgfortran-ng            7.2.0                h9f7466a_2
libstdcxx-ng              7.2.0                h7a57d05_2
mkl                       2018.0.1             h19d6760_4
ncurses                   6.0                  h9df7e31_2
numpy                     1.13.3           py27hbcc08e0_0
openssl                   1.0.2n               hb7f436b_0
pip                       9.0.1            py27ha730c48_4
python                    2.7.14              h1571d57_29
readline                  7.0                  ha6073c6_4
scipy                     1.0.0            py27hf5f0f52_0
setuptools                36.5.0           py27h68b189e_0
sqlite                    3.20.1               hb898158_2
tk                        8.6.7                hc745277_3
wheel                     0.30.0           py27h2bc6bb2_1
zlib                      1.2.11               ha838bed_2

Now that you know a little about me, let me tell you about the issue I am
having:

# I am unable to install Catalyst inside the virtual environment. When trying to install, it consistently returns the error below:

[ec2-user@ip-172-31-9-14 ~]$ source activate catalyst
(catalyst) [ec2-user@ip-172-31-9-14 ~]$ pip install enigma-catalyst matplotlib
Collecting enigma-catalyst
  Using cached enigma-catalyst-0.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Plex/Scanners.py because it changed.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Plex/Actions.py because it changed.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Pythran.py because it changed.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Lexicon.py because it changed.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Scanning.py because it changed.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Parsing.py because it changed.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Visitor.py because it changed.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/FlowControl.py because it changed.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Code.py because it changed.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Runtime/refnanny.pyx because it changed.
    Compiling /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Tempita/_tempita.py because it changed.
    [ 1/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Code.py
    [ 2/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/FlowControl.py
    [ 3/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Lexicon.py
    [ 4/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Parsing.py
    [ 5/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Pythran.py
    [ 6/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Scanning.py
    [ 7/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Compiler/Visitor.py
    [ 8/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Plex/Actions.py
    [ 9/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Plex/Scanners.py
    [10/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Runtime/refnanny.pyx
    [11/11] Cythonizing /tmp/easy_install-6MgWyN/Cython-0.27.3/Cython/Tempita/_tempita.py
    warning: no files found matching '2to3-fixers.txt'
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    virtual memory exhausted: Cannot allocate memory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NgKK24/enigma-catalyst/setup.py", line 322, in <module>
        **conditional_arguments
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/ec2-user/anaconda2/envs/catalyst/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NgKK24/enigma-catalyst/

When installing with 
sudo pip install enigma-catalyst matplotlib

It then downloads the package and then appears to 'hang' the system with no response to the terminal until rebooted.

Am I missing something?

Sincerely,
Jaco

**Comment by fredfortier** [comment]
I'd say something is missing on your system. I don't think that this is a systematic error. Do you have gcc installed?

**Comment by lacabra** [comment]
@jm789 I see that you are trying to install on an AWS EC2 instance. See this section: https://enigmampc.github.io/catalyst/install.html#amazon-linux-ami-notes and let us know if this resolves your issue.

**Comment by jm789** [comment]
Thank you @lacabra , I somehow missed that section on the site. All working well now.

**Comment by MattielloX** [comment]
I have the same problem, how do I solve it?
____________________________________________
Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/a2/e5/697f7ec96c4808983711635ef2e4c6b217493343938410125bcece1642cf/tables-3.4.2.tar.gz (7.6MB)
    100% |████████████████████████████████| 7.6MB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    /tmp/H5close3tudbwoo.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^~~~
    /tmp/H5close3tudbwoo.c: In function ‘main’:
    /tmp/H5close3tudbwoo.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
         H5close();
         ^~~~~~~
    /usr/bin/ld: não foi possível localizar -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 3.7.2 (default, Dec 29 2018, 21:15:15)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-v0ycxq4r/tables/
[android project]# uname -a
Linux android 4.14.92-1-MANJARO #1 SMP PREEMPT Wed Jan 9 16:51:38 UTC 2019 x86_64 GNU/Linux
[android project]# 
__________________________________________________
