### ISSUE TITLE
bitfinex paper trading does not appear to correctly apply fees

### ISSUE THREAD

**Issue by gatapia** [enigmampc/catalyst#143]
paper trading using the bitfinex exchange does not appear to be applying small deposit fees:

https://www.bitfinex.com/fees

From the bitfinex fees page:
_A Small Deposit Fee is applied on deposits less than a 1000 USD equivalent. Many small deposits create an excess of tiny wallet inputs that can accumulate, requiring wallet input consolidation maintenance and eventually delaying customer withdrawals. In an effort to keep withdrawals flowing smoothly for all customers, avoid sending many small deposits. Instead, batch smaller deposits together into larger amounts._

When trading larger amounts the paper trade mode seems somewhat accurate but when trading small amounts it quickly diverges (over optimistic)

**Comment by fredfortier** [comment]
Good catch! I'll look closely into it.

**Comment by fredfortier** [comment]
I looked into it but I believe that the referenced statement applies to deposits, not trades. I don't see any stipulation that Bitfinex charges more than the maker and taker fees on trades. Do you have other reasons to think otherwise?

**Comment by gatapia** [comment]
You are right, looks like I misread.  And no, no evidence just reading the fees page and then tested backtest mode to see if you were applying fees correctly and found what I thought was that inconsistency.
