### ISSUE TITLE
Make explicit the stage of catalyst development on docs, press releases, etc

### ISSUE THREAD

**Issue by caioaao** [enigmampc/catalyst#146]
I must say that after 3 weeks fiddling with catalyst, I'm really disappointed with the lack of transparency. I discovered (and fixed) a great amount of issues and actually lost some money due to some bugs (the worst one was this: #145).

I think there's nothing wrong about releasing an OSS in pre-alpha stage, but this is something people with minimal programming knowledge are trying to use and there's little to no warnings on the docs about how "alpha" this project is. I'm a professional software engineer and this gave me some real headaches, to the point that I ditched catalyst altogether and wrote a live trading framework from scratch, relying on catalyst only for backtesting my algos (and even then it failed me __badly__, although I'm to blame too here for believing unrealistic results). To me, there should be a big red banner on top of everything related to catalyst, saying it's still not safe to use it. Hell, maybe even a warning on logs when trying to run live algorithms.

The project is in a real bad shape, and will put a lot of people's money at risk. You should be way more responsible with this.

**Comment by swilso793** [comment]
Maybe we as a society give our money a little to easy to something we have no understanding of. I agree though this project is in need of a lot more documentation. I built my own trading framework from 'scratch' as well. But it was nothing compared to the beauty of what catalyst can achieve with the help of this community. Cheers.

**Comment by fredfortier** [comment]
Duly noted. We've added an explicit warning in Catalyst 0.4.4 before running each algo. We'll also be more explicit in announcements.
