### ISSUE TITLE
No way to edit submitted strategies

### ISSUE THREAD

**Issue by damo1884** [enigmampc/catalyst#15]
No way to edit submitted strategies

**Comment by lacabra** [comment]
This is issue does not pertain to the Catalyst code, but the web interface. @guyz can you advise on where to report this issue, before I close it? Thank you

**Comment by lacabra** [comment]
@damo1884 thanks again for reporting this issue. This issue pertains to the catalyst web-app that has its own repository: https://github.com/enigmampc/catalystweb/
Kindly post it there to notify the repository maintainers. Closing it here.
