### ISSUE TITLE
Documentation update: please include how to update catalyst

### ISSUE THREAD

**Issue by gatapia** [enigmampc/catalyst#156]
I have a somewhat older version and there are no instructions for installation from source or to upgrade the conda environment.

A `conda update enigma-catalyst` while in the catalyst environment does not work

**Comment by lacabra** [comment]
Hi @gatapia, thanks for your interest in Catalyst, and pointing out the lack of documentation on this front. You should be able to update by running the following:
`activate catalyst` (Windows) or `source activate catalyst` (MacOS/Linux)
and then:
``` 
pip install -U enigma-catalyst
```

**Comment by gatapia** [comment]
Great, please feel free to close this but please consider updating the docs.  Also include how to install directly from git.

**Comment by lacabra** [comment]
Documentation on how to Update Catalyst has been added to the documentation:
https://enigmampc.github.io/catalyst/install.html#updating-catalyst

Thanks again. Closing issue.
