### ISSUE TITLE
Error in candles when simulating in live mode using binance exchange

### ISSUE THREAD

**Issue by manelrovira** [enigmampc/catalyst#169]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 2010
* Python Version: dataset
* Python Bitness: 32
* How did you install Catalyst: conda
* Python packages:

alembic==0.9.6
backports.functools-lru-cache==1.4
bcolz==0.12.1
boto3==1.5.12
botocore==1.8.26
Bottleneck==1.2.1
ccxt==1.10.637
certifi==2017.11.5
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
decorator==4.1.2
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.4.4
future==0.16.0
futures==3.2.0
idna==2.6
intervaltree==2.1.0
jmespath==0.9.3
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.1
multipledispatch==0.4.9
networkx==2.0
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.5.0
patsy==0.5.0
pyparsing==2.2.0
python-dateutil==2.6.1
python-editor==1.0.3
python-telegram-bot==9.0.0
pytz==2017.3
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
s3transfer==0.1.12
scipy==1.0.0
setuptools-scm==1.15.6
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.0
statsmodels==0.8.0
TA-Lib==0.4.14
tables==3.4.2
toolz==0.9.0
urllib3==1.22
wincertstore==0.2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

When simulating in live mode in binance exchange the two last candles returned by data.history() are always the same, returning different values for the same timestap.

```
import pandas as pd
from catalyst.utils.run_algo import run_algorithm
from catalyst.api import symbol

def initialize(context):
    context.i = 0
    context.data = []

def handle_data(context, data):
    prices = data.history(
        symbol('xlm_eth'),
        fields=['price', 'open', 'high', 'low', 'close'],
        bar_count=50,
        frequency='1T'
    )
    context.data.append(prices)

    context.i = context.i + 1
    if context.i == 3:
        context.interrupt_algorithm()

def analyze(context, prefs):
    for dataset in context.data:
        print dataset[-2:]

if __name__ == '__main__':
    run_algorithm(
        capital_base=0.1,
        initialize=initialize,
        handle_data=handle_data,
        analyze=analyze,
        exchange_name='binance',
        algo_namespace='Test candles',
        base_currency='eth',
        data_frequency='minute',
        start=pd.to_datetime('2017-12-31', utc=True),
        end=pd.to_datetime('2017-12-31', utc=True),
        live=True,
        simulate_orders=True)
```
Results:

```
                                close       high        low       open       price
2018-01-18 13:25:00+00:00  0.00049845  0.0004985  0.0004947  0.0004984  0.00049845
2018-01-18 13:26:00+00:00  0.00049845  0.0004985  0.0004947  0.0004984  0.00049845
                                close        high         low        open       price
2018-01-18 13:26:00+00:00  0.00049844  0.00049847  0.00049711  0.00049845  0.00049844
2018-01-18 13:27:00+00:00  0.00049844  0.00049847  0.00049711  0.00049845  0.00049844
                                close       high        low        open       price
2018-01-18 13:27:00+00:00  0.00049844  0.0004985  0.0004972  0.00049844  0.00049844
2018-01-18 13:28:00+00:00  0.00049844  0.0004985  0.0004972  0.00049844  0.00049844

```

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Execute de code provided
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
manel

**Comment by fredfortier** [comment]
I tried to reproduce this, but I wasn't able to reproduce what I'd consider an issue. Here are some of the results which I get. I verified the numbers against Binance.
```
[2018-01-18 23:04:20.250488] INFO: exchange_algorithm: portfolio balances, cash: 0.1, positions: 0.0
                                close        high         low        open
2018-01-18 22:55:00+00:00  0.00049301  0.00049326  0.00049301  0.00049326
2018-01-18 22:56:00+00:00  0.00049201  0.00049326  0.00049200  0.00049326
2018-01-18 22:57:00+00:00  0.00049299  0.00049302  0.00049200  0.00049299
2018-01-18 22:58:00+00:00  0.00049326  0.00049326  0.00049202  0.00049203
2018-01-18 22:59:00+00:00  0.00049324  0.00049326  0.00049200  0.00049300
2018-01-18 23:00:00+00:00  0.00049328  0.00049333  0.00049206  0.00049206
2018-01-18 23:01:00+00:00  0.00049220  0.00049328  0.00049215  0.00049328
2018-01-18 23:02:00+00:00  0.00049300  0.00049326  0.00049221  0.00049326
2018-01-18 23:03:00+00:00  0.00049232  0.00049300  0.00049221  0.00049232
2018-01-18 23:04:00+00:00  0.00049300  0.00049300  0.00049221  0.00049300
```

Keep in mind that the last candle is a partial candle, so the last two candles will often have the same values in the `1T` timeframe. In this case, I might have requested `2018-01-18 23:04:00` at `2018-01-18 23:04:02` which means that the numbers will be different only if some transactions occurred in the first two seconds. While this might seem odd, considering larger timeframes help justifying this approach. If my timeframe was `30T` for example, I might be interested in the partial candle. Let me know if you have a different preference regarding the last (partial) candle.
