### ISSUE TITLE
Question about use blance acc

### ISSUE THREAD

**Issue by cbogithub** [enigmampc/catalyst#170]
Dear Catalyst Maintainers,

I am new and i have question : if value of balance my binance account is 0.69 btc, however i only use 0.12btc for trading , so anyone give me example or a suggest ?

thanks,

**Comment by lacabra** [comment]
Use parameter ``capital_base``=0.12 as explained in the last section of this page of the documentation: https://enigmampc.github.io/catalyst/live-trading.html#trading-an-algorithm
