### ISSUE TITLE
[enhancement/suggestion] paper trading mode should use capital_base instead of cash on account

### ISSUE THREAD

**Issue by gatapia** [enigmampc/catalyst#175]
It would make more sense if paper trading used `capital_base` instead of the actual cash  in the account.

**Comment by fredfortier** [comment]
It does, it’s a required argument for all mode. The only difference in live
mode is that the account must have a balance at lest equal to the
capital_base, this is to prevent errors when placing orders. This
constraint does not apply to paper trading. Please let us know if you are
observing something different.

**Comment by gatapia** [comment]
Currently `context.portfolio.cash` returns the amount on the exchange not the `capital_base`.  

I use `context.portfolio.cash` as my available money to invest so in paper trading mode I would like to simulate scenarios without necessarily having the usdt available on the exchange.

Also, I would like to run paper trading for a few weeks to check things out, I really dont want to have cash just sitting in usdt for that time just so my simulation can run.

I think `capital_base` should be the `portfolio.starting_cash` catalyst should then update `portfolio.cash` as per backtest mode.

**Comment by fredfortier** [comment]
I'm not seeing this issue here. I'm running the `mean_reversion_sample.py` algo in paper mode with 100BTC (which unfortunately is lower than my balance). The algo executes properly:
```
[2018-01-24 05:36:30.399436] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-01-24 05:36:33.403673] INFO: run_algo: running algo in paper-trading mode
[2018-01-24 05:36:34.076510] INFO: exchange_bundle: pricing data for ['btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2018-01-23 00:00:00+00:00, updating the bundles.
Ingesting daily price data for btc_usd on bitfinex
Ingesting daily price data for btc_usd on bitfinex
[2018-01-24 05:36:36.565050] WARNING: Loader: Refusing to download new treasury data because a download succeeded at 2018-01-24 05:35:37.138128+00:00.
[2018-01-24 05:36:36.570202] INFO: exchange_algorithm: initialized trading algorithm in live mode
[2018-01-24 05:36:36.649438] INFO: exchange_algorithm: portfolio balances, cash: 100.0, positions: 0.0
```

Here is what happens when I don't simulate the orders (which is expected):
```
catalyst.exchange.exchange_errors.NotEnoughCashError: Total btc amount on poloniex is lower than the cash reserved for this algo: x < 100.0. While trades can be made on the exchange accounts outside of the algo, exchange must have enough free btc to cover the algo cash.
```
Can you confirm which version of Catalyst your are running?

**Comment by gatapia** [comment]
Sorry I missed this update.  

After updating catalyst (to 0.4.7) it appears to work.  Log file has:

```
WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
INFO: exchange_bundle: pricing data for [u'btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2018-01-25 00:00:00+00:00, updating the bundles.
Ingesting daily price data for btc_usd on bitfinex
INFO: exchange_algorithm: initialized trading algorithm in live mode
INFO: exchange_algorithm: portfolio balances, cash: 4000.0, positions: 0.0
INFO: exchange_algorithm: statistics for the last 1 minutes:
...
```
Will leave this running for a while and close this issue if it looks ok.

Thanks all

**Comment by gatapia** [comment]
Appears to be working now.  Thanks all
