### ISSUE TITLE
Running catalyst in jupyter gives error

### ISSUE THREAD

**Issue by eduedix** [enigmampc/catalyst#179]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
Darwin edair.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
* Python Version: `$ python --version`
Python 3.6.4
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
64
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
pipenv
* Python packages: `$ pip freeze` or `$ conda list`
aiodns==1.1.1
aiohttp==2.3.9
alembic==0.9.7
appnope==0.1.0
astroid==1.6.0
async-timeout==2.0.0
bcolz==0.12.1
bleach==2.1.2
boto3==1.5.19
botocore==1.8.33
Bottleneck==1.2.1
cchardet==2.1.1
ccxt==1.10.802
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
decorator==4.2.1
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.4.7
entrypoints==0.2.3
html5lib==1.0.1
idna==2.6
intervaltree==2.1.0
ipykernel==4.8.0
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.0
isort==4.2.15
jedi==0.11.1
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.1
jupyter-console==5.2.0
jupyter-core==4.4.0
lazy-object-proxy==1.3.1
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.2
mccabe==0.6.1
mistune==0.8.3
multidict==4.0.0
multipledispatch==0.4.9
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.0
notebook==5.3.1
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.5.0
pandocfilters==1.4.2
parso==0.1.1
patsy==0.5.0
pexpect==4.3.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pycares==2.3.0
Pygments==2.2.0
pylint==1.8.1
pyparsing==2.2.0
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
pyzmq==16.0.3
qtconsole==4.3.1
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
s3transfer==0.1.12
scipy==1.0.0
Send2Trash==1.4.2
simplegeneric==0.8.1
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.1
statsmodels==0.8.0
tables==3.4.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==4.5.3
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.0
wrapt==1.10.11
yarl==1.1.0

Now that you know a little about me, let me tell you about the issue I am
having:
I am trying the beginner tutorial  ( https://enigmampc.github.io/catalyst/beginner-tutorial.html#running-algorithms )now and having a problem with replicating the results of the jupyter notebook section.
# Description of Issue

* What happened instead?
I receive the following error:
https://pastebin.com/Jfna0ikD

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Copy and run jupyter notebook example in https://enigmampc.github.io/catalyst/beginner-tutorial.html#running-algorithms

# Anything else?
I think this might be helpful https://stackoverflow.com/questions/47820040/using-click-library-in-jupyter-notebook-cell

Sincerely,
eduedix

**Comment by gthouret** [comment]
I ran into the same issue, passing `sys.stdout` as the second parameter to all `echo` calls resolves the issue for me.  I've not regression tested this outside of Jupyter kernel.
If I get a chance I'll test and open a pull request with the maintainers.

**Comment by fredfortier** [comment]
Thanks for the PR. It looks good. We'll merge very soon.

**Comment by fredfortier** [comment]
Merged the PR.

**Comment by fredfortier** [comment]
In release 0.5.2
