### ISSUE TITLE
ImportError: No module named stats_utils

### ISSUE THREAD

**Issue by andrei-nutas** [enigmampc/catalyst#191]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

Environment
Operating System: windows 10
Python Version: python 2.7
Python Bitness: mean_reversion_simple exercise not working
How did you install Catalyst: conda

Python packages:

> alembic (0.9.6)
> backports.functools-lru-cache (1.4)
> bcolz (0.12.1)
> boto3 (1.5.20)
> botocore (1.8.34)
> Bottleneck (1.2.1)
> ccxt (1.10.774)
> certifi (2016.2.28)
> chardet (3.0.4)
> click (6.7)
> contextlib2 (0.5.5)
> cycler (0.10.0)
> cyordereddict (1.0.0)
> Cython (0.27.1)
> decorator (4.1.2)
> docutils (0.14)
> empyrical (0.2.1)
> enigma-catalyst (0.4.7)
> futures (3.2.0)
> idna (2.6)
> intervaltree (2.1.0)
> jmespath (0.9.3)
> Logbook (1.1.0)
> lru-dict (1.1.6)
> Mako (1.0.7)
> MarkupSafe (1.0)
> matplotlib (2.1.0)
> multipledispatch (0.4.9)
> networkx (2.0)
> numexpr (2.6.4)
> numpy (1.13.1)
> pandas (0.19.2)
> pandas-datareader (0.5.0)
> patsy (0.4.1)
> pip (9.0.1)
> pyparsing (2.2.0)
> python-dateutil (2.6.1)
> python-editor (1.0.3)
> pytz (2017.2)
> redo (1.6)
> requests (2.18.4)
> requests-file (1.4.2)
> requests-ftp (0.3.1)
> s3transfer (0.1.12)
> scipy (0.19.1)
> setuptools (36.4.0)
> six (1.11.0)
> sortedcontainers (1.5.7)
> SQLAlchemy (1.1.14)
> statsmodels (0.8.0)
> subprocess32 (3.2.7)
> tables (3.4.2)
> toolz (0.8.2)
> urllib3 (1.22)
> wheel (0.29.0)
> wincertstore (0.2)
> 
> 

Now that you know a little about me, let me tell you about the issue I am
having:

I'm trying to run the Dual Moving Average Crossover. After I write: python dual.py (I shortened the name of the file), I get the following error

(catalyst) C:\Users\nutas\OneDrive\Desktop>python dual.py
Traceback (most recent call last):
  File "dual.py", line 9, in <module>
    from catalyst.exchange.stats_utils import extract_transactions
ImportError: No module named stats_utils

## What steps have you taken to resolve this already?

I've searched online for the stats_utils package but there is no such package to be found. 

Why is this error happening? 
Can I replace "from catalyst.exchange.stats_utils import extract_transactions" with another command and get the desired outcome?

Sincerely,
Andrei

**Comment by JimmyMVP** [comment]
The Dual Moving Average Crossover example hasn't been updated I think. Instead of` from catalyst.exchange.stats_utils` it should be ` from catalyst.exchange.utils.stats_utils`

**Comment by andrei-nutas** [comment]
Hey @JimmyMVP,

Won't there then be a error down the line, towards the end of the code where we have the following: 

 transaction_df = extract_transactions(perf)
    if not transaction_df.empty:
        buy_df = transaction_df[transaction_df['amount'] > 0]
        sell_df = transaction_df[transaction_df['amount'] < 0]
        ax2.scatter(
            buy_df.index.to_pydatetime(),
            perf.loc[buy_df.index, 'price'],
            marker='^',
            s=100,
            c='green',
            label=''
        )
        ax2.scatter(
            sell_df.index.to_pydatetime(),
            perf.loc[sell_df.index, 'price'],
            marker='v',
            s=100,
            c='red',
            label=''
        )

**Comment by JimmyMVP** [comment]
Sorry, this is the complete line of code: `from catalyst.exchange.utils.stats_utils import extract_transactions`

**Comment by andrei-nutas** [comment]
Thanks, everything is working fine now :)
