### ISSUE TITLE
Add documentation for setting up Catalyst with PyCharm IDE

### ISSUE THREAD

**Issue by lacabra** [enigmampc/catalyst#192]
It would be great to add another section to the [Catalyst Tutorial](https://enigmampc.github.io/catalyst/beginner-tutorial.html) that documents how to run Catalyst using the PyCharm IDE, somewhat analogous to the section on the [Jupyter Notebook](https://enigmampc.github.io/catalyst/beginner-tutorial.html#jupyter-notebook).

If you are interested, submit a Pull Request (PR) against the `develop` branch with your edits to the corresponding source file: https://github.com/enigmampc/catalyst/blob/master/docs/source/beginner-tutorial.rst

Thank you!

**Comment by airgoruizm** [comment]
Hi Lacabra, I met the same problem. when I try to run the example code in Pycharm IDE, it shows me “ImportError: No module named catalyst” on line “from catalyst import run_algorithm”. It seems I have to installed catalyst on pycharm environment that I am using. Do you know how to do that? thanks :)
![example](https://user-images.githubusercontent.com/35883970/35479976-1818fa7e-03d2-11e8-8b7a-225058d59022.png)

**Comment by lacabra** [comment]
Yes, in short, when you open a project in PyCharm, you need to specify which Python interpreter to use, otherwise it defaults to the system-wide, and you need to tell it to use the one inside the Anaconda or virtual environment where you have installed Catalyst.

**Comment by lacabra** [comment]
Closed by PR #195
