### ISSUE TITLE
TypeError: '>' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by Kiminaka** [enigmampc/catalyst#201]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (macOS High Sierra Version 10.13.1)
* Python Version: Python 3.6.1 :: Anaconda custom (x86_64)
* Python Bitness: 64
* How did you install Catalyst: pip install git+https://github.com/enigmampc/catalyst
* Python packages: 
aiodns==1.1.1
aiohttp==2.3.9
airflow==1.8.0
alabaster==0.7.10
alembic==0.8.10
amqp==2.1.4
anaconda-client==1.6.3
anaconda-navigator==1.6.2
anaconda-project==0.6.0
appnope==0.1.0
appscript==1.0.1
asn1crypto==0.22.0
astroid==1.4.9
astropy==1.3.2
async-timeout==2.0.0
attrs==17.2.0
Automat==0.6.0
Babel==2.4.0
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0rc1
bayesian-optimization==0.4.0
bcolz==0.12.1
bcrypt==3.1.3
beautifulsoup4==4.6.0
billiard==3.5.0.2
bitarray==0.8.1
blaze==0.10.1
bleach==1.5.0
bokeh==0.12.5
boto==2.46.1
boto3==1.5.22
botocore==1.8.36
Bottleneck==1.2.1
cachetools==2.0.1
cchardet==2.1.1
ccxt==1.10.944
celery==4.0.2
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
click==6.7
climate==0.4.6
cloudpickle==0.2.2
clyent==1.2.2
colorama==0.3.9
constantly==15.1.0
contextlib2==0.5.5
croniter==0.3.17
cryptography==1.8.1
cssselect==1.0.1
CVXcanon==0.1.1
cvxpy==0.4.11
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.25.2
cytoolz==0.8.2
dask==0.14.3
datashape==0.5.4
db.py==0.5.3
decorator==4.0.11
dill==0.2.7
distributed==1.16.3
docutils==0.13.1
downhill==0.4.0
dumdum==0.1.2
ecos==2.0.4
empyrical==0.2.1
enigma-catalyst==0.4.7+4.gc3662443
entrypoints==0.2.2
enum34==1.1.6
et-xmlfile==1.0.1
facebook-sdk==2.0.0
fancyimpute==0.2.0
fastcache==1.0.2
feedparser==5.2.1
filechunkio==1.8
filterpy==1.0.0
Flask==0.11.1
Flask-Admin==1.4.1
Flask-Cache==0.13.1
Flask-Cors==3.0.2
Flask-Login==0.2.11
flask-swagger==0.2.13
Flask-WTF==0.12
flower==0.9.2
funcsigs==1.0.0
future==0.16.0
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gapic-google-cloud-pubsub-v1==0.15.4
gapic-google-cloud-spanner-admin-database-v1==0.15.3
gapic-google-cloud-spanner-admin-instance-v1==0.15.3
gapic-google-cloud-spanner-v1==0.15.3
gevent==1.2.1
gitdb2==2.0.2
GitPython==2.1.5
google-auth==1.1.0
google-cloud==0.27.0
google-cloud-bigquery==0.26.0
google-cloud-bigtable==0.26.0
google-cloud-core==0.26.0
google-cloud-datastore==1.2.0
google-cloud-dns==0.26.0
google-cloud-error-reporting==0.26.0
google-cloud-language==0.27.0
google-cloud-logging==1.2.0
google-cloud-monitoring==0.26.0
google-cloud-pubsub==0.27.0
google-cloud-resource-manager==0.26.0
google-cloud-runtimeconfig==0.26.0
google-cloud-spanner==0.26.0
google-cloud-speech==0.28.0
google-cloud-storage==1.3.2
google-cloud-translate==1.1.0
google-cloud-videointelligence==0.25.0
google-cloud-vision==0.26.0
google-gax==0.15.14
google-resumable-media==0.2.3
googleapis-common-protos==1.5.2
GPy==1.8.0
GPyOpt==1.0.3
graphviz==0.8
greenlet==0.4.12
grpc-google-iam-v1==0.11.1
grpcio==1.6.0
gunicorn==19.3.0
h5py==2.7.0
HeapDict==1.0.0
html5lib==0.9999999
httplib2==0.10.3
hyperlink==17.3.1
idna==2.6
imagesize==0.7.1
incremental==17.5.0
intervaltree==2.1.0
ipykernel==4.6.1
ipython==5.3.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
isort==4.2.5
itsdangerous==0.24
jaconv==0.2.1
JapaneseTokenizer==1.3.6
jdcal==1.3
jedi==0.10.2
Jinja2==2.8.1
jmespath==0.9.3
joblib==0.11
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
Keras==2.0.5
knnimpute==0.1.0
kombu==4.0.2
kytea==0.1.3
lazy-object-proxy==1.2.2
llvmlite==0.18.0
locket==0.2.0
lockfile==0.12.2
Logbook==1.1.0
lru-dict==1.1.6
lxml==3.7.3
Mako==1.0.6
Markdown==2.6.8
MarkupSafe==0.23
matplotlib==2.0.2
mecab-python3==0.7
mistune==0.7.4
mlxtend==0.8.0
monotonic==1.3
mpmath==0.19
msgpack-python==0.4.8
multidict==4.1.0
multipledispatch==0.4.9
multiprocess==0.70.5
mysqlclient==1.3.10
navigator-updater==0.1.0
nbconvert==5.2.1
nbformat==4.3.0
neologdn==0.2.1
networkx==1.11
nltk==3.2.3
nose==1.3.7
notebook==5.0.0
numba==0.33.0
numexpr==2.6.2
numpy==1.14.0
numpydoc==0.6.0
oauth2client==3.0.0
odo==0.5.0
olefile==0.44
openpyxl==2.4.7
ordereddict==1.1
packaging==16.8
pandas==0.19.2
pandas-datareader==0.6.0
pandocfilters==1.4.1
paramiko==2.2.1
paramz==0.7.4
parsel==1.2.0
partd==0.3.8
pathlib2==2.2.1
patsy==0.4.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.1.1
plac==0.9.6
PlanOut==0.6.0
plotly==1.9.5
ply==3.8
prettytable==0.7.2
prompt-toolkit==1.0.14
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
proto-google-cloud-pubsub-v1==0.15.4
proto-google-cloud-spanner-admin-database-v1==0.15.3
proto-google-cloud-spanner-admin-instance-v1==0.15.3
proto-google-cloud-spanner-v1==0.15.3
protobuf==3.4.0
psutil==4.4.2
psycopg2==2.7.3.1
ptyprocess==0.5.1
py==1.4.33
pyasn1==0.3.4
pyasn1-modules==0.1.4
pybars3==0.9.3
pycares==2.3.0
pycosat==0.6.2
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
PyDispatcher==2.0.5
pydot==1.2.3
pydotplus==2.0.2
pyflakes==1.5.0
Pygments==2.2.0
pykakasi==0.24
pyknp==0.3
pylint==1.6.4
pymc3==3.1
PyMeta3==0.5.1
pymongo==3.6.0
PyMySQL==0.7.11
PyNaCl==1.1.2
pyodbc==4.0.16
pyOpenSSL==17.0.0
pypandoc==1.4
pyparsing==2.1.4
pytest==3.0.7
python-daemon==2.1.2
python-dateutil==2.6.0
python-editor==1.0.3
python-nvd3==0.14.2
python-slugify==1.1.4
pytz==2017.2
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.0
QtPy==1.2.1
queuelib==1.4.2
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
rope-py3k==0.9.4.post1
rsa==3.4.2
s3transfer==0.1.10
scikit-image==0.13.0
scikit-learn==0.18.1
scipy==0.19.1
Scrapy==1.4.0
scs==1.2.7
seaborn==0.7.1
service-identity==17.0.0
setproctitle==1.1.10
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
smmap2==2.0.3
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.7
Sphinx==1.5.6
spyder==3.1.4
SQLAlchemy==1.1.9
sshtunnel==0.1.2
statsmodels==0.8.0
sympy==1.0
tables==3.3.0
tabulate==0.7.7
tblib==1.3.2
tenacity==4.4.0
tensorflow==1.2.1
terminado==0.6
testpath==0.3
Theano==0.9.0
thrift==0.9.3
toolz==0.8.2
tornado==4.5.1
tqdm==4.17.1
traitlets==4.3.2
Twisted==17.9.0
typing==3.6.2
unicodecsv==0.14.1
Unidecode==0.4.21
urllib3==1.22
vine==1.1.3
w3lib==1.18.0
wcwidth==0.1.7
Werkzeug==0.12.2
widgetsnbextension==2.0.0
wrapt==1.10.10
WTForms==2.1
xgboost==0.6a2
xlrd==1.0.0
XlsxWriter==0.9.6
xlwings==0.10.4
xlwt==1.2.0
yarl==1.1.0
zict==0.1.2
zope.deprecation==4.2.0
zope.interface==4.4.3

Now that you know a little about me, let me tell you about the issue I am
having:
an issue of returning performance output data (result) when I was trying out codes on this [Enigma's blog](https://blog.enigma.co/markowitz-portfolio-optimization-for-cryptocurrencies-in-catalyst-b23c38652556).  

* What did you expect to happen?
I was expecting to see performance dataframe when I `perf.head()`.

* What happened instead?
when `results`, I got:
`TypeError: '>' not supported between instances of 'int' and 'str'` and  I cannot export the `results` with `.to_csv(data_path)`

However, when I type(results), it is indeed `pandas.core.frame.DataFrame` and it can show info with `results.info`. I could specify columns and it could show the dataframe as well. 

Here is how you can reproduce this issue on your machine:
Just follow [the blog post code](https://github.com/enigmampc/catalyst/blob/master/catalyst/examples/portfolio_optimization.py) on Jupyter Notebook:
I installed the price data for each coins before running the code. 

Sincerely,
`kimi`

**Comment by fredfortier** [comment]
@AvishaiW or @lenak25 it would be great if you could take a look and try to replicate this.

**Comment by Kiminaka** [comment]
Solved. This was actually an easy fix when I included the parameter `base_currency = 'usdt'` in `run_algorithm`. I would suggest to update the blog post code to avoid the confusion.

**Comment by lacabra** [comment]
Thank you @Kiminaka for your suggestion. The code has been updated accordingly on our `develop` branch and will be included in our next release.
