### ISSUE TITLE
Cancel orders on binance fails - Binance requires the symbol to be included in the cancelled order.

### ISSUE THREAD

**Issue by Ericxgao** [enigmampc/catalyst#204]
Running cancel_order fails in Binance because binance needs an additional parameter - the symbol itself.

Looks like in exchange_algorithm.py it only passes in the order_id - which is insufficient for Binance.

**Comment by fredfortier** [comment]
Thanks for pointing this out. We'll make this change asap.

**Comment by dmbrady01** [comment]
Any word on the status of this bug?

**Comment by frisitano** [comment]
I agree with @dmbrady01, these issues are critical.  @dmbrady01 have you had better success trading on another exchange?  If so which exchange?

**Comment by AvishaiW** [comment]
Hi, I added the changes, please make sure it's working properly on your side.. Thanks and sorry on the delay!

**Comment by AvishaiW** [comment]
added on catalyst 0.5.4
