### ISSUE TITLE
Cancelling orders on binance causes issues with reordering

### ISSUE THREAD

**Issue by Ericxgao** [enigmampc/catalyst#207]
If you market buy, then make a limit sell, and cancel that limit sell, it looks like there are some issues with portfolio synchronization. Since the limit sell withdraws from your available balance on Binance, the client thinks you own less of the coin than you do, and for some reason, cancelling the order does not reset your clientside balance.

In addition, cancelling a limit sell doesn't seem to notify the exchange_blotter properly - I had to manually call cancel_all_orders_for_asset on the blotter object to get rid of the "order is still open" log.

Since the portfolio isn't synced - I can't make a market sell order with the order_target_percent anymore - I'll get a 

    Unable to create order on exchange binance binance {"msg":"Invalid quantity.","code":-1013}.

error. This would be expected since my portfolio thinks I have no coins available (they were still being locked up in the limit sell).

**Comment by fredfortier** [comment]
Thank you for reporting, we are looking into it.

**Comment by AvishaiW** [comment]
seems like an issue that was fixed in a previous release. I'm closing it, if it still occurs feel free to reopen. Thanks!
