### ISSUE TITLE
KeyError: 'lot' when trying to open live trade on bitfinex exchange

### ISSUE THREAD

**Issue by strmci** [enigmampc/catalyst#209]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 8)
* Python Version: Python 2.7.13
* Python Bitness: 
* How did you install Catalyst: conda
* Python packages: 
[pythonPackages.txt](https://github.com/enigmampc/catalyst/files/1692658/pythonPackages.txt)

Now that you know a little about me, let me tell you about the issue I am
having:

I am trying to run live trade on my bitfinex account but it doesn't work. I tried several order types as "order" and "order_target_percent" but it is not working
error: 
lot = self.markets[symbol]['lot']
KeyError: 'lot'
(error is also attached below)

* What did you expect to happen?
Open live trade on bitfinex.

* What happened instead?
Error occurred.

Here is how you can reproduce this issue on your machine:
## Reproduction Steps

Here is my code I am using:
[live_example.txt](https://github.com/enigmampc/catalyst/files/1692669/live_example.txt)

Here is log of an error I am getting.
[logError.txt](https://github.com/enigmampc/catalyst/files/1692670/logError.txt)

## What steps have you taken to resolve this already?

Tried several amounts, several orders. 
Wrote on discord catalyst channel, been advised to create issue here.

# Anything else?

Sincerely,
strmci

**Comment by strmci** [comment]
Update: Today I updated catalyst to version 0.4.7 and it seems it helped.

**Comment by fredfortier** [comment]
In release 0.5.2
