### ISSUE TITLE
Using multiple exchange pairs for run_algorithm()

### ISSUE THREAD

**Issue by Kiminaka** [enigmampc/catalyst#212]
Hi, I'm creating a portfolio and wondering how I can feed multiple pairs on multiple exchanges when running the algorithm with `run_algorithm`? I'd like to use 'usd' and 'usdt' as the base.

**Comment by fredfortier** [comment]
That last part is going to be a problem because USDT and USD are considered
different and an algo can only have one base currency. We’re working on a
branch which includes standardized symbols. We’ve delayed it a bit but we
are planning to release next week.

**Comment by Kiminaka** [comment]
@fredfortier Thanks for the comment. Understood. Great, looking forward to the release then :)

**Comment by Kiminaka** [comment]
Hi, 
Do you have an issue on the data ingestion from multiple exchanges for same base coin (such as BTC)? That'd be very useful for portfolio analysis.

**Comment by lenak25** [comment]
@Kiminaka ,

So just to be sure I understood you correctly, you are requesting 2 new features:
1. Being able to ingest from several exchanges
2. Being able to filter the symbols based on certain criteria - `base_currency` as to your example.

**Comment by Kiminaka** [comment]
@fredfortier 

Sorry for the confusion. I meant the 1 (ingesting from several exchanges). I think this feature will be very useful for crypto portfolio management.  I wasn't thinking about 2 but it'd be useful as well to filter currencies.

**Comment by lenak25** [comment]
Thanks for the clarification.. We will add this to our future features list.

Lena
