### ISSUE TITLE
get_exchange does not pass 'password' to gdax

### ISSUE THREAD

**Issue by dmbrady01** [enigmampc/catalyst#217]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: MacOS High Sierra 10.13.3
* Python Version: 2.7.13
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

Cannot trade on gdax exchange because gdax requires a key, secret, AND passphrase but 
```get_exchange``` in ```exchange/utils/factory.py``` only passes in key and secret
from auth.json

```
def get_exchange(...

    exchange = CCXT(
        exchange_name=exchange_name,
        key=exchange_auth['key'],
        secret=exchange_auth['secret'],
        base_currency=base_currency,
    )
```
https://docs.gdax.com/#authentication

* What did you expect to happen?
Be able to paper trade on gdax

* What happened instead?
```WARNING: CCXT: unable to fetch open orders gdax / eth_usd: gdax requires `password` ```
Here is how you can reproduce this issue on your machine:

 Anything else?

...

Sincerely,
`$ whoami`

**Comment by fredfortier** [comment]
@AvishaiW or @lenak25 can you take care of this one? It should simply be a matter of adding an optional "password" attribute to auth.json, then pass it to CCXT during instantiation. Here is how CCXT handles this: https://github.com/ccxt/ccxt/blob/master/python/ccxt/gdax.py

**Comment by AvishaiW** [comment]
Hi @dmbrady01, we added the option to add a password into the auth.json on the develop branch, please notify us if it's working. Thanks.

**Comment by dmbrady01** [comment]
Hi @AvishaiW. Yes it works for me, thanks

**Comment by AvishaiW** [comment]
added to catalyst 0.5.4
