### ISSUE TITLE
issues installing catalyst from pip (for Python 3 support)

### ISSUE THREAD

**Issue by gatapia** [enigmampc/catalyst#218]
My system had to be reinstalled (Ubuntu).  So after installing the miniconda, dependencies, etc.  I try to run `sudo pip install enigma-catalyst`.  Every thing looks fine, I can even run `catalyst --version` which returns 0.5.1 as expected.

However if I run `python -c 'import catalyst'` I get `ModuleNotFoundError: No module named 'catalyst'`

I have also tried `sudo pip3 install enigma-catalyst` which also completes with no errors.  If i run `pip list |grep catalyst` I get: `enigma-catalyst (0.5.1)`.

Not sure what else I should try, any help appreciated.

**Comment by fredfortier** [comment]
I'll try to replicate this in my environment now. We'll be releasing 0.5.2 shorting to include issue #216 fix.

**Comment by fredfortier** [comment]
I just installed in from scratch in a new python3 virtualenv using: `pip install enigma-catalyst` and it worked correctly. @lenak25 can you validate the same on Ubuntu?

**Comment by gatapia** [comment]
Must be something stale on my system, like I said, I'm recovering my ubuntu from OS corruption.  So some directories / lock files could be still around. I'll keep digging and close this once solved

**Comment by gatapia** [comment]
Had a mess with permissions, gave up trying to fix.  Ended up installing a new virtualenv and all was ok.  Sorry for the time waster. *closing*
