### ISSUE TITLE
Unable to subscribe to any data sets on marketplace

### ISSUE THREAD

**Issue by tingwai-to** [enigmampc/catalyst#222]
Unable to subscribe to any of the data sets listed in the documentation ([link](https://enigmampc.github.io/marketplace/data-sets.html)) 

Entering this command into terminal:
`$ catalyst marketplace subscribe --dataset=Marketcap`

Getting this response:
```
Using 0xmyaddress for this transaction.
The requested "marketcap" dataset is not registered in the Data Marketplace.
```
Environment:
* Operating System: Ubuntu 16.04
* Python Version: 3.5.2
* Python Bitness: 64
* How did you install Catalyst: pip

**Comment by lacabra** [comment]
Hi @tingwai-to the datasets will become available when we launch the data-marketplace on mainnet, after the smart contract has been audited by a third party. Even if the datasets were available right now, you wouldn't be able to subscribe to them because you would need test-ENG (analogous to test-ether), and that's not available either to the general public.

**Comment by tingwai-to** [comment]
I see, happy to hear that the marketplace is being actively tested. Are there other features of the marketplace that the general public can try out right now?

If I may, I would also suggest updating the marketplace [datasets documentation ](https://enigmampc.github.io/marketplace/data-sets.html)to reflect that datasets are not currently available for general public/while on testnet.

**Comment by lacabra** [comment]
Thank you for the suggestion. I have edited the documentation accordingly.

Answering your question, you get a preview of how the data marketplace will work, and if you would consider offering some of your datasets to the marketplace you have the specs to get it ready in advance of the release on mainnet.

**Comment by tingwai-to** [comment]
Much appreciated. Closing issue
