### ISSUE TITLE
Add to the documentation: keeping state between runs, and clearing it

### ISSUE THREAD

**Issue by lacabra** [enigmampc/catalyst#224]
From #216 as reported by @vonpupp:

Things like this are missing from the documentation `catalyst clean-algo -n my-algo-namespace` as well as documenting that anything you put on the `context.state` variable is preserved in between stopping and restarting an algo in live mode (#185).

This should be added to https://enigmampc.github.io/catalyst/live-trading.html

**Comment by EmbarAlmog** [comment]
Documentation was added at [this](https://github.com/enigmampc/catalyst/commit/3e2694465bf3db39100ee6e15c6eb686d3926301) commit.

**Comment by lenak25** [comment]
Added to release 0.5.9.
