### ISSUE TITLE
Not able to extract transactions and results table on paper mode

### ISSUE THREAD

**Issue by vonpupp** [enigmampc/catalyst#229]
Hello,

I am able to extract transactions on *backtesting* and plotting them by doing something like this:
```
from catalyst.exchange.utils.stats_utils import (
     extract_transactions,
     trend_direction
)

def analyze...
         transaction_df = extract_transactions(perf)
         transaction_df.to_csv('{}'.format(context.parameters.ALGO_NAMESPACE_TRANSACTIONS_TABLE))
         if not transaction_df.empty:
             buy_df = transaction_df[transaction_df['amount'] > 0]
             sell_df = transaction_df[transaction_df['amount'] < 0]
```

Would it be possible to also extract them from the results after the `run_algorithm` in papermode? Something like this:

```
         results = run_algorithm(
             capital_base=parameters.CAPITAL_BASE,
             data_frequency=parameters.DATA_FREQUECY,
             initialize=initialize,
             ...
         )

         results.to_csv('{}'.format(parameters.ALGO_NAMESPACE_RESULTS_TABLE))

         t = extract_transactions(results)
         t.to_csv('{}'.format(parameters.ALGO_NAMESPACE_TRANSACTIONS_TABLE))
```

I am not able to save the results on papermode, which I guess is a pre-requisite to save transactions. I am not sure how the run_algo results and perf relate to each other; maybe another method/function must be used.

Thank you very much.

**Comment by fredfortier** [comment]
Just for my understanding, why aren't you able to do this? The `analyze()` method should work the same. Or are you asking if you can do this while the algo is running?

**Comment by vonpupp** [comment]
Hello Fred,

I would like to do this after a `ctrl-c` stop on paper mode. The analyze does not seem to be triggered on paper mode, should it be?

**Comment by AvishaiW** [comment]
hi @vonpupp, you can access the data on csv files in your local directory at: ~/.catalyst/data/live_algos/%NAMESPACE% . as to analyze, it should trigger if you define a future end date, but i am investigating in order to make sure it works properly.

**Comment by vonpupp** [comment]
Thank you very much @AvishaiW.

The csv files on the local directory solves my problem so I am closing this issue.
