### ISSUE TITLE
Poloniex paper trading not working

### ISSUE THREAD

**Issue by Vijanator70** [enigmampc/catalyst#234]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
Windows 8.1
* Python Version: `$ python --version`
Python 2.7.13 :: Anaconda, Inc.
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
conda
* Python packages: `$ pip freeze` or `$ conda list`
# packages in environment at C:\Users\Vijay\Anaconda3\envs
#
alabaster                 0.7.10           py27h2cab13d_0
alembic                   0.9.6                     <pip>
astroid                   1.5.3            py27h658102e_0
attrdict                  2.0.0                     <pip>
babel                     2.5.0            py27h50e9d34_0
backports                 1.0              py27h6492d98_1
backports.functools-lru-cache 1.4                       <p
backports.functools_lru_cache 1.4              py27h9586e2
backports.shutil_get_terminal_size 1.0.0            py27h1
backports_abc             0.5              py27h0ec6b72_0
bcolz                     0.12.1                    <pip>
bleach                    2.1.1            py27h48e914a_0
boto3                     1.5.6                     <pip>
botocore                  1.8.20                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h94faf87_0
ccxt                      1.10.1074                 <pip>
certifi                   2016.2.28                py27_0
certifi                   2017.11.5                 <pip>
chardet                   3.0.4            py27h56c3b73_1
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
cloudpickle               0.5.2            py27h309b2ea_0
colorama                  0.3.9            py27hdfe4ae1_0
configparser              3.5.0            py27h2fa79a8_0
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.1                    <pip>
cytoolz                   0.9.0                     <pip>
decorator                 4.1.2            py27h383e199_0
decorator                 4.1.2                     <pip>
docutils                  0.14                      <pip>
docutils                  0.14             py27h8652d09_0
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.3                     <pip>
entrypoints               0.2.3            py27h0271f2b_2
enum34                    1.1.6            py27h2aa175b_1
eth-abi                   1.0.0b0                   <pip>
eth-account               0.1.0a2                   <pip>
eth-keyfile               0.5.0                     <pip>
eth-keys                  0.2.0b1                   <pip>
eth-rlp                   0.1.0a2                   <pip>
eth-utils                 1.0.0b1                   <pip>
functools32               3.2.3.2          py27h0cdbcdb_1
futures                   3.2.0                     <pip>
hexbytes                  0.1.0b0                   <pip>
html5lib                  1.0.1            py27h5a33001_0
icu                       57.1                      vc9_0
idna                      2.6                       <pip>
imagesize                 0.7.1            py27h1482bd8_0
intervaltree              2.1.0                     <pip>
ipykernel                 4.7.0            py27h5233db4_0
ipython                   5.4.1            py27hbf971b4_1
ipython_genutils          0.2.0            py27hbe997df_0
ipywidgets                7.1.0                     <pip>
isort                     4.2.15           py27hdc949c3_0
jedi                      0.11.0                   py27_2
jinja2                    2.10             py27hba1794b_0
jmespath                  0.9.3                     <pip>
jpeg                      9b                   ha175dff_2
jsonschema                2.6.0            py27haaf3834_0
jupyter                   1.0.0                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter_client            5.1.0            py27hced1786_0
jupyter_core              4.4.0            py27h1619e65_0
lazy-object-proxy         1.3.1            py27ha5c8080_0
libpng                    1.6.32               hc90de78_4
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
markupsafe                1.0              py27h9d4480d_1
matplotlib                2.1.0                     <pip>
mccabe                    0.6.1            py27hde0bf6e_1
mistune                   0.8.1            py27hf875dda_0
mkl                       2017.0.3                      0
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1            py27h7a573cf_0
nbformat                  4.4.0            py27hf49b375_0
networkx                  2.0                       <pip>
notebook                  5.2.2                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0
numpydoc                  0.7.0            py27hf7b062b_0
openssl                   1.0.2l            vc9hb274bc6_5
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py27h76461d3_1
parso                     0.1.1            py27hd69ea77_0
pathlib2                  2.3.0            py27h0ae272f_0
patsy                     0.4.1                     <pip>
pickleshare               0.7.4            py27hb5f6335_0
pip                       9.0.1                    py27_1
prompt_toolkit            1.0.15           py27h3a8ec6a_0
psutil                    5.4.1            py27h2104f53_0
pycodestyle               2.3.1            py27h24cd5d9_0
pycryptodome              3.4.11                    <pip>
pyflakes                  1.6.0            py27h34e7826_0
pygments                  2.2.0            py27ha50f84f_0
pylint                    1.7.4            py27h1f1ce2c_0
pyparsing                 2.2.0                     <pip>
pyqt                      5.6.0            py27h224ed30_5
pysha3                    1.0.2                     <pip>
python                    2.7.13              h1b6d89f_16
python-dateutil           2.6.1                     <pip>
python-dateutil           2.6.1            py27hbdcc174_1
python-editor             1.0.3                     <pip>
pytz                      2017.3           py27hca431c1_0
pytz                      2017.2                    <pip>
pyzmq                     16.0.3           py27he883654_0
qt                        5.6.2                     vc9_6
qtawesome                 0.4.4            py27h766b13d_0
qtconsole                 4.3.1            py27h77d40ac_0
qtpy                      1.3.1            py27h1ff2b4b_0
redo                      1.6                       <pip>
requests                  2.14.2                   py27_0
requests                  2.18.4                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
rope                      0.10.7           py27hb65afb6_0
s3transfer                0.1.12                    <pip>
scandir                   1.6              py27h518bda0_0
scipy                     0.19.1              np113py27_0
setuptools                36.4.0                   py27_1
simplegeneric             0.8.1            py27h2c3a90d_0
singledispatch            3.4.0.3          py27h3f9d112_0
sip                       4.18.1           py27h5ec1c1a_2
six                       1.11.0                    <pip>
six                       1.11.0           py27ha5e1701_1
snowballstemmer           1.2.1            py27h28d3bf7_0
sortedcontainers          1.5.7                     <pip>
sphinx                    1.6.3            py27h858dd0f_0
sphinxcontrib             1.0              py27h0e2fb95_1
sphinxcontrib-websupport  1.0.1            py27h0d0f901_1
spyder                    3.2.5                    py27_0
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                    vc9_1
ssl_match_hostname        3.5.0.1          py27hea8a0f4_2
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
TA-Lib                    0.4.10                    <pip>
tables                    3.4.2                     <pip>
testpath                  0.3.1            py27h1cd488d_0
tk                        8.5.18                    vc9_0
toolz                     0.8.2                     <pip>
tornado                   4.5.2            py27hbdd278e_0
traitlets                 4.3.2            py27h1b1b3a5_0
typing                    3.6.2            py27h9197bb0_0
urllib3                   1.22                      <pip>
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
wcwidth                   0.1.7            py27hb1a0d82_0
web3                      4.0.0b9                   <pip>
webencodings              0.5.1            py27h4e224a2_1
wheel                     0.29.0                   py27_0
widgetsnbextension        3.1.0                     <pip>
win_unicode_console       0.5              py27hc037021_0
wincertstore              0.2              py27hf04cefb_0
wrapt                     1.10.11          py27hcd2b27d_0
zlib                      1.2.11               hbc2faf4_2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Poloniex paper trading not working

* What did you expect to happen?
Expected functional backtesting algorithm would work in paper trading. Reduced to bare minimum code, changed to live=True, simulate_orders=True.

* What happened instead?

[2018-02-15 01:37:09.934000] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-02-15 01:37:12.940000] INFO: run_algo: running algo in paper-trading mode
[2018-02-15 01:37:12.944000] INFO: exchange_bundle: pricing data for [u'btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2018-02-14 00:00:00+00:00, updating the bundles.
Ingesting daily price data for btc_usd on bitfinex
[2018-02-15 01:37:14.023000] WARNING: Loader: Refusing to download new treasury data because a download succeeded at 2018-02-15 01:24:56.742556+00:00.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-facb1a9641f0> in <module>()
     18                                 base_currency='btc',
     19                                 simulate_orders=True,
---> 20                                 live=True)

C:\Users\Vijay\Anaconda3\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.pyc in run_algorithm(initialize, capital_base, start, end, handle_data, before_trading_start, analyze, data_frequency, data, bundle, bundle_timestamp, default_extension, extensions, strict_extensions, environ, live, exchange_name, base_currency, algo_namespace, live_graph, analyze_live, simulate_orders, auth_aliases, stats_output, output)
    547         simulate_orders=simulate_orders,
    548         auth_aliases=auth_aliases,
--> 549         stats_output=stats_output
    550     )

C:\Users\Vijay\Anaconda3\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.pyc in _run(handle_data, initialize, before_trading_start, analyze, algofile, algotext, defines, data_frequency, capital_base, data, bundle, bundle_timestamp, start, end, output, print_algo, local_namespace, environ, live, exchange, algo_namespace, base_currency, live_graph, analyze_live, simulate_orders, auth_aliases, stats_output)
    325         } if algotext is None else {
    326             'algo_filename': getattr(algofile, 'name', '<algorithm>'),
--> 327             'script': algotext,
    328         }
    329     ).run(

C:\Users\Vijay\Anaconda3\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.pyc in __init__(self, *args, **kwargs)
    369         self.frame_stats = list()
    370 
--> 371         self.pnl_stats = get_algo_df(self.algo_namespace, 'pnl_stats')
    372 
    373         self.custom_signals_stats = \

C:\Users\Vijay\Anaconda3\envs\catalyst\lib\site-packages\catalyst\exchange\utils\exchange_utils.pyc in get_algo_df(algo_name, key, environ, rel_path)
    352 
    353     """
--> 354     folder = get_algo_folder(algo_name, environ)
    355 
    356     if rel_path is not None:

C:\Users\Vijay\Anaconda3\envs\catalyst\lib\site-packages\catalyst\exchange\utils\exchange_utils.pyc in get_algo_folder(algo_name, environ)
    258 
    259     root = data_root(environ)
--> 260     algo_folder = os.path.join(root, 'live_algos', algo_name)
    261     ensure_directory(algo_folder)
    262 

C:\Users\Vijay\Anaconda3\envs\catalyst\lib\ntpath.pyc in join(path, *paths)
     65     result_drive, result_path = splitdrive(path)
     66     for p in paths:
---> 67         p_drive, p_path = splitdrive(p)
     68         if p_path and p_path[0] in '\\/':
     69             # Second path is absolute

C:\Users\Vijay\Anaconda3\envs\catalyst\lib\ntpath.pyc in splitdrive(p)
    113 
    114     """
--> 115     if len(p) > 1:
    116         normp = p.replace(altsep, sep)
    117         if (normp[0:2] == sep*2) and (normp[2:3] != sep):

TypeError: object of type 'NoneType' has no len()

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

Run in Jupyter Notebook

Code:
------------------------------------------------------------------------------
%load_ext catalyst

from catalyst.api import symbol
from catalyst.utils.run_algo import run_algorithm

def initialize(context):
    pass

def handle_data(context, data):
    pass

if __name__ == '__main__':

    performance = run_algorithm(
                                capital_base=1.0,  
                                initialize=initialize,
                                handle_data=handle_data,
                                exchange_name='poloniex',
                                data_frequency='minute',
                                base_currency='btc',
                                simulate_orders=True,
                                live=True)
----------------------------------------------------------------------------------

## What steps have you taken to resolve this already?

None, please help
...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by gatapia** [comment]
Same error on bitfinex, code:
```
from catalyst.utils.run_algo import run_algorithm

run_algorithm(
            initialize=lambda ctx: True,
            handle_data=lambda ctx, data: True,
            analyze=lambda ctx, data: True,
            exchange_name='bitfinex',
            base_currency='usd',
            capital_base=3000,
            algo_namespace='namespace',
            live=True,
            data_frequency='minute',
            simulate_orders=True)
```

Error:
```
PricingDataNotLoadedError: Missing data for bitfinex btc_usd in date range [2015-03-02 00:00:00+00:00 - 2018-02-14 00:00:00+00:00]
Please run: `catalyst ingest-exchange -x bitfinex -f daily -i btc_usd`. See catalyst documentation for details.

During handling of the above exception, another exception occurred:
```

I have tried running `catalyst ingest-exchange -x bitfinex -f daily -i btc_usd` and `clean-exchange + ingest` and it still fails.

**Comment by fredfortier** [comment]
Is this specific to Jupyther or do you get this with the command line also?
It’s failing to retrieve the “benchmark” data before starting the algo. We
need to move away from this now, there are too many problems fetching this
data from Bitfinex. We’ll get back to you shortly.

**Comment by gatapia** [comment]
Sorry I missed your message @fredfortier.

I have done some testing and have very strange results:
In Jupyter bitfinex/poloniex have the same error, for instance this code:
```
from catalyst.utils.run_algo import run_algorithm

run_algorithm(
            initialize=lambda ctx: True,
            handle_data=lambda ctx, data: True,
            analyze=lambda ctx, data: True,
            exchange_name='poloniex',
            base_currency='usdt',
            capital_base=3000,
            algo_namespace='namespace',
            live=True,
            data_frequency='minute',
            simulate_orders=True)
```
Throws Error:
```
[2018-02-16 20:45:50.672334] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-02-16 20:45:53.676332] INFO: run_algo: running algo in paper-trading mode
[2018-02-16 20:45:54.060008] INFO: exchange_bundle: pricing data for ['btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2018-02-15 00:00:00+00:00, updating the bundles.
---------------------------------------------------------------------------
PricingDataNotLoadedError                 Traceback (most recent call last)
~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_bundle.py in get_history_window_series_and_load(self, assets, end_dt, bar_count, field, data_frequency, algo_end_dt, force_auto_ingest)
    858                     field=field,
--> 859                     data_frequency=data_frequency,
    860                 )

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_bundle.py in get_history_window_series(self, assets, end_dt, bar_count, field, data_frequency, reset_reader)
   1004                     start_dt=asset_start_dt,
-> 1005                     end_dt=end_dt
   1006                 )

PricingDataNotLoadedError: Missing data for bitfinex btc_usd in date range [2015-03-02 00:00:00+00:00 - 2018-02-15 00:00:00+00:00]
Please run: `catalyst ingest-exchange -x bitfinex -f daily -i btc_usd`. See catalyst documentation for details.
```
So its still trying to get bitfinex pricing data even when using polo exchange.

**Note**: This is a single cell notebook, so nothing else is interfearing.

I copy and paste this into a stand alone python file and get this output:
```
[2018-02-16 20:44:04.318073] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-02-16 20:44:07.321261] INFO: run_algo: running algo in paper-trading mode
[2018-02-16 20:44:07.666386] INFO: exchange_bundle: pricing data for ['btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2018-02-15 00:00:00+00:00, updating the bundles.
    [====================================]  Ingesting daily price data for btc_usd on bitfinex:  100%
[2018-02-16 20:44:10.678791] INFO: Loader: Cache at /home/guido/.catalyst/data/treasury_curves.csv does not have data from 1990-01-02 00:00:00+00:00 to 2018-02-15 00:00:00+00:00.
[2018-02-16 20:44:10.678968] INFO: Loader: Downloading treasury data for 'btc_usd'.
[2018-02-16 20:44:15.817884] WARNING: Loader: Still don't have expected data after redownload!
[2018-02-16 20:44:18.668565] INFO: exchange_algorithm: portfolio balances, cash: 3000.0, positions: 0.0
[2018-02-16 20:44:18.679835] INFO: exchange_algorithm: statistics for the last 1 minutes:
                           starting_cash  ending_cash  portfolio_value  pnl  long_exposure  short_exposure  orders  transactions
period_close
2018-02-16 20:45:00+00:00           3000       3000.0           3000.0  0.0              0               0       0             0
```

So its still trying to get bitfinex data for polo backtest however the error is now just a warning.

**Comment by fredfortier** [comment]
Getting Bitfinex data for polo backtest is counterintuitive but expected.
It’s only getting btc-usdt data as a benchmark. You algo will run against
Poloniex. We need to come up with a better method because we hear of too
many instance when Bitfinex does not collaborate.

**Comment by Vijanator70** [comment]
When I run the above code in IDLE:

**Comment by Vijanator70** [comment]
Is there any solution in the works for this problem?

**Comment by AvishaiW** [comment]
this issue is related to #271 and #285. I added a temporary fix for them yesterday on the develop branch, please update if it works for you or not.

**Comment by lacabra** [comment]
Release 0.5.6 includes the fix @AvishaiW mentions above.
