### ISSUE TITLE
order target percent short?

### ISSUE THREAD

**Issue by Kiminaka** [enigmampc/catalyst#235]
Hi, 
Would it be possible to make a short position with order_target_percent or order_target_value method? Since Quantopian has that capability like `order_target_percent(sid(24), -0.1)  ` mentioned on [this link](https://www.quantopian.com/posts/order-target-percent-short), I was wondering if it's possible.

**Comment by AvishaiW** [comment]
Hi @kiminaka, we currently don't support  shortening, we hope to get to it very soon. Currently, when defining a negative number it sells the percentage from what you own.

**Comment by fredfortier** [comment]
@Kiminaka which exchange would you like to short with?

**Comment by Kiminaka** [comment]
@AvishaiW Thanks, understood. Looking forward to the functionality :)
@fredfortier It'd be great if I could use BitMex for this.

**Comment by lenak25** [comment]
@Kiminaka, thanks for the info, we do not yet support fully BitMex exchange but plan to add this functionality in the future.
