### ISSUE TITLE
Performance Optimization example: Performance not available

### ISSUE THREAD

**Issue by bouteill** [enigmampc/catalyst#241]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10
* Python Version: 2.7
* Python Bitness: 32
* How did you install Catalyst: with conda, updated with pip
* Python packages: ( pip freeze)
alembic==0.9.7
attrdict==2.0.0
backports.functools-lru-cache==1.4
bcolz==0.12.1
boto3==1.5.26
botocore==1.8.40
Bottleneck==1.2.1
ccxt==1.10.1094
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0
decorator==4.2.1
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.3
eth-abi==1.0.0b0
eth-account==0.1.0a2
eth-keyfile==0.5.0
eth-keys==0.2.0b1
eth-rlp==0.1.0a2
eth-utils==1.0.0b1
futures==3.2.0
hexbytes==0.1.0b0
idna==2.6
intervaltree==2.1.0
jmespath==0.9.3
Logbook==1.2.1
lru-dict==1.1.6
lxml==4.1.1
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
multipledispatch==0.4.9
networkx==2.1
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.6.0
patsy==0.5.0
pycryptodome==3.4.11
pyparsing==2.2.0
pysha3==1.0.2
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2018.3
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==0.6.0
s3transfer==0.1.12
scipy==1.0.0
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.2
statsmodels==0.8.0
subprocess32==3.2.7
TA-Lib==0.4.16
tables==3.4.2
toolz==0.9.0
urllib3==1.22
web3==4.0.0b9
wincertstore==0.2
wrapt==1.10.11

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I copied the example 'portfolio_optimization.py' and tried to backtest it. Unfortunately, performance value is not recorded. At the end of the example, the output reads: 

[2018-02-21 00:07:01.251000] INFO: Performance: Simulated 228 trading days out of 228.
[2018-02-21 00:07:01.252000] INFO: Performance: first open: 2017-01-01 00:00:00+00:00
[2018-02-21 00:07:01.252000] INFO: Performance: last close: 2017-08-16 23:59:00+00:00

Notably, I am using PyCharm 7.3 (not sure this could be the issue - I am a newbie with Catalyst).
Could you please provide any help as to how I could retrieve performance information?
Thank you very much for your help!

Sincerely,

**Comment by lenak25** [comment]
Hi @bouteill, 

At the end of the run, you should see a `portfolio_optimization.csv` created consisting of the data that was recorded at the `handle_data` function (you can see the file is created at the `analyze` function). Is that contains the information that you are missing?

Thanks,
Lena

**Comment by bouteill** [comment]
Hi Lena,
You are absolutely right. Portfolio value does appear as the last value in the CSV file.  
One question though:  which variable does it correspond to in the program?  I see all other columns of the CSV file as being recorded in the handle_data :  
        record(pr=pr,  # prices
               r=r,    # daily returns
               m=m,    # expected returns of each asset for the selected time window
               stds=stds,  # Standard deviations
               max_sharpe_port=max_sharpe_port,
               corr_m=corr_m) #asset correlation matrix
But the portfolio value is not recorded, yet, it appears on the CSV. Could you please pinpoint which variable contains portfolio value in the program? 
 
Additionally, I get the following warning during a few (not all) trades:
     WARNING: exchange_blotter: skipping 0 amount orders
Could you please provide some insights on this warning?
Thank you very much!

Jean-Marie

**Comment by bouteill** [comment]
I figured out the WARNING: it is not placing order when the weight is equal to ZERO.

**Comment by lenak25** [comment]
Hi @bouteill ,

The portfolio_value is part of the performance object which you can display and use in your code.
If you will follow the catalyst beginner tutorial (https://enigmampc.github.io/catalyst/beginner-tutorial.html) you can see which information is kept within the performance object.

Sorry for the delay in the response, hope it answers your question. 

Lena

**Comment by lenak25** [comment]
Hi @bouteill , I am closing this.
Feel free to reopen if something is unclear.
