### ISSUE TITLE
Develop Branch - Portfolio and position statistics aren't updating in paper trading

### ISSUE THREAD

**Issue by frisitano** [enigmampc/catalyst#249]
When paper trading with the develop branch portfolio statistics such as portolio_value, pnl etc don't update. The only portfolio statistic that updates correctly is positions.  Additionally, the positions last_sale_price does not update.

**Comment by fredfortier** [comment]
@AvishaiW could this be a side-effect of one of the latest changes?

**Comment by frisitano** [comment]
@fredfortier I do not think this is related to the commit (https://github.com/enigmampc/catalyst/commit/b4bd557273dd253b9adf4e02d68389a082d81f8f) @AvishaiW made last night.  When I cherry pick his commit from the master branch paper trading behaves as expected.

**Comment by frisitano** [comment]
I have identified the culprit causing the statistics to freeze.  It is associated with the changes made to exchange_algorithm in this commit https://github.com/enigmampc/catalyst/commit/20f8a75f4a8906641bbb1b198d05cc15148fff02. If we revert back to modifying original positions after we 'sync_positions' then it updates as expected.

**Comment by AvishaiW** [comment]
Thanks @frisitano! reverted changes from that commit..

**Comment by AvishaiW** [comment]
added to catalyst 0.5.4
