### ISSUE TITLE
MPC library

### ISSUE THREAD

**Issue by patricia93sousa** [enigmampc/catalyst#25]
Hello 

I was reading the documentation regarding this library but I'm curious about the library of mpc that you use. 
In the whitepaper you mention the mpc to anonymize the information, but in the external library you do not mention any mpc library. Which mpc library do you use ? 

Thanks in advance.

**Comment by lacabra** [comment]
Hi Patricia,

Thank you for your interest in Catalyst. First of all, Github is hosting the code and this section is for issues that need addressing or fixing in the code. I would encourage to find us on our slack group (https://engima.slack.com/), in the #dev channel in particular, to ask this type of questions and engage in a conversation. New signups to Slack are currently closed, but we expect to reopen them next week.

Answering your question: I believe you might be referring to the original Enigma whitepaper that was published in 2015. I encourage you read this post that talks on how the development of Catalyst fits in the new vision, and provides additional context to your question: https://blog.enigma.co/beyond-catalyst-enigmas-vision-for-the-future-of-data-22fbb5845556. Then, if you are interested, you can delve into Catalyst's whitepaper: https://www.enigma.co/enigma_catalyst.pdf. The short answer to your question is that Catalyst doesn't use the mpc library yet.
