### ISSUE TITLE
data.history() candle data seems out of sync / different to old versions

### ISSUE THREAD

**Issue by WPsites** [enigmampc/catalyst#255]
If I use data.history() to get say 15T candles with a bar count of 50 in older versions of Catalyst you get 51 data points for the first bar, if you do this in the current version you only get 50 data points for the first bar... bars in the middle of a run both come out at 51 items and it's like they are out of sync now because the new version has a data point at the start that that isn't present in the old version then the old version has a data point at the end that isn't on the new version. All of this seems to distort my data and turns strategies that came out 50% profit last month into 60% losers this month!

**Old version of Catalyst**

2018-01-24 23:00:00+00:00    11176.000000
2018-01-24 23:30:00+00:00    11391.000000
.....
2018-01-25 23:00:00+00:00    11143.000000
2018-01-25 23:30:00+00:00    11147.000000
2018-01-26 00:00:00+00:00    11224.000000

**Current version of catalyst**

2018-01-24 22:30:00+00:00    11095.000000
2018-01-24 23:00:00+00:00    11176.000000
.....
2018-01-25 22:30:00+00:00    11161.000000
2018-01-25 23:00:00+00:00    11143.000000
2018-01-25 23:30:00+00:00    11151.000000

Same algo, just run on different versions of Catalyst. Here is the output of both runs, the new version at the bottom, you can see the bolingerband in orange is out of sync
![results](https://user-images.githubusercontent.com/1165973/36681798-839b4134-1b11-11e8-8529-f85aa5a82088.png)

You might say it was broke before but now it's fixed. If that's the case, how can I manually remove say the last value from the resulting data? or the first value or whatever I wanted to try to remove. I tried just deleting the element but it didn't work. Python isn't a language im use to. Thanks

**Comment by WPsites** [comment]
The more I look at this, the more I feel like im losing my head. I'm looking at bitfinex, 2018-02-24  to 2018-02-25 and just checking standard talib RSI... Just picking a random candle out the middle and referencing it to tradingview data the closing price they have for the 03:00 candle is 10310.0  and trading view show RSI 57.67... I just need to figure out if it's an error or I'm doing something wrong. I'm expecting to get the same price and RSI figure that trading view show or extremely close, no use my algo seeing different to trading view and im guessing other chart systems too.

Using prices[-1] from the data.history(context.asset,fields='close',bar_count=50,frequency='15T') in the old version of catalyst is the only way, the new version of catalyst isn't showing the same value as trading view anywhere.

**new version**
2018-02-24 03:00:00+00:00 : currentinfo['close'] **10385.0** prices[-1] **10385.0**  rsi 63.51781347475125

**old version**
2018-02-24 03:00:00+00:00 : currentinfo['close'] **10385.0** prices[-1] **10310.0**  rsi 58.2068613853

I appreciate your help. thanks.

If you could show me an example algo/data that matches with trading view/bitfinex that would be amazing.

**Comment by fredfortier** [comment]
I believe that the reason why candles may not be matching TradingView is that, when requesting candles in backtest mode, the last candle has partial value. This fact relates to why the old Catalyst version which you are using shows you a different result. I feel strongly that the calculations are now accurate. What does `context.asset` correspond to in this example? I can look it up and export the underlying data for you so we can confirm the calculations.

**Comment by WPsites** [comment]
TradingPair(98871 [btc_usd])

I still don't really understand because I'm trying to look at candles in the middle which don't seem to match, none of them seem to match Trading view data. I've never checked RSI values on say Trading view and confirmed that they match the RSI values from another charting service but I'm assuming they all match up pretty closely and so should catalyst in order to have effective strategies.

**Comment by fredfortier** [comment]
Yes, you are absolutely correct that the numbers should match.

Regarding the last candle, if it's 3:00 for example. The 3:00 candle in TradingView would actually contain data between 3:00 and just before 3:15. In Catalyst, the current close would be the close of the last candle and other values would be different. I will pubbl the minute candle behind Bitfinex `btc_usd` at 2018-02-24 03:00:00+00:00 example to verify the calculations with you.

**Comment by WPsites** [comment]
Not sure if some changes were made to the underlying data today as I had data missing errors for a while which eventually seemed to clear. I've now run some tests on 30 minute candles and chosen one out of the middle which was the 12:00 candle on Trading view btc bitfinex which seems to match up with the 12:29 candle from Catalyst so that looks good... but the RSI still doesn't match with trading view even though it's using the same settings

**price and RSI for candle**
2018-02-25 12:29:00+00:00 : price 9580.1   rsi 44.14708896987167 

**Example of the .history data at this candle**
2018-02-24 11:30:00+00:00    9713.700000
2018-02-24 12:00:00+00:00    9735.400000
2018-02-24 12:30:00+00:00    9747.900000
2018-02-24 13:00:00+00:00    9582.700000
.... removed a chunk
2018-02-25 10:30:00+00:00    9651.100000
2018-02-25 11:00:00+00:00    9713.500000
2018-02-25 11:30:00+00:00    9651.000000
2018-02-25 12:00:00+00:00    9580.100000

**Here is output of the 30T RSI at the above candle**
rsi [        nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan 40.54905491 45.15433627 43.22393725 35.58807783
 34.78057782 37.0689917  41.57574585 48.00101259 48.23383395 50.72552032
 53.06901845 50.33394928 50.09449195 57.32216722 57.44487228 54.10214387
 47.21414575 43.59937261 45.19339534 54.1170235  54.31255553 52.32097869
 55.16509197 59.74351824 57.76334759 58.91883567 54.58416941 56.51135694
 44.96985173 46.69201262 45.44181882 46.46101828 49.01642525 53.54580496
 48.86336783 44.14708897]

Any idea why the RSI might not be coming out the same as trading view?

**Comment by fredfortier** [comment]
My first inclination would be to double check the RSI calculation
parameters (e.g. 14 periods) to make sure that everything matches. If still
does not match, we can help validating for you. The RSI calculation uses
ta-lib, a well-known library for this type of calculation, if the inputs
are correct (price array) then the output can be trusted.

**Comment by WPsites** [comment]
Yes TV is using the default 14 period as does my calculation 
rsi = talib.RSI(prices.values, timeperiod=14)
and talib.rsi using .history data never matches up to TV

**Comment by WPsites** [comment]
OK I've finally got to the bottom of the RSI issue!... so I think we are done here. Thanks for your help, all things are matching up now...

When using talib.RSI() your bar_count needs to be 20* the timeperiod, otherwise it will not match up with sites like Trading View
