### ISSUE TITLE
How can I suppress info messages in Jupyter?

### ISSUE THREAD

**Issue by chrism2671** [enigmampc/catalyst#256]
Conda install python 3 environment. Jupyterlab additionally installed.

I’ve tried the normal methods (setting the root logger settings and using the Jupyter magics), but I can’t seem to hide them. A one day backtest generates hundreds of info messages- how can I hide them?

**Comment by AvishaiW** [comment]
Hi @chrism2671, in order to pre define your log level you need to add an environment variable called 'CATALYST_LOG_LEVEL' with either one of the following numbers: 
CRITICAL = 15
ERROR = 14
WARNING = 13
NOTICE = 12
INFO = 11
DEBUG = 10
TRACE = 9
make sure to restart your'e notebook before using it.

**Comment by lacabra** [comment]
And for future reference, Catalyst sets the default at the INFO level.

**Comment by chrism2671** [comment]
I tried doing it with the magics:
`%env CATALYST_LOG_LEVEL = 15`
Should that work?

**Comment by AvishaiW** [comment]
I suppose it will work..

**Comment by chrism2671** [comment]
I did try it, unfortunately it doesn't seem to get picked up, although I think it should.

**Comment by AvishaiW** [comment]
I tried it as well and it seems that the only way it works is if you define it permanently as an environment variable. make sure to restart the terminal after defining it.
