### ISSUE TITLE
data.history number of returned candles can sometimes not match the bar_count

### ISSUE THREAD

**Issue by gatapia** [enigmampc/catalyst#260]
This was originally reported in #230 but may have been lost due to number of comments.

The following:
`data.history(['close', 'volume'], freq='5T', bar_count=1)`
Should return 1 candle but it can sometimes (1 in 5 times or so) return 2 candles.

`data.history(['close', 'volume'], freq='5T', bar_count=2)` 
Can sometimes return 3 candles.

This was tested on bitfinex and poloniex.

**Comment by lenak25** [comment]
Thanks @gatapia for opening a separate thread.
I was able to reproduce this phenomena as well, we will address this.
Thanks

**Comment by AvishaiW** [comment]
added to catalyst 0.5.4
