### ISSUE TITLE
Missing data on poloniex

### ISSUE THREAD

**Issue by jshridha** [enigmampc/catalyst#264]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10 and Linux x64
* Python Version: 3.6.4
* Python Bitness: 64
* How did you install Catalyst: pip install enigma-catalyst==0.5.3
* Python packages: aiodns==1.1.1
aiohttp==3.0.1
alembic==0.9.8
async-timeout==2.0.0
attrdict==2.0.0
attrs==17.4.0
bcolz==0.12.1
bintrees==2.0.7
bleach==2.1.2
boto3==1.5.36
botocore==1.8.50
Bottleneck==1.2.1
cchardet==2.1.1
ccxt==1.10.1189
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0
decorator==4.2.1
dispy==4.8.4
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.3
entrypoints==0.2.3
eth-abi==1.0.0b1
eth-account==0.1.0a2
eth-hash==0.1.0a4
eth-keyfile==0.5.1
eth-keys==0.2.0b2
eth-rlp==0.1.0a2
eth-utils==1.0.0b2
gdax==1.0.6
hexbytes==0.1.0b1
html5lib==1.0.1
idna==2.6
idna-ssl==1.0.0
intervaltree==2.1.0
ipykernel==4.8.2
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.2
jedi==0.11.1
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
Logbook==1.2.1
lru-dict==1.1.6
lxml==4.1.1
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.2
mistune==0.8.3
multidict==4.1.0
multipledispatch==0.4.9
nbconvert==5.3.1
nbformat==4.4.0
netifaces==0.10.6
networkx==2.1
notebook==5.4.0
numexpr==2.6.4
numpy==1.14.1
pandas==0.19.2
pandas-datareader==0.6.0
pandocfilters==1.4.2
parso==0.1.1
patsy==0.5.0
pexpect==4.4.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
psutil==5.4.3
ptyprocess==0.5.2
pycares==2.3.0
pycos==4.6.5
pycryptodome==3.4.11
Pygments==2.2.0
pyparsing==2.2.0
pysha3==1.0.2
python-dateutil==2.6.1
python-dotenv==0.7.1
python-editor==1.0.3
pytz==2018.3
pyzmq==17.0.0
qtconsole==4.3.1
redis==2.10.6
redo==1.6
requests==2.13.0
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==0.6.0
rq==0.10.0
s3transfer==0.1.13
scipy==1.0.0
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.10.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.4
statsmodels==0.8.0
TA-Lib==0.4.16
tables==3.4.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==4.5.3
tqdm==4.19.5
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
web3==4.0.0b10
webencodings==0.5.1
websocket-client==0.40.0
widgetsnbextension==3.1.4
wrapt==1.10.11
yarl==1.1.0

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I expected to be able to backtest an algorithm on BTC_USDT and ETH_USDT on poloniex.

* What happened instead?
No matter how many times I ingest the exchange data, I keep getting this error:
```
catalyst.exchange.exchange_errors.PricingDataNotLoadedError: Missing data for poloniex btc_usdt in date range [2018-02-25 12:01:00+00:00 - 2018-02-28 00:00:00+00:00]
Please run: `catalyst ingest-exchange -x poloniex -f minute -i btc_usdt`. See catalyst documentation for details.
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Clear .catalyst folder under user profile.
2. Re-ingest exchange data.
3. Run any algorithm that tries to collect data.history from the above mentioned range.

## What steps have you taken to resolve this already?
Tried to clear catalyst directory and re-ingest data.

...

# Anything else?
Any help would be great! Thanks a bunch.
...

**Comment by gatapia** [comment]
I have seen this before, it may be the same issue.  I had forgotten to activate my environment.  I.e. run `source activate <catalyst_env_name>` then do: `catalyst clean-exchange -x poloniex` then `catalyst ingest...`

**Comment by jshridha** [comment]
I just tried that and still having the same issue. I think the issue may be the data being held on enigma's servers.

**Comment by lenak25** [comment]
@jshridha thanks for reporting, I was able to reproduce your issue, we will investigate this.

**Comment by lacabra** [comment]
I believe this is related to #265, and I would guess that the missing data in your case is limited to 02/28/18 only.

**Comment by lacabra** [comment]
@jshridha, @gatapia This issue has been fixed. It affected all minute data for both Bitfinex and Poloniex for the month of February only, but not daily data. There was a boundary condition in which the bundles were not generated properly on the last day of the month. The bundles have been generated again for February, and the issue has been fixed to prevent from reoccurring moving forward. In order for the new bundles to load properly, you need to run:

catalyst clean-exchange -x poloniex

and then ingest again whatever data you need.

Here's a snapshot of Poloniex pricing data for a sample of 20 randomly-chosen assets available on the exchange plotting data between 02/1/18 and 02/28/18. There is barely enough resolution to be able to tell, but if there was data missing you would see a flat line at the end, which is not the case anymore.

![poloniex-feb2018](https://user-images.githubusercontent.com/6098973/36997579-50af561e-2077-11e8-8511-4774886a94df.png)

**Comment by jshridha** [comment]
@lacabra Thanks for handling that so quickly. This looks to be fixed for me now.

Do you have a repo for the code that generates the database on your end? If so, I'd be interested in seeing it so I can have a local mirror of the data.

Thanks again.

**Comment by lacabra** [comment]
That repo is not public for the time being.

You already have a mirror of that data in your hard drive by ingesting the data through catalyst, which is kept up to date every time you ingest again.
