### ISSUE TITLE
Missing data for 2018-2-28

### ISSUE THREAD

**Issue by benibienz** [enigmampc/catalyst#265]
Hi,

There seems to be some missing data for the 28th feb. I've seen it with bitfinex eth-usd and btc-usd. There is data either side of this day but only NaN in between.

**Comment by lenak25** [comment]
Thanks @benibienz for reporting. 
We are investigation this.

**Comment by lacabra** [comment]
@benibienz This issue has been fixed. It affected all `minute` data for both `Bitfinex` and `Poloniex` for the month of February only, but not daily data. There was a boundary condition in which the bundles were not generated properly on the last day of the month. The bundles have been generated again for February, and the issue has been fixed to prevent from reoccurring moving forward. In order for the new bundles to load properly, you need to run:

`catalyst clean-exchange -x bitfinex`

and then ingest again whatever data you need. 

Here's a snapshot of Bitfinex pricing data for a sample of 20 randomly-chosen assets available on the exchange plotting data between 02/1/18 and 02/28/18. There is barely enough resolution to be able to tell, but if there was data missing you would see a flat line at the end, which is not the case anymore.

![bitfinex-markets-feb2018](https://user-images.githubusercontent.com/6098973/36997453-ebd13410-2076-11e8-99cb-ad4c3b898af3.png)

**Comment by benibienz** [comment]
Thanks for the prompt reply and fix!
