### ISSUE TITLE
Unnecessary bifinex data loading

### ISSUE THREAD

**Issue by songaal** [enigmampc/catalyst#271]
Hi,
I want to use data from the poloniex exchange and it always load the bitfinex's btc_usd data every time I start the algorithm. It seems to be the default setting, since it does not load poloniex data, so it seems unnecessary. I am curious about future development direction.

**Comment by AvishaiW** [comment]
Hi, can you please share your enigma-catalyst version and your command/ run_algorithm() call with us? Thanks!

**Comment by avolution** [comment]
Same Problem 

Want to run multiple backtests on the same time and i get API_RATE_LIMIT Exceptions because of this.

--->

catalyst version 0.5.3

run_algorithm(
            exchange_name='bitfinex',
            capital_base=10000,
            data_frequency='minute',
            initialize=initialize,
            handle_data=handle_data,
            analyze=analyze,
            algo_namespace=NAMESPACE,
            base_currency='usd',
            start=config["start"],
            end=config["end"],
            output=out
        )

**Comment by AvishaiW** [comment]
I added a temporary fix for them yesterday on the develop branch, please update if it works for you or not.

**Comment by lacabra** [comment]
Release 0.5.6 includes the fix @AvishaiW mentions above.
