### ISSUE TITLE
Transaction fees on Poloniex

### ISSUE THREAD

**Issue by sam31415** [enigmampc/catalyst#272]
Hi,

Just after my algo orders a position on Poloniex, I get a "warning: detected lower balance for ... on poloniex". This seems to occur because Poloniex deduces the fees from the amount ordered, so the amount you effectively get is smaller than the amount ordered. Not really a big deal, but maybe something to correct in the production version.

Samuel

**Comment by AvishaiW** [comment]
Hi, 
We implemented a proper commission control on live, therefore, we hope that warnings won't be shown (unless needed to be shown), starting from the next release. However, the behaviour you described depends on the exchange you are trading on, some exchanges (such as Poloniex) will reduce the fees from the currency that was bought where others will reduce it from the quote currency, no matter what. I presume that most of the exchanges have further info on their docs.
