### ISSUE TITLE
Live bitfinex does not support candle frequency.. Invalid frequency alias 

### ISSUE THREAD

**Issue by WPsites** [enigmampc/catalyst#273]
catalyst, version 0.5.3

In live trading with the simple universe script I can get it to work _(after spending hours of trial and error to restrict the pairs it searches to 2 per minute because API restrictions make it impossible to run a universe bigger than 2 poss 3 symbols)_ on a **15T** candle size

Seems to be anything over that period fails. I've tried all variations as instructed by the various errors I get. 60T fails, 60M fails, 1H fails and so on

`InvalidHistoryFrequencyAlias: Invalid frequency alias 4H. Valid suffixes are M (minute) and D (day). For example, these aliases would be valid 1M, 5M, 1D`

`UnsupportedHistoryFrequencyError: bitfinex does not support candle frequency 60T, please choose from: ['1T', '5T', '15T', '30T', '1H', '3H', '6H', '12H', '1D', '1W', '2W', '1M']`

`InvalidHistoryFrequencyAlias: Invalid frequency alias 3H. Valid suffixes are M (minute) and D (day). For example, these aliases would be valid 1M, 5M, 1D`

**Comment by lenak25** [comment]
Hi @WPsites ,

I think its the same issue as reported at #227. It was fixed on the develop branch but was not yet released as we are still preparing and testing towards the next release. 
I am closing this, feel free to reopen if you feel it does not address what you have experienced. 

Thanks,
Lena
