### ISSUE TITLE
Bug in the data.history function 

### ISSUE THREAD

**Issue by avolution** [enigmampc/catalyst#274]
I updated catalyst to  version 0.5.4 from the previous version

There is a bug in the data.history function

data.history(
            context.instrument,
            fields='close',
            bar_count=10,
            frequency="1D")

This call produce now only one bar as the result in an Array instead of 10.

This occurs for frequency "Days" 
The frequency minute works correctly.

That code was working under the last version.

**Comment by lenak25** [comment]
Hi @avolution,

Thanks for reporting this.
Could you please specify in which mode you are running (live/backtest)?

Thanks,
Lena

**Comment by avolution** [comment]
I did Rolling back to version 0.5.3 and that behaviour disappeared

Here is the run_algorithm call

run_algorithm(
    exchange_name='bitfinex',
    capital_base=10000,
    data_frequency='minute',
    initialize=initialize,
    handle_data=handle_data,
    analyze=analyze,
    algo_namespace=NAMESPACE,
    base_currency='usd',
    start=config["start"],
    end=config["end"],
    output=out
)

**Comment by lenak25** [comment]
Thanks @avolution for the information.
We will fix this.

**Comment by SOGorman35** [comment]
I had the same issued and rolled back to 0.5.3.

**Comment by fredfortier** [comment]
We're planning to push a fix for this tomorrow.

**Comment by fredfortier** [comment]
@lenak25 and I looked into this but we've been a bit delayed in releasing the patch. We'll release on Monday morning PST.

**Comment by lenak25** [comment]
Fixed at version 0.5.5.
