### ISSUE TITLE
Universe fails on anything but Bitfinex, Bittrex, Poloniex

### ISSUE THREAD

**Issue by WPsites** [enigmampc/catalyst#281]
I've tracked down my issue to the fact that you don't seem to have symbols.json files uploaded to your aws space for the other exchanges. For ecample:

https://s3.amazonaws.com/enigmaco/catalyst-exchanges/binance/symbols.json

But the bitfinex file exists, as does polo and bittrex https://s3.amazonaws.com/enigmaco/catalyst-exchanges/bitfinex/symbols.json

There is no mention of only those exchanges working/supported on the example algo or anywhere really. Any plans to create the files for the other exchanges?

**Comment by salihkilic** [comment]
I'm not sure if this is related, but I keep getting errors myself in an algorithm that uses universe as a starting point.

```
[2018-03-20 13:22:41.741511] INFO: run_algo: Catalyst version 0.5.5
[2018-03-20 13:22:44.742488] INFO: run_algo: running algo in paper-trading mode
[2018-03-20 13:22:45.928641] INFO: exchange_bundle: pricing data for ['btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2018-03-19 00:00:00+00:00, updating the bundles.
Ingesting daily price data for btc_usd on bitfinex
[2018-03-20 13:22:47.598079] INFO: Loader: Cache at C:\Users\---[username hidden for privacy]---\.catalyst\data\treasury_curves.csv does not have data from 1990-01-02 00:00:00+00:00 to 2018-03-19 00:00:00+00:00.
[2018-03-20 13:22:47.598079] INFO: Loader: Downloading treasury data for 'btc_usd'.
[2018-03-20 13:22:50.936954] WARNING: Loader: Still don't have expected data after redownload!
```

**Comment by lenak25** [comment]
Hi @WPsites, 

Catalyst currently provides historical pricing for use in *backtesting* mode for Poloniex, Bitfinex and Bittrex. In *live* mode, Catalyst integrates with the CCXT library, and supports 90+ exchanges. Please visit http://catalyst.enigma.co/ for more information.

We are currently working on supporting historical data for use in backtesting from more exchanges as well.

Hopes this answers your question,
Lena

**Comment by salihkilic** [comment]
@lenak25 Does that mean that the simple universe example [here](https://github.com/enigmampc/catalyst/blob/master/catalyst/examples/simple_universe.py) does not work in a live setting?

**Comment by lenak25** [comment]
@salihkilic , the original question was regarding what exchanges are currently supported in backtesting and live.
Regarding running the simple universe example in live more, there should be no limitations of doing so.

**Comment by WPsites** [comment]
Hi @lenak25. it's live paper trading im doing. The universe example algo will only work in live mode when using the exchanges bitfinex, poloniex and bittrex, all other exchanges will fail, resulting in the issue @salihkilic is also experiencing. I'm guessing your not using bitfinex, poloniex and bittrex as your exchange for live trading @salihkilic

The problem is down to catalyst not hosting those symbol files as indicated in my initial post. Thanks for your comments.

**Comment by lenak25** [comment]
@WPsites , thanks for the clarification.
In our next release we will be adding support for more exchanges so I believe it will address this issue as well.
In any case, I will try to have a deeper look at what you are experiencing to see if something can be done before.

**Comment by lacabra** [comment]
@WPsites, @salihkilic 

There is a simpler way to accomplish the same thing in live mode, as per the code below:
`
def initialize():
     context.exchange = 'binance'
     context.base_currency = 'btc'

**Comment by lacabra** [comment]
@WPsites, @salihkilic

There is a simpler way to accomplish the same thing in live mode, as per the code below:
```
def initialize(context):
    context.exchange = 'binance'
    context.base_currency = 'btc'

def handle_data(context, data):
    # run the following every so often in live mode to get the universe of active coins 
    # in the given exchange quoted in base_currency
    context.coins = context.exchanges[context.exchange].assets
    context.coins = [c for c in context.coins
                             if c.quote_currency == context.base_currency]
```
in live mode you have to perform less operations because the exchange will already only return active coins, and from that we filter those we are interested in (quoted in base_currency in this case)

**Comment by WPsites** [comment]
Are you saying that version will work in live mode only?

**Comment by lacabra** [comment]
Correct, you could have a `LIVE` flag variable, so that:
```
if LIVE:
    # run the code above
else:
    # run the code from the example
```
after which, in either case, you have the valid universe of coins in `context.coins`.

**Comment by lenak25** [comment]
Closing this issue.
@WPsites feel free to reopen if you have more questions.
