### ISSUE TITLE
Downloading treasury data error

### ISSUE THREAD

**Issue by salihkilic** [enigmampc/catalyst#282]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10 
* Python Version: Python 3.6
* How did you install Catalyst: Pycharm (pip)
* Python packages:
aiodns==1.1.1
aiohttp==3.0.1
alembic==0.9.8
asn1crypto==0.24.0
async-timeout==2.0.1
attrdict==2.0.0
attrs==17.4.0
autobahn==17.10.1
Automat==0.6.0
backtrader==1.9.61.122
bcolz==0.12.1
boto3==1.6.11
botocore==1.9.11
Bottleneck==1.2.1
bt==0.2.5
cchardet==2.1.1
ccxt==1.11.137
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
click==6.7
colorama==0.3.9
colorlover==0.2.1
constantly==15.1.0
contextlib2==0.5.5
cryptography==2.1.4
cufflinks==0.12.1
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.28.1
cytoolz==0.9.0.1
dateparser==0.7.0
decorator==4.2.1
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.5
eth-abi==1.0.0
eth-account==0.1.0a2
eth-hash==0.1.1
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.0
eth-utils==1.0.1
ffn==0.3.3
future==0.16.0
gevent==1.2.2
greenlet==0.4.13
grequests==0.3.0
hexbytes==0.1.0
html5lib==1.0.1
hyperlink==18.0.0
idna==2.6
idna-ssl==1.0.1
incremental==17.5.0
intervaltree==2.1.0
ipython==6.2.1
ipython-genutils==0.2.0
jedi==0.11.1
jmespath==0.9.3
jsonschema==2.6.0
jupyter-core==4.4.0
Kivy==1.10.0
Kivy-examples==1.10.0
Kivy-Garden==0.1.4
kivy.deps.glew==0.1.9
kivy.deps.sdl2==0.1.17
kiwisolver==1.0.1
Logbook==1.3.0
lru-dict==1.1.6
lxml==4.2.0
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.2.0
multidict==4.1.0
multipledispatch==0.5.0
nbformat==4.4.0
networkx==2.1
numexpr==2.6.4
numpy==1.14.2
pandas==0.19.2
pandas-datareader==0.6.0
parso==0.1.1
patsy==0.5.0
pickleshare==0.7.4
Pillow==5.0.0
pipenv==11.8.3
plotly==2.4.1
progress==1.3
prompt-toolkit==1.0.15
PyAlgoTrade==0.18
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycares==2.3.0
pycparser==2.18
pycryptodome==3.5.1
pygame==1.9.3
Pygments==2.2.0
pyOpenSSL==17.5.0
pyparsing==2.2.0
pypiwin32==220
PyPrind==2.11.2
PyQt5==5.10
PyQtChart==5.10
pysha3==1.0.2
python-binance==0.6.6
python-dateutil==2.7.0
python-editor==1.0.3
pytz==2018.3
redo==1.6
regex==2018.2.21
requests==2.18.4
requests-cache==0.4.13
requests-file==1.4.3
requests-ftp==0.3.1
requests-threads==0.1.1
requests-toolbelt==0.8.0
rlp==0.6.0
ruamel.yaml==0.15.35
s3transfer==0.1.13
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.8.1
selenium==3.9.0
service-identity==17.0.0
simplegeneric==0.8.1
sip==4.19.7
six==1.11.0
sklearn==0.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.5
statsmodels==0.8.0
TA-Lib==0.4.16
tables==3.4.2
tabulate==0.8.2
toolz==0.9.0
tqdm==4.19.5
traitlets==4.3.2
Twisted==17.9.0
txaio==2.9.0
tzlocal==1.5.1
urllib3==1.22
virtualenv==15.1.0
virtualenv-clone==0.3.0
wcwidth==0.1.7
web3==4.0.0b11
webencodings==0.5.1
wrapt==1.10.11
yarl==1.1.0
zope.interface==4.4.3

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I wanted to test a backtested strategy in live mode (paper trading)

* What happened instead?
I keep getting the following error:
```
[2018-03-20 14:21:42.463287] INFO: run_algo: running algo in paper-trading mode
[2018-03-20 14:21:42.744043] INFO: exchange_bundle: pricing data for ['btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2018-03-19 00:00:00+00:00, updating the bundles.
Ingesting daily price data for btc_usd on bitfinex
[2018-03-20 14:21:45.332001] INFO: Loader: Cache at C:\Users\[username_removed]\.catalyst\data\treasury_curves.csv does not have data from 1990-01-02 00:00:00+00:00 to 2018-03-19 00:00:00+00:00.
[2018-03-20 14:21:45.332001] INFO: Loader: Downloading treasury data for 'btc_usd'.
[2018-03-20 14:21:48.763205] WARNING: Loader: Still don't have expected data after redownload!
```
Also the list of coins (from the universe function) doesn't contain anything. I also tried forcing it by making it reload every tick.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Use the "Simple Universe Example" from documentation
2. Ingest appropriate bundle, insert key and secret in json file
3. Run algorithm with the following variables:
```
performance = run_algorithm(capital_base=1000.0,  # amount of base_currency
                                initialize=initialize,
                                handle_data=handle_data,
                                analyze=analyze,
                                exchange_name='bitfinex',
                                data_frequency='minute',
                                base_currency='usd',
                                live=True,
                                live_graph=False,
                                algo_namespace='TEST1')
```
...

## What steps have you taken to resolve this already?
I cleared the .catalyst folder, tried ingesting again. Used new API key.

...

# Anything else?
Nope, my algo works in backtesting, but not live.
...

Sincerely,
Salih

**Comment by salihkilic** [comment]
Did some further searching around, the .csv file now actually does have the data (although I don't know how that happened this time after many retries), but now the algo says:
`WARNING: Loader: Refusing to download new treasury data because a download succeeded at 2018-03-20 14:21:48.762203+00:00.`

It still gives no list of available coins in `context.coins` in the example algorithm from "Simple Universe". I double checked if the conditions are even getting hit for the creation of the list by the following:

```
    if not context.i % one_day_in_minutes or not context.universe:
        print("Print check")
        context.universe = universe(context, lookback_date, date)
```

It does get printed out, but the list is still empty for some reason.

**Comment by salihkilic** [comment]
I think I found out what's causing the error in the example. The retrieved data ends at yesterday, while 
the example algorithm looks for coins that existed in the given timeframe. 
```
                        end_daily                 end_minute  
aidusd  2018-03-19 00:00:00+00:00  2018-03-19 00:00:00+00:00   
avtusd  2018-03-19 00:00:00+00:00  2018-03-19 00:00:00+00:00   
batusd  2018-03-19 00:00:00+00:00  2018-03-19 00:00:00+00:00   
bchusd  2018-03-19 00:00:00+00:00  2018-03-19 00:00:00+00:00   
btcusd  2018-03-19 00:00:00+00:00  2018-03-19 00:00:00+00:00   
btgusd  2018-03-19 00:00:00+00:00  2018-03-19 00:00:00+00:00   
datusd  2018-03-19 00:00:00+00:00  2018-03-19 00:00:00+00:00   
dshusd  2018-03-19 00:00:00+00:00  2018-03-19 00:00:00+00:00   
```
In a backtest, it's a timespan in the past so a coin that exists now will return True and get included in the resulting dataframe because of this line:

```
    # Filter all pairs to ensure that pair existed in the current date range
    df = df[df.start_date < lookback_date]
    df = df[df.end_daily >= current_date]
```

I'm still not sure as to why Catalyst would only download the data until yesterday midnight.

**Comment by salihkilic** [comment]
For anyone reading this later on, the example from the docs can be resolved for live trading by doing the following (which might not be safe) in the universe function:

```
d = str(datetime.today().date() - timedelta(days=1))

[...]

    # Filter all pairs to ensure that pair existed in the current date range
    df = df[df.start_date < lookback_date]
    df = df[df.end_daily >= d]
```

**Comment by AvishaiW** [comment]
this issue seems to be related to #285 & #271, I added a temporary fix for them yesterday on the develop branch, please update if it works for you or not.

**Comment by lacabra** [comment]
Release 0.5.6 includes the fix @AvishaiW mentions above.
