### ISSUE TITLE
Please remove sleep(3) from run_algo.py:156 - serves no purpose but to slow down my backtest by 3 seconds

### ISSUE THREAD

**Issue by gatapia** [enigmampc/catalyst#283]
Which when used in a grid search can result in considerable time.

**Comment by lacabra** [comment]
This serves its purpose.
If you are an advanced enough user to figure this out, why not override the code in your local copy?

We'll remove this once we are no longer in an alpha release

**Comment by gatapia** [comment]
already overridden
