### ISSUE TITLE
How can I get current portfolio value and percent of aserts in handle_data function?

### ISSUE THREAD

**Issue by Longcnttbkhn** [enigmampc/catalyst#289]
Dear Catalyst Maintainers,

I'm using your product and It's very great. I have a question and I really happy if you help me answer. 
I want to get current portfolio value and percent of aserts in handle_data function so how can I do that?

Thank you for your help and have nice day my friend!

**Comment by AvishaiW** [comment]
Hi @Longcnttbkhn, if I've understood correctly, I presume that `context.portfolio` is what you are looking for. it has a list of your positions. Hope it helps and we are glad you are enjoying the product!

**Comment by Longcnttbkhn** [comment]
Thank you so much for your help. this is exactly what I need.

**Comment by Longcnttbkhn** [comment]
I have one more question. If I use live trading mode (not paper trading), the `portfolio_value` and `amount` of aserts return by `context.portfolio` is updated realtime from my account in exchange ( Ex: Bitfinex) right?

**Comment by AvishaiW** [comment]
correct! every minute the portfolio is updated..

**Comment by Longcnttbkhn** [comment]
Thank you so much, that is very wonderful!

**Comment by salihkilic** [comment]
Is there a way to update the cash reserves with the pushed buys/sells within the same tick? For example, when I do a order_target_percent it doesn't update the cash reserves for the next coin if I have multiple coins/assets potentially being traded within the tick. There is this limbo within the tick where I haven't confirmed I have filled the order, but the cash isn't reserved either which can result in negative cash holdings when backtrading for example.

**Comment by AvishaiW** [comment]
@salihkilic sorry on the late response. Thanks for informing us regarding this issue, it will be much easier to track it if it will be on a card of it's own, and we will be able to add it to our log.

**Comment by lenak25** [comment]
Closing this as the original question was answered. 

@salihkilic if you are still experiencing an issue, as @AvishaiW mentioned, please open a tew ticket.

Thanks,
Lena
