### ISSUE TITLE
How can I reduce number of request to exchange when run in live trading mode?

### ISSUE THREAD

**Issue by Longcnttbkhn** [enigmampc/catalyst#291]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: `Linux 3.13.0-108-generic #155-Ubuntu SMP Wed Jan 11 16:58:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 3.4.3`
* Python Bitness: `64`
* How did you install Catalyst: `pip`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I'm running my algorithm in live trading mode but after a time it gets error like picture below:

![screenshot from 2018-03-31 09-28-27](https://user-images.githubusercontent.com/16404157/38169136-22901636-358c-11e8-97bf-89aebfc2e0b2.png)

I think maybe the reason is having too many request to exchange, so what can I do to reduce number of request to exchange? or If you have any way to help me to fix the issue, can you tell me?

Thank you so much for your help!

**Comment by lenak25** [comment]
Hi @Longcnttbkhn , 

It is indeed an issue of sending too many requests to the exchange and in the case of Bitfinex, the limit is quite low (from their docs:"Our rate limit policy can vary in a range of 10 to 90 requests per minute depending on some factors"). We are aware of this limitation and plan to add some improvements to our code to optimize the requests number to better handle this.
In the meantime you can try to reduce the number of requests in your code or use a different exchange.

Thanks,
Lena

**Comment by Longcnttbkhn** [comment]
Hi @lenak25 ,

Thank you so much for you help. I used `data_frequency='minute'` and I had 6 coin to trade so I think my code just called 6 request per minute. Furthermore, my algorithm had been running for 10 hours before got error. I want to change `data_frequency='minute'` to 30 minutes, is that possible?

Thank you so much for spend time helping me!
Long

**Comment by lenak25** [comment]
Hi @Longcnttbkhn ,

It depends on what you are doing in your `handle_data()` function: any call to history candles/current price is also translated to a request sent to the exchange.
Regarding your second question, the frequency in which your algorithm is run is every minute - if you need, you can add a specific logic to your code which enforces that a certain section will be run in a lower frequency. For example, you can set a counter and skip all those minutes that you don't need to take action:
```
def initialize(context):
     context.i = 0
def handle_data(context, data):
     context.i = context.i +1
     if context.i % 30:
            return       # does nothing 29 out of 30 times
      # your code here that will be executed every 30 min
```

Lena

**Comment by Longcnttbkhn** [comment]
Thank you so much @lenak25 , I understand well.

**Comment by lenak25** [comment]
Happy to hear, I am closing this, feel free to reopen if something is unclear.
