### ISSUE TITLE
any example use pipline with catalyst

### ISSUE THREAD

**Issue by cbogithub** [enigmampc/catalyst#292]
Dear Catalyst Maintainers,

i saw catalyst suported pipline but can't saw any example use pipline, 
Pls, give me a simple example, thanks

**Comment by lacabra** [comment]
Hi @cbogithub, Catalyst does not support Zipline's pipelines yet, so there are no examples we can provide. 

Can you point where you saw that Catalyst supports pipeline so that we can correct it?

Thanks

**Comment by lacabra** [comment]
Oh, ok. That makes sense: that's legacy code from the Zipline code, which we haven't touched since (other than renaming zipline->catalyst), but no actual code supports this.
