### ISSUE TITLE
Trouble live trading on GDAX: create_order() got an unexpected keyword argument 'symbol'

### ISSUE THREAD

**Issue by romanparker** [enigmampc/catalyst#293]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 10 Pro)
* Python Version: 3.6.5
* How did you install Catalyst: conda
* Python packages:
# Name                    Version                   Build  Channel
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.9.7                     <pip>
async-timeout             2.0.0                     <pip>
attrdict                  2.0.0                     <pip>
attrs                     17.4.0                    <pip>
backports                 1.0              py36h81696a8_1
backports.functools_lru_cache 1.5                      py36_0    conda-forge
bcolz                     0.12.1                    <pip>
bleach                    2.1.3                     <pip>
boto3                     1.5.27                    <pip>
botocore                  1.8.41                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h94faf87_0
cchardet                  2.1.1                     <pip>
ccxt                      1.10.1102                 <pip>
certifi                   2018.1.18                py36_0
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
colorama                  0.3.9                     <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0           py36h009560c_0
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
cytoolz                   0.9.0                     <pip>
decorator                 4.2.1                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.8                     <pip>
entrypoints               0.2.3                     <pip>
eth-abi                   1.0.0b0                   <pip>
eth-account               0.1.0a2                   <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b1                   <pip>
eth-rlp                   0.1.0a2                   <pip>
eth-utils                 1.0.0b1                   <pip>
freetype                  2.8                  h51f8f2c_1
hexbytes                  0.1.0b0                   <pip>
html5lib                  1.0.1                     <pip>
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.6                       <pip>
idna-ssl                  1.0.0                     <pip>
intel-openmp              2018.0.0                      8
intervaltree              2.1.0                     <pip>
ipykernel                 4.8.2                     <pip>
ipython                   6.2.1                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.2.0                     <pip>
jedi                      0.11.1                    <pip>
Jinja2                    2.10                      <pip>
jmespath                  0.9.3                     <pip>
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.3                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
kiwisolver                1.0.1            py36h12c3424_0
libpng                    1.6.34               h79bbb47_0
Logbook                   1.2.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.1.1                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.2.2                     <pip>
mistune                   0.8.3                     <pip>
mkl                       2018.0.2                      1
mkl_fft                   1.0.1            py36h452e1ab_0
mkl_random                1.0.1            py36h9258bd6_0
multidict                 4.1.0                     <pip>
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
networkx                  2.1                       <pip>
notebook                  5.4.1                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.14.2           py36h5c71026_1
openssl                   1.0.2o               h8ea7d77_0
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
pandocfilters             1.4.2                     <pip>
parso                     0.1.1                     <pip>
patsy                     0.5.0                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py36_5
prompt-toolkit            1.0.15                    <pip>
pycares                   2.3.0                     <pip>
pycryptodome              3.4.11                    <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0            py36h785a196_1
pyqt                      5.6.0            py36hb5ed885_5
pysha3                    1.0.2                     <pip>
python                    3.6.5                h0c2934d_0
python-dateutil           2.6.1                     <pip>
python-dateutil           2.7.2                    py36_0
python-editor             1.0.3                     <pip>
pytz                      2018.3                   py36_0
pywinpty                  0.5.1                     <pip>
pyzmq                     17.0.0                    <pip>
qt                        5.6.2           vc14h6f8c307_12
qtconsole                 4.3.1                     <pip>
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     1.0.1            py36hce232c7_0
Send2Trash                1.5.0                     <pip>
setuptools                39.0.1                   py36_0
simplegeneric             0.8.1                     <pip>
sip                       4.18.1           py36h9c25514_2
six                       1.11.0           py36h4db2310_1
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.2                     <pip>
sqlite                    3.22.0               h9d3ae62_0
statsmodels               0.8.0                     <pip>
TA-Lib                    0.4.17                    <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1                     <pip>
tk                        8.6.7                hcb92d03_3
toolz                     0.9.0                     <pip>
tornado                   5.0.1                    py36_1
traitlets                 4.3.2                     <pip>
urllib3                   1.22                      <pip>
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wcwidth                   0.1.7                     <pip>
web3                      4.0.0b9                   <pip>
webencodings              0.5.1                     <pip>
wheel                     0.30.0           py36h6c3ec14_1
widgetsnbextension        3.2.0                     <pip>
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.11                   <pip>
xz                        5.2.3                h7c615d8_2
yarl                      1.1.0                     <pip>
zlib                      1.2.11               h8395fce_2

Now that you know a little about me, let me tell you about the issue I am
having:

Hi, my goal is to live trade on GDAX.  Everything seems to work well until the system tries to create an order.  I am using the following test algo:

```
from catalyst import run_algorithm
from catalyst.api import order, order_target_percent, record, symbol 
import pandas as pd

def initialize(context):
    context.asset = symbol('btc_usd')

def handle_data(context, data):
    order(context.asset, .001)
    record(btc=data.current(context.asset, 'price'))

run_algorithm(
    initialize=initialize,
    capital_base=300,
    handle_data=handle_data,
    exchange_name='gdax',
    live=True,
    algo_namespace='live_testing',
    base_currency='usd',
    simulate_orders=False
)
```

* What did you expect to happen?
Using this algo, I expected to purchase .001 btc in my gdax account (and then I would stop the algo)

* What happened instead?
I get the error at the bottom about create_order() having trouble with the 'symbol' argument:

> (catalyst) C:\catalyst\alogs>catalyst live -f live_testing.py -x gdax --base-currency usd -n live_testing --capital-base 300
> Running in paper trading mode.
> [2018-04-08 22:16:52.835988] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
> [2018-04-08 22:16:52.835988] INFO: run_algo: Catalyst version 0.5.8
> [2018-04-08 22:16:55.837188] INFO: run_algo: running algo in paper-trading mode
> [2018-04-08 22:16:56.160975] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
> [2018-04-08 22:16:56.160975] INFO: run_algo: Catalyst version 0.5.8
> [2018-04-08 22:16:59.161860] INFO: run_algo: running algo in live-trading mode
> [2018-04-08 22:17:04.946564] INFO: exchange_algorithm: portfolio balances, cash: 341.3832, positions: 0.0
> Traceback (most recent call last):
>   File "c:\catalyst\miniconda\envs\catalyst\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\catalyst\miniconda\envs\catalyst\Scripts\catalyst.exe\__main__.py", line 9, in <module>
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\click\core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\click\core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\click\core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\click\core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\click\core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 104, in _
>     return f(*args, **kwargs)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\click\decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\__main__.py", line 497, in live
>     stats_output=None,
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 338, in _run
>     'script': algotext,
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 423, in __init__
>     super(ExchangeTradingAlgorithmLive, self).__init__(*args, **kwargs)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 68, in __init__
>     super(ExchangeTradingAlgorithmBase, self).__init__(*args, **kwargs)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\algorithm.py", line 376, in __init__
>     exec_(code, self.namespace)
>   File "live_testing.py", line 23, in <module>
>     simulate_orders=False
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 560, in run_algorithm
>     stats_output=stats_output
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 342, in _run
>     overwrite_sim_params=False,
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 330, in run
>     data, overwrite_sim_params
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\algorithm.py", line 724, in run
>     for perf in self.get_generator():
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\gens\tradesimulation.py", line 224, in transform
>     for capital_change_packet in every_bar(dt):
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\gens\tradesimulation.py", line 137, in every_bar
>     handle_data(algo, current_data, dt_to_use)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\utils\events.py", line 216, in handle_data
>     dt,
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\utils\events.py", line 235, in handle_data
>     self.callback(context, data)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 865, in handle_data
>     self._handle_data(self, data)
>   File "live_testing.py", line 12, in handle_data
>     order(context.asset, .001)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\utils\api_support.py", line 57, in wrapped
>     return getattr(algo_instance, f.__name__)(*args, **kwargs)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\utils\api_support.py", line 126, in wrapped_method
>     return method(self, *args, **kwargs)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\algorithm.py", line 1462, in order
>     return self.blotter.order(asset, amount, style)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_blotter.py", line 169, in order
>     if amount == 0:
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_blotter.py", line 185, in order
>     args=(asset, amount, style),
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\redo\__init__.py", line 162, in retry
>     return action(*args, **kwargs)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange_blotter.py", line 163, in exchange_order
>     asset, amount, style
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange.py", line 841, in order
>     return self.create_order(asset, amount, is_buy, style)
>   File "c:\catalyst\miniconda\envs\catalyst\lib\site-packages\catalyst\exchange\ccxt\ccxt_exchange.py", line 785, in create_order
>     price=price
> **TypeError: create_order() got an unexpected keyword argument 'symbol'**

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Use algo above
2. Run algo with this command: catalyst live -f live_testing.py -x gdax --base-currency usd -n live_testing --capital-base 300

## What steps have you taken to resolve this already?
I have tried using different symbol naming structures such as "BTC/USD", "btcusd", etc. 

Thank you!!  I am new to Catalyst - just learning.
Sincerely,
Roman Parker

**Comment by AvishaiW** [comment]
Hi, Thanks for noting this out. for some reason the name of the `symbol` argument in `create_order` on CCXT (the api library, catalyst is using) was named `market`, specifically for GDAX. I opened an [issue on ccxt](https://github.com/ccxt/ccxt/issues/2515) and it was fixed. we will add this to our next release.

**Comment by romanparker** [comment]
Excellent, thanks!

**Comment by AvishaiW** [comment]
btw, if you upgrade ccxt to the latest version (`pip install ccxt --upgrade`), you will be able to run it properly.

**Comment by romanparker** [comment]
Avishai, I did the update and it connected and executed the trades perfectly.  Thanks!
