### ISSUE TITLE
Error: NoDataAvailableOnExchange when running example code

### ISSUE THREAD

**Issue by hnipps** [enigmampc/catalyst#300]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: macOS High Sierra 10.13.4
* Python Version: Python 3.6.4 :: Anaconda, Inc
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages:
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.9.7                     <pip>
astroid                   1.6.3                    py36_0  
async-timeout             2.0.0                     <pip>
attrdict                  2.0.0                     <pip>
attrs                     17.4.0                    <pip>
backports                 1.0              py36ha3c1827_1  
backports.functools_lru_cache 1.5                      py36_0    conda-forge
bcolz                     0.12.1                    <pip>
boto3                     1.5.27                    <pip>
botocore                  1.8.41                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0  
cchardet                  2.1.1                     <pip>
ccxt                      1.10.1102                 <pip>
certifi                   2018.1.18                py36_0  
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0           py36hfc81398_0  
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
cytoolz                   0.9.0                     <pip>
decorator                 4.2.1                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.8                     <pip>
eth-abi                   1.0.0b0                   <pip>
eth-account               0.1.0a2                   <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b1                   <pip>
eth-rlp                   0.1.0a2                   <pip>
eth-utils                 1.0.0b1                   <pip>
freetype                  2.8                  h12048fb_1  
hexbytes                  0.1.0b0                   <pip>
idna                      2.6                       <pip>
idna-ssl                  1.0.0                     <pip>
intel-openmp              2018.0.0                      8  
intervaltree              2.1.0                     <pip>
isort                     4.3.4                    py36_0  
jmespath                  0.9.3                     <pip>
kiwisolver                1.0.1            py36h792292d_0  
lazy-object-proxy         1.3.1            py36h2fbbe47_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libpng                    1.6.34               he12f830_0  
Logbook                   1.2.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.1.1                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.2.2            py36ha7267d0_0  
mccabe                    0.6.1            py36hdaeb55d_0  
mkl                       2018.0.1             hfbd8650_4  
multidict                 4.1.0                     <pip>
multipledispatch          0.4.9                     <pip>
ncurses                   6.0                  hd04f020_2  
networkx                  2.1                       <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.14.0           py36ha726252_2  
openssl                   1.0.2n               hdbc3d79_0  
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
patsy                     0.5.0                     <pip>
pip                       9.0.1                    py36_5  
pycares                   2.3.0                     <pip>
pycryptodome              3.4.11                    <pip>
pylint                    1.8.4                    py36_0  
pyparsing                 2.2.0            py36hb281f35_0  
pysha3                    1.0.2                     <pip>
python                    3.6.4                hc167b69_3  
python-dateutil           2.6.1                     <pip>
python-dateutil           2.7.2                    py36_0  
python-editor             1.0.3                     <pip>
pytz                      2018.3                   py36_0  
readline                  7.0                  hc1231fa_4  
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     1.0.0            py36h1de22e9_0  
setuptools                38.4.0                   py36_0  
six                       1.11.0           py36h0e22d5e_1  
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.2                     <pip>
sqlite                    3.22.0               h3efe00b_0  
statsmodels               0.8.0                     <pip>
TA-Lib                    0.4.17                    <pip>
tables                    3.4.2                     <pip>
tk                        8.6.7                h35a86e2_3  
toolz                     0.9.0                     <pip>
tornado                   5.0.1                    py36_1  
urllib3                   1.22                      <pip>
web3                      4.0.0b9                   <pip>
wheel                     0.30.0           py36h5eb2c71_1  
wrapt                     1.10.11          py36hc29e774_0  
wrapt                     1.10.11                   <pip>
xz                        5.2.3                h0278029_2  
yarl                      1.1.0                     <pip>
zlib                      1.2.11               hf3cbc9b_2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I ran the buy_and_hodl.py example. I expected it to run correctly, and produce charts etc. It worked yesterday.
* What happened instead?
I received this error message:
```
catalyst.exchange.exchange_errors.NoDataAvailableOnExchange: Requested data for trading pair BTC/USD is not available on exchange bitfinex in `daily` frequency at this time. Check `http://enigma.co/catalyst/status` for market coverage.
```
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.  $ catalyst run -f buy_and_hodl.py -s 2015-3-1 -e 2017-11-30 --capital-base 100000 -x bitfinex -c btc -o bah.pickle

## What steps have you taken to resolve this already?
Tried to clean the exchange data with $ catalyst clean-exchange -x bitfinex and then ingest the daily data again. It didn't help.
...

# Anything else?

...

Sincerely,
Harry

**Comment by AvishaiW** [comment]
Hi, seems like a replicate of #301. i'm closing this issue, feel free to open if necessary..
