### ISSUE TITLE
Bitfinex Trading Pairs Disappeared

### ISSUE THREAD

**Issue by Dan733** [enigmampc/catalyst#301]
All of Bitfinex's currency pairs are down https://enigma.co/catalyst/status/
This is a pretty critical bug.

**Comment by lacabra** [comment]
The file has been restored. Data is only up to date until 5 days ago, and we continue to investigate, but at least backtesting works again.

**Comment by jake-smithandcrown** [comment]
Great - thanks so much for the update. 

Best,
Jake

**Comment by catalyst-support** [comment]
➤ Victor Grau Serrat commented:

No changes since last report, but the server processes that generate these datasets function properly. Error handling on the server has been improved to prevent or catch similar issues in the future.
