### ISSUE TITLE
Transactions and positions by period in paper/live trading

### ISSUE THREAD

**Issue by sam31415** [enigmampc/catalyst#302]
Hi,

When you run an algorithm in backtest mode, the run function returns a "results" dataframe that contains all the info about the backtest. In particular, it contains all the transactions and the positions for each time period. 

It would be nice if the same information was available when paper or live trading. As far as I can tell, this is not the case. Something closely resembling to the dataframe appears in the "stats" folder, with one csv file per day. However, the latter contains less information. For instance each time period contains an integer with the number of transactions, instead of a dictionary with all the transactions. Maybe dataframes containing dictionaries don't really convert well to csv. Perhaps it would be better to dump at each time period the data of the results dataframe into a pickle file incrementally, so that it can be easily retrieved and analysed?

I have also seen that some information seems to be contained in the pickled performance object, but it is unclear how to retrieve this data, as all the useful tools in the catalyst API can be used only inside an algorithm.

Any help would be appreciated,

Samuel

**Comment by sam31415** [comment]
That's great, thanks. Just to be sure, what do you mean by "with a defined end_date"? What's the meaning of end_date in paper/live trading?

**Comment by AvishaiW** [comment]
when running on live/ paper you can add the `end` argument defining a future end date when you want the algo to stop running. See more on the [docs](https://enigma.co/catalyst/live-trading.html#trading-an-algorithm)

**Comment by sam31415** [comment]
Ah ok... So you can't access this information while the algorithm is running.

Here is what I had in mind, which could potentially be more useful. Every minute, the corresponding line of the results dataframe gets appended to a pickle file (one can make the pickle file change every day or every week to avoid big files, just like what is currently done in the daily_performance and stats folders). Then at any time one can recover the pickle files, unpickle them sequentially and get the equivalent of the results dataframe from the start of the algorithm until the present time.

**Comment by AvishaiW** [comment]
actually it is possible, 
the stats we return (in paper/live/minute freq) are located in `context.frame_stats` dictionary, which at the end of each day is pickled into a frame_stats folder. for now, a file is erased after 30 days and we also remove the folder at the beginning of every run to avoid overloading of the disk. so you can either extract the data from the pickle files or from within the algo at the moment. Of course, we are working on better solutions, similar to your suggestions, however, it will take time to implement them, due to many other urgent issues.

**Comment by sam31415** [comment]
Ok, thanks. I haven't seen a frame_stats folder in my live_algo folder. I only have a daily_performance and a stats folder. The stats folder contains csv files, so assume this is not the one you mean. I upgraded to Catalyst 0.5.8 from 0.5.6 and will see if frame_stats appears at the end of the day.

**Comment by sam31415** [comment]
I see the frame_stats folder now, and the pickle files seem to have all the data I need. Great!

**Comment by AvishaiW** [comment]
added to 0.5.9
