### ISSUE TITLE
No commission values after extract_transactions(perf)

### ISSUE THREAD

**Issue by kooomix** [enigmampc/catalyst#306]
Hi,

I've set commissions and slippage in "def initialize(context)" as follows:
**context.set_commission(maker=0.0015, taker=0.0025)
context.set_slippage(spread=0.005)** 

and in the "def analyze(context, perf)" function i've used the command **extract_transactions(perf)**.

I get the columns: [dt, amount, commission, order_id, price, sid] but the commission value is always empty...

I'm using catalyst version 0.5.8.

Any known issue regarding this matter?
Thanks.

**Comment by kooomix** [comment]
Actually, I now see that the "perf" parameter doesn't include the commission info.
So the question is - how can I get the commission information into the perf and then extract transactions from it?

**Comment by AvishaiW** [comment]
this seems to be a replicate of #304, once I find the error, ill be informing there..
