### ISSUE TITLE
New balance in str_btc not taken into account by an algorithm live trading on Poloniex

### ISSUE THREAD

**Issue by sam31415** [enigmampc/catalyst#307]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux trading-bot 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: 3.6.4
* Python Bitness: Nothing happening when executing `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: conda
* Python packages: # packages in environment at /home/samuel_monnier/miniconda3:                                                                                                           
Name                    Version                   Build  Channel                                               
asn1crypto                0.24.0                   py36_0                                                        
ca-certificates           2017.08.26           h1d4fec5_0                                                        
certifi                   2018.1.18                py36_0                                                        
cffi                      1.11.4           py36h9745a5d_0                                                        
chardet                   3.0.4            py36h0f667ec_1                                                        
conda                     4.5.0                    py36_0                                                        
conda-env                 2.6.0                h36134e3_1                                                        
cryptography              2.1.4            py36hd09be54_0                                                        
idna                      2.6              py36h82fb2a8_1                                                        
libedit                   3.1                  heed3624_0                                                        
libffi                    3.2.1                hd88cf55_4                                                        
libgcc-ng                 7.2.0                h7cc24e2_2                                                        
libstdcxx-ng              7.2.0                h7a57d05_2                                                        
ncurses                   6.0                  h9df7e31_2                                                        
openssl                   1.0.2n               hb7f436b_0                                                        
pip                       9.0.1            py36h6c6f9ce_4                                                        
pip                       9.0.3                     <pip>                                                        
pycosat                   0.6.3            py36h0a5515d_0                                                        
pycparser                 2.18             py36hf9f622e_1                                                        
pyopenssl                 17.5.0           py36h20ba746_0                                                        
pysocks                   1.6.7            py36hd97a5b1_1                                                        
python                    3.6.4                hc3d631a_1                                                        
readline                  7.0                  ha6073c6_4
requests                  2.18.4           py36he2e5f8d_1
ruamel_yaml               0.15.35          py36h14c3975_1
setuptools                38.4.0                   py36_0
six                       1.11.0           py36h372c433_1
sqlite                    3.22.0               h1bed415_0
tk                        8.6.7                hc745277_3
urllib3                   1.22             py36hbe7ace6_0
wheel                     0.30.0           py36hfd4bba0_1
xz                        5.2.3                h55aa19d_2
yaml                      0.1.7                had09818_2
zlib                      1.2.11               ha838bed_2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

During live trading on Poloniex, on several occasions a str_btc buy order has been placed using order_target, with no previous position in str. The order is placed correctly and filled on the exchange. 
However, the algorithm does not detect the new position and I get the following warning:
```
[2018-04-18 11:21:00.133166] INFO: exchange_blotter: filled order 73349994671 / str_btc: 67.30263909, avg price: 3.97e-05
[2018-04-18 11:21:02.123716] WARNING: Exchange: detected lower balance for str_btc on poloniex: 0.0 < 67.30263909, updating position amount
[2018-04-18 11:21:02.124473] INFO: exchange_algorithm: portfolio balances, cash: 0.02120141, positions: 0.010694250461529699
```
This results in the str position being ignored by the algorithm, and the position opened is counted as a complete loss.

I should note that several other positions in different pairs have been opened without problem around the same time, but that this problem with str_btc happened three times within two hours. 

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Have a live trading algorithm open an order for str_btc on Poloniex using order_target, with no previous position in str.
2. Observe the result.

## What steps have you taken to resolve this already?

For now, I forbid my algorithm to buy str, but this is hardly a solution.

Sincerely,

Samuel

**Comment by AvishaiW** [comment]
added to 0.5.9
