### ISSUE TITLE
Calculating excess returns in portfolio_optimization.py

### ISSUE THREAD

**Issue by zkid18** [enigmampc/catalyst#314]
Dear Catalyst Maintainers,

I'm a bit confused about the way you are calculating excess returns in 

>  portfolio_optimization.py

        # Compute daily returns (r)
        r = np.asmatrix(t_val / tminus_val - 1)
        # Compute the expected returns of each asset with the average
        # daily return for the selected time window
        m = np.asmatrix(np.mean(r, axis=0))
        # ###
        stds = np.std(r, axis=0)
        # Compute excess returns matrix (xr)
        xr = r - m

As far as I know excess returns requires the subtracting of the riskless rate, or benchmark rate, from the actual rate achieved. But according to your formula you just subtract mean of your returns from return rate. Why do you concern mean of the returns as a riskless rate?

By now I can't really understand the physical meaning of this variable, as it's not even standartization.

Thank you!

**Comment by zkid18** [comment]
Why not to use `np.cov` to calculate covariance?

**Comment by lacabra** [comment]
Added proper authorship attribution to the example file 0dcd0fe3155fb5c400dca904b7793d7b46142a6a.

@zkid18 For algorithm-specific questions, please contact the author directly. You can find him on LinkedIn, Medium,...

**Comment by zkid18** [comment]
Sure, thank you for reply!
