### ISSUE TITLE
Aborted! was the message I received when running backtest bot

### ISSUE THREAD

**Issue by Criptical** [enigmampc/catalyst#316]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 10l)
* Python Version: `$ python --version` current
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'` IDKnow
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`) both
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue: I tried to run my algorithm file using anaconda prompt cli, and received Aborted!
Its installed correctly and I have been able to use ide ATOM by launching the environment through the anaconda prompt. 

* What did you expect to happen? 
For it to at least start running, after dropping -o arbitragetest.pickle

* What happened instead?
catalyst run -f arbitragebot.py -x bitfinex --start 2017-12-12 --end 2017-12-13 -c usd --capital-base 100000
Running in backtesting mode.
[2018-04-28 00:20:04.865654] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-04-28 00:20:04.865654] INFO: run_algo: Catalyst version 0.5.9
[2018-04-28 00:20:07.879174] INFO: run_algo: running algo in backtest mode

Aborted!

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. IDK, run: catalyst run -f arbitragebot.py -x bitfinex --start 2017-12-12 --end 2017-12-13 -c usd --capital-base 100000
2. sorry, this is my first time doing something like this. 
3.
...

## What steps have you taken to resolve this already? I've searched google, but found nothing. I'm thinking about ensuring my command matches everything that is in the file. i.e. exchange, capital base, start, end, etc... 

...

# Anything else? Thanks for making this for newbs such as myself. I really have enjoyed the strenuous, but not to complicated process of learning python to build an algotrader. Came across catalyst when learning ccxt. And, I'm going through the setting up/testing/learning phase before unleashing my economics background. 

...

Sincerely,
`$ Criptical`

**Comment by Criptical** [comment]
Update: I have tried matching the arbitragebot.py with command line command. Received same Aborted! message.

**Comment by lenak25** [comment]
Hi @Criptical ,

Were you able to run the examples properly?

**Comment by Criptical** [comment]
@lenak25 How do I do that? Or, what would you be looking for in the example? 

The reason I ask is that everything I put in in the description above was the exact command/response from the anaconda prompt. 

Specifically this: 

catalyst run -f arbitragebot.py -x bitfinex --start 2017-12-12 --end 2017-12-13 -c usd --capital-base 100000
Running in backtesting mode.
[2018-04-28 00:20:04.865654] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-04-28 00:20:04.865654] INFO: run_algo: Catalyst version 0.5.9
[2018-04-28 00:20:07.879174] INFO: run_algo: running algo in backtest mode

Aborted!

=-=-=-=-=-

After the 'Aborted!' message it returned to the <python>_ command line to await another command.

**Comment by Criptical** [comment]
Fixed it! 

I must of did the recording part of the code wrong. The whole perf() and record with .pickle files. I put a # in from of those lines, ran the command again, and off it went.

**Comment by lenak25** [comment]
Happy to hear.
I suggest you to read the [docs](https://enigma.co/catalyst/) to understand better how to use the recording functionality. 
In any case, let us know if you have more questions.
