### ISSUE TITLE
Implement usage of start date in live mode.

### ISSUE THREAD

**Issue by rauff** [enigmampc/catalyst#318]
I was not able to find anything about the time frame of implementing, start_date while running catalyst in live mode. I think this is a quite important feature, as the trading program will not be that vulnerable to OS restart or changing the running algorithm when this is implemented. 
This is especially critical when your algorithm use a couple of days to predict the coming prices. 

If this is not being looked at right now, could you point me into the couple of files where the major changes are going to happend, then I can take a look at it.

Best Regards
Jens Henrik

**Comment by AvishaiW** [comment]
Hi, sorry on the delay.. I added an implementation of this to the develop branch, will be added to the next release.

**Comment by lenak25** [comment]
Fixed at release 0.5.10.
