### ISSUE TITLE
Commission missing in transaction dataframe in backtesting

### ISSUE THREAD

**Issue by xbionicx** [enigmampc/catalyst#325]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 3.6.4 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages: 
# packages in environment at /root/anaconda3/envs/catalyst:
#
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.9.9                     <pip>
async-timeout             2.0.1                     <pip>
attrdict                  2.0.0                     <pip>
attrs                     17.4.0                    <pip>
backports                 1.0              py36hfa02d7e_1  
backports.functools_lru_cache 1.5                      py36_0    conda-forge
bcolz                     0.12.1                    <pip>
bleach                    2.1.3                     <pip>
boto3                     1.7.4                     <pip>
botocore                  1.10.4                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h1d4fec5_0  
cchardet                  2.1.1                     <pip>
ccxt                      1.12.153                  <pip>
certifi                   2018.1.18                py36_0  
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0           py36h93f1223_0  
cyordereddict             1.0.0                     <pip>
Cython                    0.28.1                    <pip>
cytoolz                   0.9.0.1                   <pip>
dbus                      1.12.2               hc3f9b76_1  
decorator                 4.2.1                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.8                     <pip>
entrypoints               0.2.3                     <pip>
et-xmlfile                1.0.1                     <pip>
eth-abi                   1.0.0                     <pip>
eth-account               0.1.0a2                   <pip>
eth-hash                  0.1.2                     <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b3                   <pip>
eth-rlp                   0.1.0                     <pip>
eth-utils                 1.0.2                     <pip>
expat                     2.2.5                he0dffb1_0  
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8                  hab7d2ae_1  
glib                      2.53.6               h5d9569c_2  
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
hexbytes                  0.1.0                     <pip>
html5lib                  1.0.1                     <pip>
icu                       58.2                 h9c2bf20_1  
idna                      2.6                       <pip>
idna-ssl                  1.0.1                     <pip>
intel-openmp              2018.0.0             hc7b2577_8  
intervaltree              2.1.0                     <pip>
ipykernel                 4.8.2                     <pip>
ipython                   6.2.1                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.1.2                     <pip>
jdcal                     1.3                       <pip>
jedi                      0.11.1                    <pip>
Jinja2                    2.10                      <pip>
jmespath                  0.9.3                     <pip>
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.3                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran-ng            7.2.0                hdf63c60_3  
libpng                    1.6.34               hb9fc6fc_0  
libstdcxx-ng              7.2.0                hdf63c60_3  
libxcb                    1.12                 hcd93eb1_4  
libxml2                   2.9.7                h26e45fe_0  
Logbook                   1.3.0                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.2.1                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.2                    py36_0    conda-forge
mistune                   0.8.3                     <pip>
mkl                       2018.0.1             h19d6760_4  
multidict                 4.1.0                     <pip>
multipledispatch          0.5.0                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
ncurses                   6.0                  h9df7e31_2  
networkx                  2.1                       <pip>
notebook                  5.4.0                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.14.2                    <pip>
numpy                     1.14.0           py36ha266831_2  
openpyxl                  2.5.2                     <pip>
openssl                   1.0.2n               hb7f436b_0  
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
pandocfilters             1.4.2                     <pip>
parso                     0.1.1                     <pip>
patsy                     0.5.0                     <pip>
pcre                      8.41                 hc27e229_1  
pexpect                   4.4.0                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py36_5  
pip                       9.0.3                     <pip>
prompt-toolkit            1.0.15                    <pip>
ptyprocess                0.5.2                     <pip>
pycares                   2.3.0                     <pip>
pycryptodome              3.6.0                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.6.0            py36h0386399_5  
pysha3                    1.0.2                     <pip>
python                    3.6.4                hc3d631a_1  
python-dateutil           2.7.2                     <pip>
python-dateutil           2.6.1            py36h88d3b88_1  
python-editor             1.0.3                     <pip>
pytz                      2018.4                    <pip>
pytz                      2018.3                   py36_0  
pyzmq                     17.0.0                    <pip>
qt                        5.6.2               hd25b39d_14  
qtconsole                 4.3.1                     <pip>
readline                  7.0                  ha6073c6_4  
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.13                    <pip>
scipy                     1.0.0            py36hbf646e7_0  
scipy                     1.0.1                     <pip>
Send2Trash                1.5.0                     <pip>
setuptools                39.0.1                    <pip>
setuptools                38.4.0                   py36_0  
simplegeneric             0.8.1                     <pip>
sip                       4.18.1           py36h51ed4ed_2  
six                       1.11.0           py36h372c433_1  
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.6                     <pip>
sqlite                    3.22.0               h1bed415_0  
statsmodels               0.8.0                     <pip>
TA-Lib                    0.4.17                    <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1                     <pip>
tk                        8.6.7                hc745277_3  
toolz                     0.9.0                     <pip>
tornado                   5.0                      py36_0  
traitlets                 4.3.2                     <pip>
urllib3                   1.22                      <pip>
wcwidth                   0.1.7                     <pip>
web3                      4.1.0                     <pip>
webencodings              0.5.1                     <pip>
websockets                4.0.1                     <pip>
wheel                     0.30.0           py36hfd4bba0_1  
widgetsnbextension        3.1.4                     <pip>
wrapt                     1.10.11                   <pip>
xz                        5.2.3                h55aa19d_2  
yarl                      1.1.0                     <pip>
zlib                      1.2.11               ha838bed_2 

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? The transaction dataframe returned by extract_transactions should contain the commission of every transaction. 
* What happened instead? The commission is missing but when looking at the orders column of the results dataframe in the analyze function, you can see that the transaction had a commission.

.

## What steps have you taken to resolve this already?
For now I am taking the commission from the results dataframe instead the transaction.

I attach an excel where you could see what I mean

[statistics.xlsx](https://github.com/enigmampc/catalyst/files/1977707/statistics.xlsx)

**Comment by lenak25** [comment]
@xbionicx , I believe this issue was reported at #304 and addressed in the latest catalyst release - 0.5.9.
Please [upgrade](https://enigma.co/catalyst/install.html?highlight=uninstall#updating-catalyst) to the latest release and feel free to reopen if you observe any issues.

Thanks!
