### ISSUE TITLE
catalyst >marketplace ls< shows only Ids but not the names of the Datasets

### ISSUE THREAD

**Issue by avolution** [enigmampc/catalyst#327]
Hey guys,

I have the following problem:

catalyst >marketplace ls< shows only Ids but not the names of the Datasets

I run Catalyst 0.5.9 on Mac installed via conda env

Here is the console output 
(catalyst) $  catalyst marketplace ls
Listing of available data sources on the marketplace:
   dataset
0         
1         
2         
3         
4         
5         
6         
7         
8         
9         
10        
11        
12        
13        
14        
15        
16        
17        
18        
19        
20        
21        
22        
23        
24

**Comment by apalepu23** [comment]
Hi @avolution,

This issue has been resolved and the fix will be included in the new release of the enigma-catalyst package, which will be released in the next couple of days. 

Thanks for raising this :)

**Comment by lenak25** [comment]
Fixed at version 0.5.10.
