### ISSUE TITLE
Cannot use ingest-exchange '--csv' option in Jupyter notebook

### ISSUE THREAD

**Issue by hnipps** [enigmampc/catalyst#336]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: MacOS High Sierra 10.13.4
* Python Version: Python 3.6.4 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages: 

# Name                    Version                   Build  Channel
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.9.7                     <pip>
appnope                   0.1.0                     <pip>
astroid                   1.6.3                    py36_0  
async-timeout             2.0.0                     <pip>
attrdict                  2.0.0                     <pip>
attrs                     17.4.0                    <pip>
autopep8                  1.3.5                     <pip>
backcall                  0.1.0                     <pip>
backports                 1.0              py36ha3c1827_1  
backports.functools_lru_cache 1.5                      py36_0    conda-forge
bcolz                     0.12.1                    <pip>
bleach                    2.1.3                     <pip>
boto3                     1.5.27                    <pip>
botocore                  1.8.41                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0  
cchardet                  2.1.1                     <pip>
ccxt                      1.10.1102                 <pip>
certifi                   2018.1.18                py36_0  
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0           py36hfc81398_0  
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
cytoolz                   0.9.0                     <pip>
decorator                 4.2.1                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.8                     <pip>
entrypoints               0.2.3                     <pip>
eth-abi                   1.0.0b0                   <pip>
eth-account               0.1.0a2                   <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b1                   <pip>
eth-rlp                   0.1.0a2                   <pip>
eth-utils                 1.0.0b1                   <pip>
freetype                  2.8                  h12048fb_1  
hexbytes                  0.1.0b0                   <pip>
html5lib                  1.0.1                     <pip>
idna                      2.6                       <pip>
idna-ssl                  1.0.0                     <pip>
intel-openmp              2018.0.0                      8  
intervaltree              2.1.0                     <pip>
ipykernel                 4.8.2                     <pip>
ipython                   6.3.1                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.2.1                     <pip>
isort                     4.3.4                    py36_0  
jedi                      0.12.0                    <pip>
Jinja2                    2.10                      <pip>
jmespath                  0.9.3                     <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.3                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
kiwisolver                1.0.1            py36h792292d_0  
lazy-object-proxy         1.3.1            py36h2fbbe47_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libpng                    1.6.34               he12f830_0  
Logbook                   1.2.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.1.1                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.2.2            py36ha7267d0_0  
mccabe                    0.6.1            py36hdaeb55d_0  
mistune                   0.8.3                     <pip>
mkl                       2018.0.1             hfbd8650_4  
multidict                 4.1.0                     <pip>
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
ncurses                   6.0                  hd04f020_2  
networkx                  2.1                       <pip>
notebook                  5.4.1                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.14.0           py36ha726252_2  
openssl                   1.0.2n               hdbc3d79_0  
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
pandocfilters             1.4.2                     <pip>
parso                     0.2.0                     <pip>
patsy                     0.5.0                     <pip>
pexpect                   4.5.0                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py36_5  
prompt-toolkit            1.0.15                    <pip>
ptyprocess                0.5.2                     <pip>
pycares                   2.3.0                     <pip>
pycodestyle               2.4.0                     <pip>
pycryptodome              3.4.11                    <pip>
Pygments                  2.2.0                     <pip>
pylint                    1.8.4                    py36_0  
pyparsing                 2.2.0            py36hb281f35_0  
pysha3                    1.0.2                     <pip>
python                    3.6.4                hc167b69_3  
python-dateutil           2.6.1                     <pip>
python-dateutil           2.7.2                    py36_0  
python-editor             1.0.3                     <pip>
pytz                      2018.3                   py36_0  
pyzmq                     17.0.0                    <pip>
qtconsole                 4.3.1                     <pip>
readline                  7.0                  hc1231fa_4  
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
rope                      0.10.7           py36h68959ac_0  
s3transfer                0.1.12                    <pip>
scipy                     1.0.0            py36h1de22e9_0  
Send2Trash                1.5.0                     <pip>
setuptools                38.4.0                   py36_0  
simplegeneric             0.8.1                     <pip>
six                       1.11.0           py36h0e22d5e_1  
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.2                     <pip>
sqlite                    3.22.0               h3efe00b_0  
statsmodels               0.8.0                     <pip>
TA-Lib                    0.4.17                    <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1                     <pip>
tk                        8.6.7                h35a86e2_3  
toolz                     0.9.0                     <pip>
tornado                   5.0.1                    py36_1  
traitlets                 4.3.2                     <pip>
urllib3                   1.22                      <pip>
wcwidth                   0.1.7                     <pip>
web3                      4.0.0b9                   <pip>
webencodings              0.5.1                     <pip>
wheel                     0.30.0           py36h5eb2c71_1  
widgetsnbextension        3.2.1                     <pip>
wrapt                     1.10.11          py36hc29e774_0  
wrapt                     1.10.11                   <pip>
xz                        5.2.3                h0278029_2  
yarl                      1.1.0                     <pip>
zlib                      1.2.11               hf3cbc9b_2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I expected that I'd be able to import price data from a CSV file, by running the Python magic command in a Jupyter notebook. The command works in the terminal.

`$ catalyst ingest-exchange -x bitfinex --csv ./notebooks/test-mc-prices.csv -f minute`

* What happened instead?
This error is logged:
```
---------------------------------------------------------------------------
NoSuchOption                              Traceback (most recent call last)
<ipython-input-26-88d20aba5c53> in <module>()
----> 1 get_ipython().run_line_magic('catalyst', 'ingest-exchange -x bitfinex --csv ./notebooks/test-mc-prices.csv -f minute')

~/miniconda3/envs/catalyst/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2129                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2130             with self.builtin_trap:
-> 2131                 result = fn(*args,**kwargs)
   2132             return result
   2133 

~/miniconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/__main__.py in catalyst_magic(line, cell)
    324             '%s%%catalyst' % ((cell or '') and '%'),
    325             # don't use system exit and propogate errors to the caller
--> 326             standalone_mode=False,
    327         )
    328     except SystemExit as e:

~/miniconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py in main(self, args, prog_name, complete_var, standalone_mode, **extra)
    694         try:
    695             try:
--> 696                 with self.make_context(prog_name, args, **extra) as ctx:
    697                     rv = self.invoke(ctx)
    698                     if not standalone_mode:

~/miniconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py in make_context(self, info_name, args, parent, **extra)
    619         ctx = Context(self, info_name=info_name, parent=parent, **extra)
    620         with ctx.scope(cleanup=False):
--> 621             self.parse_args(ctx, args)
    622         return ctx
    623 

~/miniconda3/envs/catalyst/lib/python3.6/site-packages/click/core.py in parse_args(self, ctx, args)
    874     def parse_args(self, ctx, args):
    875         parser = self.make_parser(ctx)
--> 876         opts, args, param_order = parser.parse_args(args=args)
    877 
    878         for param in iter_params_for_processing(

~/miniconda3/envs/catalyst/lib/python3.6/site-packages/click/parser.py in parse_args(self, args)
    265         state = ParsingState(args)
    266         try:
--> 267             self._process_args_for_options(state)
    268             self._process_args_for_args(state)
    269         except UsageError:

~/miniconda3/envs/catalyst/lib/python3.6/site-packages/click/parser.py in _process_args_for_options(self, state)
    291                 return
    292             elif arg[:1] in self._opt_prefixes and arglen > 1:
--> 293                 self._process_opts(arg, state)
    294             elif self.allow_interspersed_args:
    295                 state.largs.append(arg)

~/miniconda3/envs/catalyst/lib/python3.6/site-packages/click/parser.py in _process_opts(self, arg, state)
    412         # like "-foo" to be matched as long options.
    413         try:
--> 414             self._match_long_opt(norm_long_opt, explicit_value, state)
    415         except NoSuchOption:
    416             # At this point the long option matching failed, and we need

~/miniconda3/envs/catalyst/lib/python3.6/site-packages/click/parser.py in _match_long_opt(self, opt, explicit_value, state)
    322             possibilities = [word for word in self._long_opt
    323                              if word.startswith(opt)]
--> 324             raise NoSuchOption(opt, possibilities=possibilities)
    325 
    326         option = self._long_opt[opt]

NoSuchOption: no such option: --csv
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Run this in a Jupyter notebook cell:
```
import catalyst
# Register the catalyst magic
%load_ext catalyst
%catalyst ingest-exchange -x bitfinex --csv ./notebooks/test-mc-prices.csv -f minute
```

## What steps have you taken to resolve this already?
Using the Catalyst API ExchangeBundle directly as a workaround.

I can't see a reason in __main__ why the CSV option wouldn't be allowed.
...

# Anything else?

...

Sincerely,
Harry

**Comment by AvishaiW** [comment]
Hi @hnipps Catalyst doesn't support ingestion via Jupyter Notebook, you [must ingest](https://enigma.co/catalyst/beginner-tutorial.html#running-algorithms) the data on a Cli prior to running your algorithm

**Comment by hnipps** [comment]
That's a shame. I was hoping to include it in an automated workflow inside Jupyter. Thanks for letting me know.

**Comment by lenak25** [comment]
@hnipps we are closing this, feel free to reopen if you have more questions.

**Comment by ernstjendritzki** [comment]
That did not really help. Jupyter seems not to have access to the ingesting-data...
