### ISSUE TITLE
Major currency pairs missing in Bitfinex (backtest mode)

### ISSUE THREAD

**Issue by dj-sly** [enigmampc/catalyst#337]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

Mac OS
Python 3
PIP install

aiodns==1.1.1
aiohttp==3.0.1
alembic==0.9.9
appnope==0.1.0
async-timeout==2.0.1
attrdict==2.0.0
attrs==17.4.0
backcall==0.1.0
bcolz==0.12.1
bleach==2.1.3
boto3==1.6.20
botocore==1.9.20
Bottleneck==1.2.1
cchardet==2.1.1
ccxt==1.12.43
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.28.1
cytoolz==0.9.0.1
decorator==4.2.1
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.8
entrypoints==0.2.3
eth-abi==1.0.0
eth-account==0.1.0a2
eth-hash==0.1.1
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.0
eth-utils==1.0.1
hexbytes==0.1.0
html5lib==1.0.1
idna==2.6
idna-ssl==1.0.1
intervaltree==2.1.0
ipykernel==4.8.2
ipython==6.3.0
ipython-genutils==0.2.0
ipywidgets==7.2.0
jedi==0.11.1
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
kiwisolver==1.0.1
Logbook==1.3.0
lru-dict==1.1.6
lxml==4.2.1
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.2.2
mistune==0.8.3
multidict==4.1.0
multipledispatch==0.5.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
notebook==5.4.1
numexpr==2.6.4
numpy==1.14.2
pandas==0.19.2
pandas-datareader==0.6.0
pandocfilters==1.4.2
parso==0.1.1
patsy==0.5.0
pexpect==4.4.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pycares==2.3.0
pycryptodome==3.5.1
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.7.2
python-editor==1.0.3
pytz==2018.3
pyzmq==17.0.0
qtconsole==4.3.1
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==0.6.0
ruamel.yaml==0.15.37
s3transfer==0.1.13
scipy==1.0.1
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.5
statsmodels==0.8.0
TA-Lib==0.4.17
tables==3.4.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==5.0.1
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
web3==4.0.0b13
webencodings==0.5.1
widgetsnbextension==3.2.0
wrapt==1.10.11
yarl==1.1.0

Now that you know a little about me, let me tell you about the issue I am
having:

I am seeing BTC_USD and ETH_USD Bitfinex pairs only ingest up to approximately 3/27/2018. The data for these (major) currency pairs drops off thereafter. 

Note I am running a simple buy and hold strategy in a backtest environment.

Can you please advise?

thanks

**Comment by jake-smithandcrown** [comment]
Actually I am going to move this discussion to Discord (might be a better format). thanks

**Comment by lenak25** [comment]
Thanks for reporting @dj-sly , we will check this.
I am reopening this issue, as this is the preferred place to bug reports. Discord is good for discussions but once a bug is identified, it it much more convenient to track it here.
Thanks,
Lena

**Comment by lenak25** [comment]
@dj-sly I wasn't able to reproduce the problems you have experienced.
Could you please try to re-ingest and re-run your algorithm?

**Comment by dj-sly** [comment]
Thanks, Lena! Understood and appreciate the help with this.

**Comment by lenak25** [comment]
@dj-sly , it seems that in some place in the code you specify the `btc_usdt` pair instead the `btc_usd` which is the one supported at Bitfinex.

**Comment by lenak25** [comment]
@dj-sly I am closing this, if you are still experiencing any issues, feel free to report back and reopen this.
