### ISSUE TITLE
"Live trading" doc page has a broken link

### ISSUE THREAD

**Issue by STOpandthink** [enigmampc/catalyst#338]
https://enigma.co/catalyst/live-trading.html
`Here is a complete algorithm for reference: [Buy Low and Sell High](https://github.com/enigmampc/catalyst/blob/master/catalyst/examples/buy_low_sell_high_live.py)`

The link is broken. Should be this: https://github.com/enigmampc/catalyst/blob/11302b3af96f9a1e7787b1aeda66b87fc248b8c4/catalyst/examples/buy_low_sell_high.py ?

**Comment by lenak25** [comment]
Thanks for reporting @STOpandthink ! 
We will address this.

**Comment by lenak25** [comment]
Was added to release 0.5.12.
Thank for noting it!
