### ISSUE TITLE
Unable to import catalyst in the jupyter notebook

### ISSUE THREAD

**Issue by joewaltman** [enigmampc/catalyst#340]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Darwin
* Python Version: Python 3.6.4 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages: 
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.9.7                     <pip>
appnope                   0.1.0                     <pip>
async-timeout             2.0.0                     <pip>
attrdict                  2.0.0                     <pip>
attrs                     17.4.0                    <pip>
backcall                  0.1.0                     <pip>
backports                 1.0              py36ha3c1827_1
backports.functools_lru_cache 1.5                      py36_0    conda-forge
bcolz                     0.12.1                    <pip>
bleach                    2.1.3                     <pip>
boto3                     1.5.27                    <pip>
botocore                  1.8.41                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0
cchardet                  2.1.1                     <pip>
ccxt                      1.10.1102                 <pip>
certifi                   2018.1.18                py36_0
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0           py36hfc81398_0
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
cytoolz                   0.9.0                     <pip>
decorator                 4.2.1                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.11                    <pip>
entrypoints               0.2.3                     <pip>
eth-abi                   1.0.0b0                   <pip>
eth-account               0.1.0a2                   <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b1                   <pip>
eth-rlp                   0.1.0a2                   <pip>
eth-utils                 1.0.0b1                   <pip>
freetype                  2.8                  h12048fb_1
hexbytes                  0.1.0b0                   <pip>
html5lib                  1.0.1                     <pip>
idna                      2.6                       <pip>
idna-ssl                  1.0.0                     <pip>
intel-openmp              2018.0.0                      8
intervaltree              2.1.0                     <pip>
ipykernel                 4.8.2                     <pip>
ipython                   6.4.0                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.2.1                     <pip>
jedi                      0.12.0                    <pip>
Jinja2                    2.10                      <pip>
jmespath                  0.9.3                     <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.3                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libedit                   3.1.20170329         hb402a30_2
libffi                    3.2.1                h475c297_4
libgfortran               3.0.1                h93005f0_2
libpng                    1.6.34               he12f830_0
Logbook                   1.2.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.1.1                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.2                    py36_0    conda-forge
mistune                   0.8.3                     <pip>
mkl                       2018.0.1             hfbd8650_4
multidict                 4.1.0                     <pip>
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
ncurses                   6.1                  h0a44026_0
networkx                  2.1                       <pip>
notebook                  5.5.0                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.14.0           py36ha726252_2
openssl                   1.0.2n               hdbc3d79_0
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
pandocfilters             1.4.2                     <pip>
parso                     0.2.1                     <pip>
patsy                     0.5.0                     <pip>
pexpect                   4.5.0                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py36_5
prompt-toolkit            1.0.15                    <pip>
ptyprocess                0.5.2                     <pip>
pycares                   2.3.0                     <pip>
pycryptodome              3.4.11                    <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0            py36hb281f35_0
pysha3                    1.0.2                     <pip>
python                    3.6.4                hc167b69_3
python-dateutil           2.7.3                    py36_0
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2018.4                   py36_0
pytz                      2018.3                    <pip>
pyzmq                     17.0.0                    <pip>
qtconsole                 4.3.1                     <pip>
readline                  7.0                  hc1231fa_4
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     1.0.0            py36h1de22e9_0
Send2Trash                1.5.0                     <pip>
setuptools                38.4.0                   py36_0
simplegeneric             0.8.1                     <pip>
six                       1.11.0           py36h0e22d5e_1
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.2                     <pip>
sqlite                    3.22.0               h3efe00b_0
statsmodels               0.8.0                     <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1                     <pip>
tk                        8.6.7                h35a86e2_3
toolz                     0.9.0                     <pip>
tornado                   5.0.2                    py36_0
traitlets                 4.3.2                     <pip>
urllib3                   1.22                      <pip>
wcwidth                   0.1.7                     <pip>
web3                      4.0.0b9                   <pip>
webencodings              0.5.1                     <pip>
wheel                     0.30.0           py36h5eb2c71_1
widgetsnbextension        3.2.1                     <pip>
wrapt                     1.10.11                   <pip>
xz                        5.2.3                h727817e_4
yarl                      1.1.0                     <pip>
zlib                      1.2.11               hf3cbc9b_2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I am trying to run catalyst in the Jupyter notebook. When I try to execute the import catalyst cell, I get the following error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-e7247172b6dc> in <module>()
----> 1 import catalyst

ModuleNotFoundError: No module named 'catalyst'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Active catalyst (i.e. source activate catalyst)
2. Start a jupyter notebook (i.e. jupyter notebook)
3. Attempt to import catalyst in the notebook
...

## What steps have you taken to resolve this already?
I've searched through your forum and google. I haven't found any mention of this issue. 

...

# Anything else?
Thanks for the help...really appreciate it. :)

...

Sincerely,
`$ whoami`

**Comment by lenak25** [comment]
Hi @joewaltman , have you followed [these instructions](https://enigma.co/catalyst/beginner-tutorial.html#jupyter-notebook), especially running this command: `%load_ext catalyst`?

**Comment by joewaltman** [comment]
Yeah....followed (and triple checked). Per the instructions, you are supposed to import catalyst (which is what produces the error) before your run the %load_ext command. 

Thanks. :/

**Comment by sawyercade** [comment]
+1 experiencing the same issue using catalyst with Jupyter.

Followed the conda install instructions, `$ source activate catalyst`, `$ pip install jupyter`, `$ jupyter notebook`, `import catalyst` -> ModuleNotFoundError: No module named 'catalyst'.

`%load_ext catalyst` also raises a `ModuleNotFoundError: No module named 'catalyst`

**Comment by sawyercade** [comment]
Update: I was able to get this working by installing jupyter in the conda environment I created for catalyst:

```$conda install -n catalyst jupyter
$jupyter notebook```

Then the following cells work as expected:
`[1] import catalyst`
`[2] %load_ext catalyst`

**Comment by lucasgadams** [comment]
What I usually do to run notebooks from within virtual environments is this

```
source env/bin/activate
pip3 install ipykernel
python3 -m ipykernel install --user --name=my-virtualenv-name
```

This works if you have jupyter notebook installed globally. Then when you start a new notebook you just need to select the appropriate kernel from the dropdown.

**Comment by aslakter** [comment]
Yeah, it was a jupyter kernel issue for me. This worked: 
`python -m ipykernel install --user --name catalyst --display-name "Python (catalyst)"`
