### ISSUE TITLE
bela_btc on Poloniex still returned by get_exchange_symbol

### ISSUE THREAD

**Issue by sam31415** [enigmampc/catalyst#342]
Hi,

bela_btc has just been delisted on Poloniex, but is still returned by `get_exchange_symbol`. When this pair is fed into `symbol` or `symbols` to obtain the corresponding asset object, an error occurs. 
```
catalyst.exchange.exchange_errors.SymbolNotFoundOnExchange: Symbol BELA_BTC not found on exchange Poloniex. Choose from: ['amp_btc', 'ardr_btc', 'bch_btc', 'bc
h_eth', 'bch_usdt', 'bcn_btc', 'bcn_xmr', 'bcy_btc', 'blk_btc', 'blk_xmr', 'btc_usdt', 'btcd_btc', 'btcd_xmr', 'btm_btc', 'bts_btc', 'burst_btc', 'clam_btc', '
cvc_btc', 'cvc_eth', 'dash_btc', 'dash_usdt', 'dash_xmr', 'dcr_btc', 'dgb_btc', 'doge_btc', 'emc2_btc', 'etc_btc', 'etc_eth', 'etc_usdt', 'eth_btc', 'eth_usdt'
, 'exp_btc', 'fct_btc', 'fldc_btc', 'flo_btc', 'game_btc', 'gas_btc', 'gas_eth', 'gno_btc', 'gno_eth', 'gnt_btc', 'gnt_eth', 'grc_btc', 'huc_btc', 'lbc_btc', '
lsk_btc', 'lsk_eth', 'ltc_btc', 'ltc_usdt', 'ltc_xmr', 'maid_btc', 'maid_xmr', 'nav_btc', 'neos_btc', 'nmc_btc', 'nxc_btc', 'nxt_btc', 'nxt_usdt', 'nxt_xmr', '
omg_btc', 'omg_eth', 'omni_btc', 'pasc_btc', 'pink_btc', 'pot_btc', 'ppc_btc', 'rads_btc', 'rep_btc', 'rep_eth', 'rep_usdt', 'ric_btc', 'sbd_btc', 'sc_btc', 's
teem_btc', 'steem_eth', 'storj_btc', 'str_btc', 'str_usdt', 'strat_btc', 'sys_btc', 'via_btc', 'vrc_btc', 'vtc_btc', 'xbc_btc', 'xcp_btc', 'xem_btc', 'xmr_btc'
, 'xmr_usdt', 'xpm_btc', 'xrp_btc', 'xrp_usdt', 'xvc_btc', 'zec_btc', 'zec_eth', 'zec_usdt', 'zec_xmr', 'zrx_btc', 'zrx_eth'] 
```                
I've just updated Catalyst to 0.5.12.

Best,

Samuel

**Comment by lenak25** [comment]
Hi @sam31415 , thanks for reporting.
If you'll try to run `get_exchange_symbol` function now, I think you'll see that the pair `bela_btc` is no longer returned.
I think that you have probably experienced the delay it takes to update the exchanges symbol list internally in catalyst servers. 
The `get_symbol` function reads the catalyst internal exchange symbols info which was not yet updated, while the `get_exchange_symbol` get the info straight from the exchange (using the CCXT library).

**Comment by sam31415** [comment]
Hi,

Thanks. But I can confirm that I was really using the `get_exchange_symbol` function. If it's really getting the info through the exchange through CCXT, how comes it returned the `bela_btc` pair when it was not traded anymore? Are you saying the issue is with Poloniex?

Best,

Samuel

**Comment by lenak25** [comment]
@sam31415 , my mistake, I meant that the  `get_exchange_symbol` reads the catalyst internal exchange symbols while the `get_symbol` gets the info straight from the exchange.
Sorry for the confusion!

**Comment by sam31415** [comment]
@lenak25  Ok thanks for the info!
