### ISSUE TITLE
Errors in `context.portfolio.portfolio_value`

### ISSUE THREAD

**Issue by abnera** [enigmampc/catalyst#35]
Dear Catalyst Maintainers and @lacabra 

# Description of Issue
I'm trying to use `context.portfolio.portfolio_value` and `context.portfolio.cash` to limit when I can buy I sell assets and control my leverage and handle all kind of exception but there are two problems with these values.

### First Error: Update context.portfolio and cotext.account immediately after transaction completed
`context.portfolio` and `context.account` take too long to be updated. These are updated in the next cycle of scheduling function. However, if you decide to purchase multiple assets/coins on the cycle it can lead to errors. 

Ideally, once the order has been successfully completed (i.e someone bought my coins I bought the coins I wanted) it should instantly update the values of both `context.portfolio` and `context.account`.

### Secon Error: Even in the next cycle, the calculations are sometimes erroneous. 
Fixed with enigma-catalyst 0.2.dev4

Sincerely,
`avn3r`

**Comment by lacabra** [comment]
I'm curious to hear from you if the second issue you report has been addressed with the 0.2.dev3 release that implements trading of fractional coins?

**Comment by abnera** [comment]
Yes, it seems to be fixed now, all the numbers are adding up perfectly. I'll edit the issue request to just the first error.

With respect to the first error. Basically, it will be nice to have a flag of when the transaction is completed to update the profile and account. that way I can do a waiting while_loop where I wait till the transaction is completed to move forward or if taking too long to complete the transaction I can cancel it.
