### ISSUE TITLE
Difference between 'price' and 'close'

### ISSUE THREAD

**Issue by bukosabino** [enigmampc/catalyst#353]
Dear Catalyst Maintainers,

I have a doubt. What is the logic difference between 2 sentences?

```python
close = data.current(context.asset, 'close')
price = data.current(context.asset, 'price')
```

Sincerely,
Bukosabino.

**Comment by STOpandthink** [comment]
As far as I could tell, close == price. I think the difference comes from the stock market, where you could have one closing price for a day, but a different current price (if the asset is trading in the off-hours).

**Comment by SOGorman35** [comment]
the terms are way too broad for me to have any luck searching, but I seem to remember seeing on the Quantopian forums that "close" and "price" are identical.

**Comment by lenak25** [comment]
Hi,

I think [this Quantopian thread](https://www.quantopian.com/posts/whats-the-difference-between-data-dot-current-index-close-and-data-dot-current-index-price) explains the zipline approach.
In catalyst, both fields are completely identical, as can be seen at the `get_spot_value` function implementation of the `DataPortalExchangeBase` class (exchange_data_portal.py).

**Comment by lenak25** [comment]
@bukosabino , I am closing this, feel free to reopen if something is still unclear.
