### ISSUE TITLE
Tests don't pass

### ISSUE THREAD

**Issue by bogensberger** [enigmampc/catalyst#354]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Darwin Philipps-MacBook-Pro-2.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
* Python Version: Python 3.6.5
* Python Bitness: 64
* How did you install Catalyst: checked out from source and run:
```
.venv/bin/pip install -r etc/requirements.txt
.venv/bin/pip install -r etc/requirements_dev.txt
.venv/bin/pip install -r etc/requirements_blaze.txt
.venv/bin/pip install -r etc/requirements_talib.txt
.venv/bin/pip install -e .
.venv/bin/python setup.py build_ext --inplace
```

As I couldn't find how to run the tests in the development guidelines ( docs/source/development-guidelines.rst ) I followed the appveyor file and the zipline documentation.

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

When I run the nosetests a lot of them fail:

```
.venv/bin/nosetests
...
Ran 1817 tests in 10509.935s

FAILED (errors=305, failures=247)
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

```.venv/bin/nosetests```

## What steps have you taken to resolve this already?

I read the developer documentation and also followed the zipline guidelines to run the tests. 

# Anything else?

In the test logs I also see that one test is trying to access `/Users/fredfortier/Dropbox/Enigma/Data/bittrex_bat_eth.csv` which of course doesn't exist on my machine.

Thanks,
Philipp

**Comment by lenak25** [comment]
Thanks @bogensberger for bringing this up. 
We are in an ongoing process of adjusting the zipline tests and adding dedicated catalyst unit tests however its still a work in progress. There is an [open issue](https://github.com/enigmampc/catalyst/issues/113) with regards to this.

**Comment by bogensberger** [comment]
@lenak25 do you have any idea until this will run again? There are a few contributions I would like to make, but it's basically impossible without being able to verify if I haven't broke anything.

**Comment by ykgoon** [comment]
>  but it's hard to do without being able to verify that I didn't break anything.

I had the same problem. There isn't clear documentation (if at all) on running tests.

**Comment by lenak25** [comment]
@bogensberger and @ykgoon , thanks for your feedback, we are aware of the current problematic state of the testing environment and we planning to address it ASAP.

**Comment by brandsimon** [comment]
Is it known, that there are still 36 errors and 3 failures on python 3.6.6 (64bit) or is it my system?

**Comment by lenak25** [comment]
Hi @brandsimon , on what system are you running the tests?

Catalyst tests are being run using Travis on Linux, both with Python 2.7 and Python 3.6: https://travis-ci.com/enigmampc/catalyst

**Comment by brandsimon** [comment]
Hi @lenak25 , I am sorry for the late answer. I was on vacation and after that I had a lot of important things to do first.

I ran it on an uptodate arch linux system 26 days ago. Now I ran it on a Debian 10 system (64bit, Python 3.6.6) and it also fails.
I ran it on catalyst 0.5.18 from git with these commands
```
python3.6 -m venv .venv
.venv/bin/pip install --upgrade pip
.venv/bin/pip install -r etc/requirements.txt
.venv/bin/pip install -r etc/requirements_talib.txt
.venv/bin/pip install -r etc/requirements_dev.txt
.venv/bin/pip install -e .
.venv/bin/catalyst ingest-exchange -x poloniex -f daily -i xcp_btc
.venv/bin/catalyst ingest-exchange -x poloniex -f minute -i btc_usdt
.venv/bin/nosetests >&2 2> log
```

I attach the log and a `pip freeze`

[pip-freeze.txt](https://github.com/enigmampc/catalyst/files/2289833/pip-freeze.txt)
[log.txt](https://github.com/enigmampc/catalyst/files/2289971/log.txt)

**Comment by lenak25** [comment]
Thanks for the info @brandsimon , please look at the [travis config](https://github.com/enigmampc/catalyst/blob/master/.travis.yml) to learn more about the steps required for running the tests.
From looking at the data you attached:
* The `requirements_blaze.txt` installation is missing 
* You should run the tests using: `cd tests && nosetests`

**Comment by brandsimon** [comment]
@lenak25 Thank you very much, all tests pass.

**Comment by lenak25** [comment]
Happy to hear, I am closing this, feel free to reopen if you have any more questions/issues.
