### ISSUE TITLE
catalyst ingest-exchange -x poloniex -i btc_usdt --show-progress fails with a Http 403 error

### ISSUE THREAD

**Issue by aknirmal90** [enigmampc/catalyst#355]
* Operating System: MAC OSX HighSierra 10.13.4
* Python Version: 3.6.2
* Python Bitness: 64
* How did you install Catalyst: pip
* Python packages: catalyst, ipython, jupyter

I'm seeing an error on running the command above. I think this is failing because there seems to be an intermediary captcha page which turns up when we try to hit the public APIs.

This is the error message thrown up by python
```
ccxt.base.errors.ExchangeNotAvailable: poloniex https://poloniex.com/public?command=returnTicker GET 403 Client Error: Forbidden for url: https://poloniex.com/public?command=returnTicker <!DOCTYPE html>
```

Could you suggest a workaround for this?

**Comment by lacabra** [comment]
This is a known issue with Poloniex exchange. There is nothing we can do. This happens when you retrieve data from the exchange from certain geographies (mostly from outside the US).

Our only recommendation is that you connect to the exchange via a VPN, simulating you are inside the US.
