### ISSUE TITLE
Missing data for bitfinex eth_usd

### ISSUE THREAD

**Issue by avolution** [enigmampc/catalyst#357]
--->

catalyst.exchange.exchange_errors.PricingDataNotLoadedError: Missing data for bitfinex eth_usd in date range [2018-02-27 23:01:00+00:00 - 2018-02-28 00:00:00+00:00]
Please run: `catalyst ingest-exchange -x bitfinex -f minute -i eth_usd`. See catalyst documentation for details.

after running the command:

catalyst ingest-exchange -x bitfinex -f minute -i eth_usd

the data is still missing.

A Gap in the Dataset?

I use Catalyst 0.5.12 on Mac

**Comment by lenak25** [comment]
Hi @avolution , 

Could you please clean your data using `catalyst clean-exchange -x bitfinex` , re-ingest the data and try again?

**Comment by avolution** [comment]
That solves my Problem Thx

**Comment by lenak25** [comment]
Great, closing this.
