### ISSUE TITLE
Get order by id does not work for all exchanges

### ISSUE THREAD

**Issue by red-eagle-eye** [enigmampc/catalyst#372]
Dear Catalyst Maintainers,

# Description of Issue
* What did you expect to happen?
API method `TradingAlgorithm::get_order` to work for exchanges that require the asset symbol as a parameter (e.g. Binance) 

* What happened instead?
The `get_order` method signature only receives the `order_id`.

Here is how you can reproduce this issue on your machine:
Just place any order on Binance and try to get it by `id`

## What steps have you taken to resolve this already?
Add additional arguments to the `get_order` method signature:
`def get_order(self, order_id, exchange_name, symbol=None, params={})`
This allows the client to optionally specify the symbol and also any additional parameters required by the exchange (similiar to the `cancel_order` signature)

Cheers,
Red Eagle

**Comment by AvishaiW** [comment]
fixed on develop. will be released towards the end of the week. Thanks for noting this out!

**Comment by AvishaiW** [comment]
added to release 0.5.14

**Comment by red-eagle-eye** [comment]
Great @AvishaiW! Nice improvements. Thanks
