### ISSUE TITLE
Portfolio sync is missing asset positions that are locked in open orders

### ISSUE THREAD

**Issue by red-eagle-eye** [enigmampc/catalyst#373]
Dear Catalyst Maintainers,

# Description of Issue
* What did you expect to happen?
While doing the portfolio synchronisation the positions sync should take into consideration the available total amount of the currency (available amount + in-order amount).
Example:
Amount available: 0
Amount in orders: 0.4
Portfolio position: 0.4    

* What happened instead?
The check low balance method (`_check_low_balance`) is using the the `free` amount and not the `total` amount.
 Example:
Amount available: 0
Amount in orders: 0.4
Portfolio position: 0   

Here is how you can reproduce this issue on your machine:
You need to have open orders to sell your asset. When the portfolio is synched you will not have the correct value on your positions.

## Reproduction Steps
1. Buy some asset
2. Place a limit order to sell that asset (with a limit price that is not going to be matched)
3. Wait for the next time frame (e.g. 1 minute)
4. Check that your portfolio positions are missing the asset being sold (but the order is not matched yet)

## What steps have you taken to resolve this already?
The method `Exchange::sync_positions` should the total amount to the `_check_low_balance`.
I've temporarily created a `_check_low_total_balance` to use here:
```
    def _check_low_total_balance(self, currency, balances, amount):
        total = balances[currency]['total'] if currency in balances else None
        if total is None:
            return None, False
        if total < amount:
            return total, True
        else:
            return total, False
```

Cheers,
Red Eagle

**Comment by AvishaiW** [comment]
Hi, pushed fix into the develop branch (although I think Catalyst avoids checking the currency balance when orders are open) will be released towards the end of the week. Thanks!

**Comment by AvishaiW** [comment]
added to release 0.5.14

**Comment by red-eagle-eye** [comment]
Seems great. Thank you!
