### ISSUE TITLE
Simulator is buying orders in the price of the next day instead of the same day

### ISSUE THREAD

**Issue by eranhirs** [enigmampc/catalyst#374]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
Windows 10
* Python Version: `$ python --version`
3.5
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
64
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
pip

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
It seems that the simulator is buying / selling my orders in the price of the next day instead of the same day.

```
Bittrex prices
ZCL - 2018.1.1 - 0.00754999
ZCL - 2018.1.2 - 0.006336961
ZCL - 2018.1.3 - 0.00710002
```

* What did you expect to happen?
In `handle_data` , `data.current_dt` is equal to `2018.01.01 23:59:00`.
I check `data.current(asset, "price")`, and I get the price of 2018.1.1.
I use `order_percent` and , I expect the simulator to buy the coin in the price of 2018.01.01.

* What happened instead?
The simulator actually buys the coin in the price of 2018.01.02.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. `run_algorithm` with 10 btc and Bittrex exchange
1. In `handle_data` - run `order_percent(symbol("zcl_btc"), 1.0)`
2. In the next iteration, check `context.portfolio.portfolio_value`
3. portfolio_value should be approximately `8.393336455`

## What steps have you taken to resolve this already?

I debugged the code, I found out `every_bar` is first calling `blotter.get_transactions` and after that it is calling `handle_data`.
This means `dt_to_use` changes between my `handle_data` to `get_transactions`.
I validated my assumption that the price used really is the price of the next day.

# Anything else?
Thank you for this tool!

**Comment by eranhirs** [comment]
I noticed there is also a value called `context.current_day` which is always 1 day before `data.current_dt`.
Using it doesn't solve the problem because `order_percent(...,1.0)` uses `data.price` of the next day so the amount bought is wrong.

**Comment by AvishaiW** [comment]
Hi, We have an [issue](#348) opened similar to what you are experiencing. We will post our conclusions there. 
Thanks for issuing this!

**Comment by eranhirs** [comment]
Looking at #348  , someone suggested that instead of using `daily` interval just change your code to support `minute` interval and everything will work as expected.
So my problem is solved 😄
