### ISSUE TITLE
Accessing data outside of backtest

### ISSUE THREAD

**Issue by jshridha** [enigmampc/catalyst#375]
I am trying find a way to access catalysts's data outside of backtest. I realize there is a catalyst.protocol.BarData object that is instantiated that acts as the API to the data. However, I am having difficulty determining how the arguments to that object  to be defined. Any help would be great.

**Comment by lenak25** [comment]
Hi @jshridha , could you please elaborate more on your exact needs?

**Comment by lenak25** [comment]
@jshridha, you can look at [this section](https://enigma.co/catalyst/utilities.html#extracting-market-data) of the docs for an example of saving pricing data.
I am closing this, feel free to reopen if you feel otherwise.
