### ISSUE TITLE
Bid/Ask from order book for live/paper trading

### ISSUE THREAD

**Issue by dlacombejr** [enigmampc/catalyst#381]
Are there plans to add bid and ask data from the order book to the `data` event frame for live and paper trading? Currently, it seems like the only trade execution strategy for a limit order is based on the last close price.

**Comment by lenak25** [comment]
Hi @dlacombejr , thanks for bringing this up.
There is an API for getting the order book information in live and paper trading, however there was a small issue with it which was resolved on develop branch and will be included in catalyst release 0.5.16
Whether using the develop branch or the official release (once it is out) you will be able for example to get the order book of `eth_btc` with depth 10 using the following code:  
`context.exchanges[<exchange_name>].get_orderbook(symbol('etc_btc'), limit=10)` (the `limit` parameter is optional).

**Comment by lenak25** [comment]
The fix was added to 0.5.16.
