### ISSUE TITLE
Can't ingest bittrex data

### ISSUE THREAD

**Issue by lucasgadams** [enigmampc/catalyst#382]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: MacOS Sierra 10.13.5
* Python Version: Python 3.6.5
* How did you install Catalyst: pip installed in virtualenv

aiodns==1.1.1
aiohttp==3.3.2
alembic==0.9.10
async-timeout==3.0.0
attrdict==2.0.0
attrs==18.1.0
bcolz==1.2.1
boto3==1.7.48
botocore==1.10.48
Bottleneck==1.2.1
cchardet==2.1.1
ccxt==1.15.1
certifi==2018.4.16
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.28.3
cytoolz==0.9.0.1
decorator==4.3.0
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.14
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-utils==1.0.3
hexbytes==0.1.0
idna==2.7
idna-ssl==1.0.1
intervaltree==2.1.0
jmespath==0.9.3
Logbook==1.4.0
lru-dict==1.1.6
lxml==4.2.3
Mako==1.0.7
MarkupSafe==1.0
multidict==4.3.1
multipledispatch==0.5.0
networkx==2.1
numexpr==2.6.5
numpy==1.14.5
pandas==0.19.2
pandas-datareader==0.6.0
parsimonious==0.8.0
patsy==0.5.0
pycares==2.3.0
pycryptodome==3.6.3
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2018.5
redo==1.6
requests==2.19.1
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==1.0.1
s3transfer==0.1.13
scipy==1.1.0
six==1.11.0
sortedcontainers==2.0.4
SQLAlchemy==1.2.9
statsmodels==0.9.0
tables==3.4.4
toolz==0.9.0
urllib3==1.23
web3==4.0.0b11
wrapt==1.10.11
yarl==1.1.0

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

Running command:
```catalyst ingest-exchange -x bittrex -f minute```

I get the output message:
```Trying to ingest exchange bundle bittrex...```

But then nothing. No progress bar or data download appears to happen. Ingesting bitfinex and poloniex seems to work fine. Is this expected behavior? Or is bittrex not supported? The status page doesn't have any information on it https://enigma.co/catalyst/status/

**Comment by lenak25** [comment]
Hi @lucasgadams , thanks for reporting the issue with the coverage page, we are aware of it and working to fix it.
Regarding Bittrex, no minute-resolution data is currently available for this exchange. Historical data is provided with daily resolution for Bittrex, Bitfinex and Poloniex but minute resolution data is currently available for only Bitfinex and Poloniex. 
With that said, we are actively adding historical data for more exchanges.
