### ISSUE TITLE
portolio.cash not calculated properly when selling

### ISSUE THREAD

**Issue by eranhirs** [enigmampc/catalyst#383]
Dear Catalyst Maintainers,

# Description of Issue
I run this `order('ltc_btc',-1.0)` and portfolio.cash is not calculated properly

* What did you expect to happen?
Assuming this command makes a short on the coin like the documentation, I would expect `portfolio.cash` to stay the same and only when I close the trade I will see `portfolio.cash` changing.

* What happened instead?
My `portfolio.cash` actually increases and is now `199.76681618174086`.

## Reproduction Steps

1. On `handle_data` run `order_target_percent('ltc_btc',-1.0)`

## What steps have you taken to resolve this already?
It seems that the `portfolio.cash` assumes I am selling LTC in an amount value of 100% of my portfolio, so it makes sense I now have something close to 200 in `portfolio.cash`.
However, the docs says that this shorts the coin, so I am a bit confused.

# Anything else?

Is there a different way to short a coin?

Sincerely

**Comment by AvishaiW** [comment]
Hi @eranhirs, The order you specify sells ltc. Currently, we don't have the option of shorting an asset. It would be helpful if you can add a link to the location in the docs where it says that the order is defined as a short and we will modify it. Thanks!

**Comment by eranhirs** [comment]
Thanks @AvishaiW !

Here are the places I run into it in the docs:
1. https://enigma.co/catalyst/beginner-tutorial.html?highlight=short `"(if negative, order() will sell/short assets)."`

2. I saw it in my local catalyst in `def order` in `algorithm.py`, but I see it has already been changed when I look on github.

**Comment by AvishaiW** [comment]
Thanks!
fixed on develop.
