### ISSUE TITLE
Catalyst doesn't detect the filling of certain orders on Poloniex

### ISSUE THREAD

**Issue by sam31415** [enigmampc/catalyst#384]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux 4.13.0-39-generic #44-Ubuntu SMP Thu Apr 5 14:25:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 3.6.4 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages: 
aiodns                    1.1.1                     <pip>                      
aiohttp                   3.1.3                     <pip>                      
alembic                   0.9.9                     <pip>                      
async-timeout             2.0.1                     <pip>                      
attrdict                  2.0.0                     <pip>                      
attrs                     17.4.0                    <pip>                      
bcolz                     1.1.2            py36h00f5784_0                      
bcolz                     1.2.1                     <pip>                      
bokeh                     0.12.14                  py36_0                      
boto3                     1.7.4                     <pip>                      
botocore                  1.10.4                    <pip>                      
Bottleneck                1.2.1                     <pip>                      
bzip2                     1.0.6                h9a117a8_4                      
ca-certificates           2017.08.26           h1d4fec5_0                      
cchardet                  2.1.1                     <pip>                      
ccxt                      1.13.1                    <pip>                      
certifi                   2018.1.18                py36_0                      
certifi                   2018.4.16                 <pip>    
chardet                   3.0.4                     <pip>                      
click                     6.7              py36h5253387_0                      
cloudpickle               0.5.2                    py36_1                      
configparser              3.5.0                     <pip>                      
contextlib2               0.5.5                     <pip>                      
cycler                    0.10.0                    <pip>                      
cyordereddict             1.0.0                     <pip>                      
cython                    0.27.3           py36h1860423_0                      
Cython                    0.28.2                    <pip>                      
cytoolz                   0.9.0.1          py36h14c3975_0                      
dask                      0.17.2                   py36_0                      
dask-core                 0.17.2                   py36_0                                                    
decorator                 4.3.0                     <pip>                      
distributed               1.21.4                   py36_0                      
docutils                  0.14                      <pip>                                                                          
empyrical                 0.2.1                     <pip>                      
enigma-catalyst           0.5.14                    <pip>                      
eth-abi                   1.0.0                     <pip>                      
eth-account               0.1.0a2                   <pip>                      
eth-hash                  0.1.2                     <pip>                      
eth-keyfile               0.5.1                     <pip>                      
eth-keys                  0.2.0b3                   <pip>                      
eth-rlp                   0.1.0                     <pip>                      
eth-utils                 1.0.2                     <pip>                      
hdf5                      1.10.1               h9caa474_1                      
heapdict                  1.0.0                    py36_2                      
hexbytes                  0.1.0                     <pip>                      
idna                      2.6                       <pip>                      
idna-ssl                  1.0.1                     <pip>                      
intel-openmp              2018.0.0                      8                      
intervaltree              2.1.0                     <pip>                      
jinja2                    2.10             py36ha16c418_0                      
jmespath                  0.9.3                     <pip>                      
kiwisolver                1.0.1                     <pip>                      
libedit                   3.1                  heed3624_0                      
libffi                    3.2.1                hd88cf55_4                      
libgcc-ng                 7.2.0                hdf63c60_3                      
libgfortran-ng            7.2.0                hdf63c60_3              
libstdcxx-ng              7.2.0                hdf63c60_3                      
locket                    0.2.0            py36h787c0ad_1                      
Logbook                   1.3.3                     <pip>                      
lru-dict                  1.1.6                     <pip>                      
lxml                      4.2.1                     <pip>                      
lzo                       2.10                 h49e0be7_2                      
Mako                      1.0.7                     <pip>                      
markupsafe                1.0              py36hd9260cd_1                      
matplotlib                2.2.2                     <pip>                      
mkl                       2018.0.2                      1                      
mpld3                     0.3                       <pip>                      
msgpack-python            0.5.5            py36h6bb024c_0                                                    
multidict                 4.2.0                     <pip>                      
multipledispatch          0.5.0                     <pip>                      
ncurses                   6.0                  h9df7e31_2                                                                          
networkx                  2.1                       <pip>                      
numexpr                   2.6.4            py36hc4a3f9a_0                      
numpy                     1.14.2           py36hdbf6ddf_0                      
numpy                     1.14.2                    <pip>                      
openssl                   1.0.2n               hb7f436b_0                      
packaging                 17.1                     py36_0                      
pandas                    0.22.0           py36hf484d3e_0                      
pandas                    0.19.2                    <pip>                      
pandas-datareader         0.6.0                     <pip>                      
partd                     0.3.8            py36h36fd896_0                      
patsy                     0.5.0                    py36_0                      
patsy                     0.5.0                     <pip>                      
pip                       10.0.1                    <pip>                      
pip                       9.0.1                    py36_5                      
psutil                    5.4.3            py36h14c3975_0                      
pycares                   2.3.0                     <pip>                      
pycryptodome              3.6.1                     <pip>                      
pyparsing                 2.2.0            py36hee85983_1                      
pytables                  3.4.2            py36h3b5282a_2                      
python                    3.6.4                hc3d631a_3                      
python-dateutil           2.7.0                    py36_0                      
python-dateutil           2.7.2                     <pip>                      
python-editor             1.0.3                     <pip>                      
pytz                      2018.4                    <pip>                      
pytz                      2018.3                   py36_0                      
pyyaml                    3.12             py36hafb9ca4_1                      
readline                  7.0                  ha6073c6_4                      
redo                      1.6                       <pip>                      
requests                  2.18.4                    <pip>                      
requests-file             1.4.3                     <pip>                      
requests-ftp              0.3.1                     <pip>                      
requests-toolbelt         0.8.0                     <pip>                      
rlp                       0.6.0                     <pip>                      
s3transfer                0.1.13                    <pip>                      
scipy                     1.0.1                     <pip>                                                    
scipy                     1.0.0            py36hbf646e7_0                      
setuptools                39.0.1                    <pip>                      
setuptools                38.5.1                   py36_0                                                                          
six                       1.11.0           py36h372c433_1                      
six                       1.10.0                    <pip>                      
sortedcontainers          1.5.9                    py36_0                      
SQLAlchemy                1.2.6                     <pip>                      
sqlite                    3.22.0               h1bed415_0                      
statsmodels               0.8.0            py36h8533d0b_0                      
statsmodels               0.8.0                     <pip>                      
tabulate                  0.8.2                     <pip>                      
tblib                     1.3.2            py36h34cf8b6_0                      
tk                        8.6.7                hc745277_3                      
toolz                     0.9.0                    py36_0                      
tornado                   5.0                      py36_0                      
urllib3                   1.22                      <pip>                      
web3                      4.1.0                     <pip>                      
websockets                4.0.1                     <pip>                      
wheel                     0.30.0           py36hfd4bba0_1                      
wrapt                     1.10.11                   <pip>                      
xz                        5.2.3                h55aa19d_2                      
yaml                      0.1.7                had09818_2                      
yarl                      1.1.0                     <pip>                      
zict                      0.1.3            py36h3a3bf81_0                      
zlib                      1.2.11               ha838bed_2                      

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

This issue is very similar to  #309, which is marked as fixed. A order is placed, filled on the exchange, but catalyst considers the order as open. The order was placed using the `order` function. It is a limit order with a price sufficiently far from the current price to act as a market order. (Poloniex does not accept market orders.)

In the algo log, I see:
```
[2018-07-02 20:41:03.353228] INFO: exchange_blotter: poloniex order 158888747322 for xrp_btc still open after 0 days 00:00:50.353013                           
[2018-07-02 20:42:01.240536] INFO: exchange_blotter: poloniex order 158888747322 for xrp_btc still open after 0 days 00:01:48.240386                           
[2018-07-02 20:43:00.697644] INFO: exchange_blotter: poloniex order 158888747322 for xrp_btc still open after 0 days 00:02:47.697468                           
[2018-07-02 20:44:00.947044] INFO: exchange_blotter: poloniex order 158888747322 for xrp_btc still open after 0 days 00:03:47.946876                           
[2018-07-02 20:45:00.142445] INFO: exchange_blotter: poloniex order 158888747322 for xrp_btc still open after 0 days 00:04:47.138227

[...]

[2018-07-02 22:16:00.701239] INFO: exchange_blotter: poloniex order 158888747322 for xrp_btc still open after 0 days 01:35:47.701092                           
[2018-07-02 22:17:00.269116] INFO: exchange_blotter: poloniex order 158888747322 for xrp_btc still open after 0 days 01:36:47.268943                           
[2018-07-02 22:18:00.356150] INFO: exchange_blotter: poloniex order 158888747322 for xrp_btc still open after 0 days 01:37:47.355998

[...]
``` 
On the exchange, I see the filled order:
``` 
XRP/BTC | Buy | Exchange | 0.00007410 | 36.01048174 | 0.07202096 XRP (0.2%) | 0.00266837 BTC | 2018-07-02 20:40:13
``` 
Note that previously, there was a suspicion about this problem arising when market orders were filled against several limit orders. But this particular order got filled at a single price.

Also, note Catalyst is unusable on Poloniex as long as this type of error arise. Given the impossibility to modify the algorithm state #312, the only solution is to stop the algo at manually close all the positions.

* What did you expect to happen?
I expect Catalyst to detect filled orders.

* What happened instead?
It did not detect this particular order.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Send orders to Poloniex.
2. Observe whether Catalyst fails to detect their filling.
...

Sincerely,
Samuel

**Comment by lenak25** [comment]
Thanks for reporting this, we will investigate.

**Comment by sam31415** [comment]
It also failed to detect the filling of two sell orders, in particular a sell order for xrp_btc. Then shortly after the order was actually filled, it detected the lower balance which is then recorded as a complete loss
```
[2018-07-03 16:01:20.227945] WARNING: Exchange: detected lower balance for xrp_btc on poloniex: 1.45e-05 < 35.90588550762, updating position amount
```
The order was filled on the exchange
```
XRP/BTC | Sell | Exchange | 0.00007539 | 35.90588550 | 0.00000541 BTC (0.2%) | 0.00270153 BTC | 2018-07-03 16:00:17
```
Am I really the only person experiencing this on Poloniex?

**Comment by lenak25** [comment]
@sam31415 and @SOGorman35, 
I've tried to reproduce this while creating buy and sell limit orders of `xrp_btc` on Poloniex with no success. 
Could you please try to provide more information on the scenarios in which catalyst becomes inconsistent with the orders state on the exchange?

**Comment by sam31415** [comment]
It's hard to tell. Many order are treated correctly, but suddenly one or two do not get detected. I don't think this is specific to certain pairs, but it is definitely specific to Poloniex. 

Could it be an issue with CCXT? The following issues display the opposite problem we're having: orders detected as filled when they are not:
https://github.com/ccxt/ccxt/issues/1801
https://github.com/ccxt/ccxt/issues/2275
#178 seems related as well.

**Comment by lenak25** [comment]
OK, thanks for the input, we will continue investigating.

**Comment by AvishaiW** [comment]
Hi, We were able to replicate this issue and we added a fix which will be added to the next release.

**Comment by sam31415** [comment]
@AvishaiW  Thanks!

**Comment by sam31415** [comment]
It looks like this issue is not fixed. I got exactly the same problem today, with Catalyst 0.5.17.
I'm getting
```
[2018-09-01 17:11:02.486388] INFO: exchange_blotter: poloniex order 189977130752 for ltc_btc still open after 0 days 00:00:49.486176                                       
[2018-09-01 17:12:01.318318] INFO: exchange_blotter: poloniex order 189977130752 for ltc_btc still open after 0 days 00:01:48.318171                                       
[2018-09-01 17:13:00.805389] INFO: exchange_blotter: poloniex order 189977130752 for ltc_btc still open after 0 days 00:02:47.805237                                       
[2018-09-01 17:14:01.080885] INFO: exchange_blotter: poloniex order 189977130752 for ltc_btc still open after 0 days 00:03:48.080717                                                                                                
[2018-09-01 17:15:00.406735] INFO: exchange_blotter: poloniex order 189977130752 for ltc_btc still open after 0 days 00:04:47.406593
[...]
```
while the order has been filled on Poloniex:
`LTC/BTC | Buy | Exchange | 0.00920230 | 0.28423696 | 0.00056847 LTC (0.2%) | 0.00261563 BTC | 2018-09-01 17:10:13`

**Comment by SOGorman35** [comment]
I restarted live trading today for the first time in  quite awhile and this problem still exists.

**Comment by magick93** [comment]
We're also facing the same issue. 

Perhaps we can get this issue reopened?
