### ISSUE TITLE
Order_target_percent() problem using portfolio.value

### ISSUE THREAD

**Issue by eranhirs** [enigmampc/catalyst#385]
Dear Catalyst Maintainers,

# Description of Issue

I think `order_target_percent()` should not be simply using `portfolio.value` for the calculations.

Here is why:
1. initialize - `portfolio.value` and `portfolio.cash` are both 100 BTC.
2. handle - Time is 01:00. Run `order_target_percent(symbol('ltc_btc'), 1.0)`.
3. handle - Time is 02:00, Litecoin price went up by 10%. Run `order_target_percent(symbol('ltc_btc'), 1.0)`.

* What did you expect to happen?
I did not expect anything to happen, because all of my portfolio is invested in LTC

* What happened instead?
`portfolio_value` is now 110 BTC, so it buys more LTC.
However, there is no actual BTC to buy this extra LTC because the position is still open.

## What steps have you taken to resolve this already?

I already implemented locally a change to `calculate_order_percent_amount` in `algorithm.py` to use `portfolio.cash` and it makes more sense to me.

# Anything else?

If it isn't the original idea of `order_target_percent` and it doesn't make sense changing it, I still think there is a need for a method that uses `portfolio.cash`.
What are your thoughts?

Sincerely

**Comment by AvishaiW** [comment]
Hi @eranhirs how come was this issue closed?

**Comment by eranhirs** [comment]
@AvishaiW The original example I gave was wrong, I now understand it needs to be using 2 coins
1. Buy `order_target_percent(symbol('ltc_btc'), 1.0)`
2. Buy `order_target_percent(symbol('eth_btc'), 1.0)`
It will buy both coins although it doesn't have the cash to buy them.
I would love to have a method that takes into consideration the `portfolio.cash` not `portfolio.value`.

I thought I should open a new issue instead of editing.
