### ISSUE TITLE
 Catalyst Market Coverage Overview is empty

### ISSUE THREAD

**Issue by wegamekinglc** [enigmampc/catalyst#386]
The linked page in the README.md file for  Catalyst Market Coverage Overview is an empty page. Is this a wrong link?

**Comment by lenak25** [comment]
Hi @wegamekinglc , thanks for reporting this. 

We are aware of the problem in the status page and it should be resolved ASAP.

Thanks,
Lena

**Comment by lenak25** [comment]
The status page was fixed.
