### ISSUE TITLE
Spread calculation looks wrong for TradingPairFixedSlippage

### ISSUE THREAD

**Issue by lucasgadams** [enigmampc/catalyst#390]
Per the doc string of TradingPairFixedSlippage in https://github.com/enigmampc/catalyst/blob/master/catalyst/exchange/exchange_blotter.py : 

```   
 """
    Model slippage as a fixed spread.
    Parameters
    ----------
    spread : float, optional
        spread / 2 will be added to buys and subtracted from sells.
    """
```

but in the __init__ function:
```
    def __init__(self, spread=0.0001):
        super(TradingPairFixedSlippage, self).__init__()
        self.spread = spread
```

And then when self.spread is used in def process_order:
```    
def process_order(self, data, order):
        price = data.current(order.asset, 'close')

        if order.amount > 0:
            # Buy order
            adj_price = price * (1 + self.spread)
        else:
            # Sell order
            adj_price = price * (1 - self.spread)

        log.debug('added slippage to price: {} => {}'.format(price, adj_price))

        return adj_price, order.amount
```

Should spread by divided by 2 somewhere?

**Comment by lenak25** [comment]
Hi @lucasgadams , thanks for bringing this up.
This is indeed a bit confusing.. The intention was to to define a fixed slippage which will be used to determine the end price. The name `spread` is less suitable to define this fixed slippage and the documentation is not correct as well.
We will address this.
Thanks again.

**Comment by lenak25** [comment]
Was added to release 0.5.16
