### ISSUE TITLE
Execution duration of order on minute frequency

### ISSUE THREAD

**Issue by reinka** [enigmampc/catalyst#40]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment
* Operating System: macOS Sierra
* Python Version: Python 2.7.13 :: Continuum Analytics, Inc.
* Python Bitness: 64
* How did you install Catalyst: followed docs instruction for conda installation, the one without the `.yml` file
* Python packages: 
alembic                   0.9.6                     <pip>
backports.functools-lru-cache 1.4                       <pip>
bcolz                     0.12.1                    <pip>
Bottleneck                1.2.1                     <pip>
certifi                   2017.7.27.1               <pip>
certifi                   2016.2.28                py27_0

chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.1                    <pip>
decorator                 4.1.2                     <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.2.dev5                  <pip>
idna                      2.6                       <pip>
intervaltree              2.1.0                     <pip>
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.0                     <pip>
mkl                       2017.0.3                      0

multipledispatch          0.4.9                     <pip>
networkx                  2.0                       <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py27_0

openssl                   1.0.2l                        0

pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
patsy                     0.4.1                     <pip>
pip                       9.0.1                    py27_1

pudb                      2017.1.4                  <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0

python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2017.2                    <pip>
readline                  6.2                           2

requests                  2.18.4                    <pip>
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
scipy                     0.19.1              np113py27_0

setuptools                36.4.0                   py27_1

six                       1.11.0                    <pip>
sortedcontainers          1.5.7                     <pip>
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                        0

statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
TA-Lib                    0.4.10                    <pip>
tables                    3.4.2                     <pip>
tk                        8.5.18                        0

toolz                     0.8.2                     <pip>
urllib3                   1.22                      <pip>
urwid                     1.3.1                     <pip>
wheel                     0.29.0                   py27_0

zlib                      1.2.11                        0

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
## Current behaviour
When running the algorithm on a minute basis I've noticed that it can take quite some time until a placed order gets executed: 

￼
![image](https://user-images.githubusercontent.com/12010921/31737958-761396d0-b449-11e7-9447-8ba4725452f6.png)

Here you can see that even though my limit is set 10% above the current price, it still takes quite some time until the order is being executed (up to >1h):

￼
![image](https://user-images.githubusercontent.com/12010921/31738477-2196e2b8-b44b-11e7-910c-897dee491db0.png)

finally executed:

￼
![image](https://user-images.githubusercontent.com/12010921/31738030-a00c44aa-b449-11e7-92be-665b9d19caa3.png)

Some code parts for creating the logs, in case its good for anything.

￼
![image](https://user-images.githubusercontent.com/12010921/31738066-b9480b20-b449-11e7-94a3-f3b343a7c569.png)

![image](https://user-images.githubusercontent.com/12010921/31738069-bb815914-b449-11e7-88c7-e34399d73886.png)
￼

## Expected behaviour
So if I set an order with such a high buy price I’d expect it to be executed quite quickly. 
Is this expected behaviour or am I doing something wrong?

**Comment by abnera** [comment]
It depends on the volume of that coin at the time of purchase. If no one was buying that coin or is someone had an even higher bid than yours with lots of shares to purchases.

This is more something you should monitor. I doubt is related to execution time.

**Comment by reinka** [comment]
I chose a limit order that was 20% above market price and it still took up to 1h to get executed which made it quite unlikely that it's due to low volume etc.

Also, whatever the reason was this issue disappeared with v0.3. 

However with v0.3 it seemd I'm facing issues when placing sell orders on a minute frequency. Will have to investigate this more before I can come to any conclusion though.

**Comment by fredfortier** [comment]
@reinka There is indeed an issue with sell orders. It will be resolved in version 0.3.4 which we will release very soon.

Your original issue probably had something to do with the commission model pre-0.3.

Please re-open if you are still experiencing issues with v0.3.4.

**Comment by fredfortier** [comment]
Reopening to allow enough time for validation.
