### ISSUE TITLE
403 Error Downloading Data Bundle

### ISSUE THREAD

**Issue by rolo** [enigmampc/catalyst#408]
When attempting to ingest data with the following command:
`catalyst ingest-exchange -x bitfinex -f daily -i btc_usd`

I'm getting an HTTP 403 error on downloading the data bundle:

`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-bitfinex/bitfinex-daily-btc_usd-2013.tar.gz
`
Seems like the AWS S3 permissions are wrong on this file: https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-bitfinex/bitfinex-daily-btc_usd-2013.tar.gz

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BAF02897056585E5</RequestId>
<HostId>
IH6W2Nn/ufHQ43/ZVNN4TV4+z4sPLCxVdBUbQvq6Z19+AXd8rvMwb4Xt3d+m/RFIx0S2ZkPXlY0=
</HostId>
</Error>`

I'm not sure how these are generated. Maybe a step for setting permissions didn't fire?

Thanks.

**Comment by lenak25** [comment]
Thanks for reporting this.
We are looking into this.
In the meantime, please use the following command (retrieve data from 2015, until we fix the other data): 
`catalyst ingest-exchange -x bitfinex -s 2015 -i btc_usd`

Thanks,
Lena

**Comment by rolo** [comment]
That works great - thanks loads.

**Comment by lenak25** [comment]
Fixed at release 0.5.17

**Comment by rolo** [comment]
Wonderful - thanks!

**Comment by zanoo** [comment]
I'm getting this issue again for `https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-binance/binance-minute-btt_bnb-2019-01.tar.gz` on `catalyst ingest-exchange -x binance -f minute`

**Comment by paulplayer** [comment]
I'm also getting this issue again on catalyst ingest-exchange -x binance -f minute
