### ISSUE TITLE
catalyst ingest-exchange hangs randomly

### ISSUE THREAD

**Issue by avolution** [enigmampc/catalyst#414]
Happens randomly.
Maybe on connection-interruptions(have a bad connection at the moment) but there is no Error or so.
Just The Progress-Bar and the Time will not changed anymore.

There should be an Error-Message or an automatic continue when an error occurs

I use catalyst 0.5.18

**Comment by lenak25** [comment]
@avolution, thanks for reporting this.
Have you noticed if this behaviour is unique to a special set of parameters (like an exchange)?
Thanks

**Comment by avolution** [comment]
@special parameter
It was with Bitfinex as the exchange 
otherwise it happen with start and end parameter also without start and end (so whole history)

**Comment by EmbarAlmog** [comment]
Hi @avolution , are you still experiencing this issue?

**Comment by avolution** [comment]
@EmbarAlmog 
I do not working in backtesting at the moment.
So I do not come in touch with it again currently.

Do you was able to reproduce it?

**Comment by avolution** [comment]
@EmbarAlmog :
I will do

**Comment by avolution** [comment]
@EmbarAlmog :
I am now back to that topic and it failed again many times.

For reproduction you can use something like this:
https://nshipster.com/network-link-conditioner/
Then you can setup a bad connection and it should fail.

A logging with more informations would be also great as an improvement.
There is this “—verbose” mode but there it will be only one entry per pair instead of all in one progress bar.

**Comment by avolution** [comment]
Here an output of a failed execution
Maybe it will help to find the reason

First i have cleared the env with

catalyst clean-exchange -x bitfinex

Then the execution


user$ catalyst ingest-exchange -x bitfinex -f minute --verbose
Trying to ingest exchange bundle bitfinex...
    [====================================]  Ingesting minute price data for agi_btc on bitfinex:  100%             
    [====================================]  Ingesting minute price data for agi_eth on bitfinex:  100%             
    [====================================]  Ingesting minute price data for agi_usd on bitfinex:  100%             
    [====================================]  Ingesting minute price data for aid_btc on bitfinex:  100%             
    [====================================]  Ingesting minute price data for aid_eth on bitfinex:  100%    

...

    [====================================]  Ingesting minute price data for bat_btc on bitfinex:  100%             
    [====================================]  Ingesting minute price data for bat_eth on bitfinex:  100%             
    [====================================]  Ingesting minute price data for bat_usd on bitfinex:  100%             
    [===================                 ]  Ingesting minute price data for bch_btc on bitfinex:   53%  0d 00:00:22


**** Now nothing happens anymore *****

^C

Aborted!



------------

**Comment by AvishaiW** [comment]
Hi @avolution,
are you still experiencing this issue? 
If so, please feel free to reopen..
Thanks!
