### ISSUE TITLE
Old cached Account values in live mode (bitfinex)

### ISSUE THREAD

**Issue by avolution** [enigmampc/catalyst#417]
In live mode(live=true,simulate_orders=true|false) I have dicovered that old values from previous states of the account will be used for example:
cash, old positions etc.

In this mode the states will be fetched live from the exchange so maybe a problem with cached API requests?

-----------

tested this with bitfinex as exchange
and catalyst version 0.5.18

**Comment by lenak25** [comment]
Hi @avolution , it seems that you are describing the [algorithm's state saving mechanism in live mode. ](https://enigma.co/catalyst/live-trading.html#algorithm-state)

**Comment by avolution** [comment]
Ah okay that explains this behaviour ...
Thanks! :)
