### ISSUE TITLE
poloniex get request crash

### ISSUE THREAD

**Issue by ytkang** [enigmampc/catalyst#420]
enigma-catalyst version 0.5.18

poloniex GET https://poloniex.com/public?period=900&start=1532679300&command=returnChartData&end=1532859300&currencyPair=BTC_DASH HTTPSConnectionPool(host='poloniex.com', port=443): Read timed out. (read timeout=10)

If poloniex give timeout, then it should be retried instead of crashed.

**Comment by lenak25** [comment]
Hi @ytkang ,

In order to address this issue, please provide the following information:
1. Algorithm's parameters
2. Description of the scenario causing this error

Thanks,

Lena

**Comment by ytkang** [comment]
@lenak25 
Yes,
It caused when it tries to get historical data from poloniex

`target_asset = symbol("DASH_BTC")
target_history = data.history(target_asset, fields="close",
                                      bar_count=200, frequency='15T')`

It is not happened every time. It causes some time. because it is timeout.

**Comment by avolution** [comment]
I think its the same problem as in #422 

My solution for now is to demonize the algo as a service which automatic restart when the process is crashed.
When you have defined a unique Namespace the algostate will be restored(Positions + content of context.state)
-> https://enigma.co/catalyst/live-trading.html#algorithm-state

**Comment by ytkang** [comment]
@lenak25 yeah, it seems same issue. I will close mine

**Comment by lenak25** [comment]
Hi @ytkang,

I am not sure it is related to #422. 
There is a retry mechanism for retrieving `history` data but perhaps it should be improved. 
I am reopening this, we will investigate. 
If you have the entire trace, it could be helpful.

Thanks,
Lena

**Comment by ytkang** [comment]
@lenak25 Great! Thanks!

**Comment by lenak25** [comment]
Fixed at release 0.5.19
