### ISSUE TITLE
Get order by id does not work for all exchanges (e.g. Kucoin)

### ISSUE THREAD

**Issue by red-eagle-eye** [enigmampc/catalyst#423]
Dear Catalyst Maintainers,

# Description of Issue
* What did you expect to happen?
API method `TradingAlgorithm::get_order` to work for exchanges that require the order direction as a parameter (SELL or BUY) (e.g. Kucoin) 

* What happened instead?
The `get_order` method fails when getting order from kucoin.

Here is how you can reproduce this issue on your machine:
Just place any order on Kucoin and try to get it by `id`

## What steps have you taken to resolve this already?
Add additional argument **params** to the `get_order` method signature:
`def get_order(self, order_id, exchange_name, symbol=None, params={})`
This allows the client to optionally specify additional parameters required by the exchange (similiar to the `cancel_order` signature)

Cheers,
Red Eagle

**Comment by lenak25** [comment]
Thanks @red-eagle-eye for reporting.
What catalyst version and CCXT version are you using?

**Comment by EmbarAlmog** [comment]
Thanks for reporting and suggesting the workaround. It was added to our develop branch and will be included in our next release. 
An example of using `get_order` with KuCoin, for future reference:
```get_order('1234567890' , 'xlm_btc', params={'type': 'BUY'})``` 

thanks again, 
Embar

**Comment by lenak25** [comment]
Added to release 0.5.19
