### ISSUE TITLE
missing history data

### ISSUE THREAD

**Issue by ddimkin** [enigmampc/catalyst#434]
Trying to run my strategy on latest data, but bitfinex and poloniex return same error for the same period.

```
PricingDataNotLoadedError: Missing data for bitfinex ltc_usd in date range [2018-08-01 00:00:00+00:00 - 2018-08-05 00:00:00+00:00]
Please run: `catalyst ingest-exchange -x bitfinex -f daily -i ltc_usd`. See catalyst documentation for details.
```

Tried to run 
`catalyst clean-exchange -x bitfinex`
and then run
`catalyst ingest-exchange -x bitfinex -f daily -i ltc_usd`
but nothing changed.
Thx.

**Comment by lenak25** [comment]
Hi @ddimkin ,

I wasn't able to reproduce the issue you are describing. 
Does is still occurring (after a clean ingest)? If so, what causes this error (what API call)?

Thanks,
Lena

**Comment by ddimkin** [comment]
@lenak25 
For some reason it disappears now.
Sorry for being worried. 
**Thx!**
