### ISSUE TITLE
Is there any way to get data from several exchanges?

### ISSUE THREAD

**Issue by ddimkin** [enigmampc/catalyst#439]
**Hi Catalyst Maintainers!**

I created one strategy and realized that it would be nice to have aggregated historical data from several exchanges. In reality we have only `Init` method where I must specify exchange name and then history returns only this exchange-related data.
Any ideas or suggestions?

Sincerely,
`ddimkin`

**Comment by SOGorman35** [comment]
I haven't tried it myself, but if you look at the arbitrage_from_interface.py file in the examples, it shows how to do this.
