### ISSUE TITLE
[Question] Is there a mechanism real-time ingesting exchange?

### ISSUE THREAD

**Issue by traeper** [enigmampc/catalyst#440]
Dear Catalyst Maintainers,

I wonder if there is a mechanism ingesting ohlcv data from a exchange frequently.

Requirements are below.
* ingest ohlcv data every minute from dbms crawled from some exchanges.
* nearly real-time backtest. (Maybe similar or same with paper trading)
  * ex) run backtest from X to 18-8-15 13:59:00 (Suppose current time is  18-8-15 14:00:00)

Can Catalyst support the requirements?
I'll be trying to ingest all coin data every minute by running shell script minutely.

Sincerely,
`traeper`

**Comment by traeper** [comment]
found the bundle example in git clode. close this issue

**Comment by LiuXingMing** [comment]
Can you list the demo path? Thank you very much!

**Comment by traeper** [comment]
@LiuXingMing 

I just found some codes that may releated to bundle. 
these bundle codes are using directly http api of a exchange.

1. curate(??) : {catalyst pacakge}/curate/poloniex.py
2. bundle :  {catalyst pacakge}/data/bundles/{many-exchange}.py
