### ISSUE TITLE
unable to ingest data through both online and custom data local

### ISSUE THREAD

**Issue by studyquant** [enigmampc/catalyst#441]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ Python 2.7 
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`) pip 
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
unable to ingest data 
I have download example CSV file from https://github.com/enigmampc/catalyst/issues/65
* What did you expect to happen?
* What happened instead?
(catalyst) F:\catalyst\bittrex_bat_eth.csv>catalyst ingest-exchange -x bittrex --csv ~/Data/bittre
x_bat_eth.csv -f minute
Trying to ingest exchange bundle bittrex...
[2018-08-18 17:30:54.679000] INFO: exchange_bundle: ingesting csv file: ~/Data/bittrex_bat_eth.csv
then ! it stops forever 

For online download.. is it means that it need to pay ETH to subscriber data and download online? 

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by lenak25** [comment]
Thanks for the information @studyquant .

Regarding the use of the marketplace: yes, Python 3 is required and unfortunately there is indeed an issue with the current conda yml file used in windows as discussed at #407.
We are addressing this in our next release. In the meantime you can try to use the **still WIP** updated [yml file](https://github.com/enigmampc/catalyst/blob/develop/etc/python3.6-environment-windows.yml) created for windows on our develop branch and let us know if you observe any issues.
Regarding the CSV ingestion, could you supply more information on the data, its size so we could try to reproduce what you have experienced.

Thanks,

Lena

**Comment by lenak25** [comment]
@studyquant, the windows issue was resolved: a new Python 3.6 environment yml file for windows can be found [here](ttps://github.com/enigmampc/catalyst/blob/master/etc/python3.6-environment-windows.yml).
If you are still experiencing an issue with the csv ingestion, please provide more information so we could try to reproduce.

**Comment by studyquant** [comment]
@lenak25  where  i can find it ?

**Comment by lenak25** [comment]
@studyquant , sorry for that, the link was erroneous, I've updated the previous message.

Thanks

**Comment by lenak25** [comment]
@studyquant , I am closing this. 
If you are still experiencing an issue with the csv ingestion, please reopen and provide more information so we could reproduce this.
