### ISSUE TITLE
Position object does not have time held attribute.

### ISSUE THREAD

**Issue by demontamer** [enigmampc/catalyst#446]
Dear Catalyst Maintainers,

This is just an enhancement suggestion/help needed. Say, I like to close positions after holding them for x amount of time. At the moment the position object doesn't have a similar attribute to get this information. I am aware I could track when the order was created but this depends on weather the order is still open or if it gets filled the same time it was created, which isn't always the same. 

We have get_open_orders and maybe need get_filled_orders since time x, but less work if included in position object instead.  
For the moment I think I have no choice but to track when I execute a buy order. Or do you have a better suggestion? 

...

Sincerely,
`@demontamer`

**Comment by EmbarAlmog** [comment]
Hi @demontamer, thank you for opening this issue.  
Each `Position` object saves the calculated amount of the base currency from all your orders. That means that if you buy X units of base currency and sell Y units of base currency the position will hold X-Y units. If you wish to see the history that led to the value of this specific `Position` it will require saving all the filled orders which led to the current amount. So its not very clear if the information that you request should be held (and how) within the `Position` itself.
Currently you have the option to access the dictionary of all the orders created during the algorithm run in `context.blotter.orders`. You can manually calculate the estimated time in which the order was filled (please note that an order can be filled in phases) by tracking its state.

Thanks, Embar
