### ISSUE TITLE
historical minutes data missing [binance: eth_btc]

### ISSUE THREAD

**Issue by FWangTrading** [enigmampc/catalyst#447]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 7
* Python Version: 3.6.5
* Python Bitness: 64
* How did you install Catalyst: pip
* Python packages: 
aiodns==1.1.1
aiohttp==3.0.1
alembic==0.9.7
async-timeout==2.0.1
attrdict==2.0.0
attrs==18.1.0
bcolz==1.2.1
boto3==1.5.27
botocore==1.8.50
Bottleneck==1.2.1
cchardet==2.1.1
ccxt==1.12.131
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0.1
decorator==4.3.0
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.18
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-utils==1.0.3
hexbytes==0.1.0
idna==2.6
idna-ssl==1.1.0
intervaltree==2.1.0
jmespath==0.9.3
kiwisolver==1.0.1
Logbook==0.12.5
lru-dict==1.1.6
lxml==4.2.3
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.2.2
multidict==4.3.1
multipledispatch==0.4.9
networkx==2.1
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.6.0
parsimonious==0.8.0
patsy==0.5.0
psutil==5.4.6
pycares==2.3.0
pycryptodome==3.6.4
pyparsing==2.2.0
pypiwin32==223
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2016.4
pywin32==223
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==1.0.1
s3transfer==0.1.13
scipy==1.0.0
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.2
statsmodels==0.8.0
tables==3.4.2
toolz==0.9.0
urllib3==1.22
web3==4.2.1
websockets==6.0
wrapt==1.10.11
yarl==1.1.0

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
binance:eth_btc historical data is missing from 2018-7-23 to 2018-1-1

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. catalyst ingest-exchange -x binance -f minute -i eth_btc
2. `price = data.history( symbol('eth_btc', 'binance'), 'price', bar_count = 1000, frequency = '1T',)
print(price)`
...
...

# Anything else?

...

Sincerely,
Frank

**Comment by lenak25** [comment]
Hi Frank,

I wasn't able to reproduce this issue.
Could you please clean the ingested data using `catalyst clean-exchange -x binance` and try to ingest again?

Thanks,

Lena

**Comment by FWangTrading** [comment]
Thanks, @lenak25 . Problem fixed after cleaning bundles.
