### ISSUE TITLE
Feature request: API-key/secret as parameter 

### ISSUE THREAD

**Issue by avolution** [enigmampc/catalyst#452]
According to https://enigma.co/catalyst/live-trading.html#authentication you have to set up the api-key secret in a json file.
So you can setup only one api-key per installation

Thats limits you to only run only one algorithm at once because otherwise you get nonce errors from the exchanges.
->> ccxt.base.errors.InvalidNonce: bitfinex {"message":"Nonce is too small."}

Would be nice to have the ability to pass the api in run_algoritm for example.

(or is there another way at the moment to override the api-key in initialize for example?)

**Comment by avolution** [comment]
Okay there already is an undocumented parameter(auth_alias) for that

https://github.com/enigmampc/catalyst/commit/e688783931a64ccfa8ee371892dee927caecb042

**Comment by avolution** [comment]
Usage described here:
https://github.com/enigmampc/catalyst/issues/60#issuecomment-359106604

**Comment by avolution** [comment]
(This should be documented)

**Comment by lenak25** [comment]
Thanks @avolution. Have you looked at the `run_algorithm` [API reference](https://enigma.co/catalyst/appendix.html#catalyst.run_algorithm)?

**Comment by avolution** [comment]
Alright thx.
But an example in the "live trading" section would be also good to be added.

I also tried it with this format from the Api reference
for example
auth_aliases="bitfinex,auth2"

but this is not working
I get api key not found errors when I do this

It is working in the format of the comment https://github.com/enigmampc/catalyst/issues/60#issuecomment-359106604:

--->
auth_aliases=dict(bitfinex='auth2')

**Comment by lenak25** [comment]
Hi @avolution , 

> But an example in the "live trading" section would be also good to be added.

Thanks for the feedback. 

> I also tried it with this format from the Api reference
for example
auth_aliases="bitfinex,auth2"
but this is not working

Both options should work. Could you please provide more info?

Thanks,

Lena

**Comment by lenak25** [comment]
Hi @avolution 

> But an example in the "live trading" section would be also good to be added.

Was added, thanks for the suggestion.

> I also tried it with this format from the Api reference
> for example
> auth_aliases="bitfinex,auth2"
> but this is not working

If you still experience this issue, please reopen this (+ share more info).

Thanks,

Lena
