### ISSUE TITLE
Binance data.current and data.history return different prices

### ISSUE THREAD

**Issue by demontamer** [enigmampc/catalyst#453]
Dear Catalyst Maintainers,

on binance these two statements should return the same price?
` X_price = data.current(X,'close')`
` test = data.history(X,bar_count=1,fields='close'
                                   ,frequency='1T')`

please check because they return different prices for me.

FYI I am simulating with --data-frequency minute
...
thanks
Sincerely,
`@demontamer`

**Comment by lenak25** [comment]
Hi @demontamer , thanks for bringing this up. This is indeed an issue, which was discussed at #392 . 
We fixed it on develop branch which will be included in our next release.
