### ISSUE TITLE
Number of shorts/longs and number of transactions are differ

### ISSUE THREAD

**Issue by lamres** [enigmampc/catalyst#454]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: MacOS
* How did you install Catalyst: conda

# Name                    Version                   Build  Channel
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.9.7                     <pip>
appdirs                   1.4.3                      py_1    conda-forge
appnope                   0.1.0                    py36_0    conda-forge
asn1crypto                0.24.0                   py36_3    conda-forge
async-timeout             2.0.0                     <pip>
attrdict                  2.0.0                     <pip>
attrs                     17.4.0                    <pip>
attrs                     18.2.0                     py_0    conda-forge
automat                   0.7.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcolz                     1.2.1                     <pip>
blas                      1.1                    openblas    conda-forge
bleach                    2.1.4                      py_1    conda-forge
boto3                     1.5.27                    <pip>
botocore                  1.8.41                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0  
cchardet                  2.1.1                     <pip>
ccxt                      1.17.94                   <pip>
certifi                   2018.1.18                py36_0    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                     <pip>
clangdev                  6.0.1                 default_1    conda-forge
click                     6.7                       <pip>
constantly                15.1.0                     py_0    conda-forge
contextlib2               0.5.5                     <pip>
cryptography              2.2.1                    py36_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
cytoolz                   0.9.0                     <pip>
decorator                 4.3.0                      py_0    conda-forge
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.19                    <pip>
entrypoints               0.2.3                    py36_2    conda-forge
eth-abi                   1.1.1                     <pip>
eth-account               0.2.2                     <pip>
eth-hash                  0.1.3                     <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b3                   <pip>
eth-rlp                   0.1.2                     <pip>
eth-utils                 1.0.3                     <pip>
freetype                  2.9.1                h6debe1e_2    conda-forge
hexbytes                  0.1.0                     <pip>
html5lib                  1.0.1                      py_0    conda-forge
hyperlink                 17.3.1                     py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.6                       <pip>
idna                      2.7                      py36_2    conda-forge
idna-ssl                  1.0.0                     <pip>
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2018.0.0                      8  
intervaltree              2.1.0                     <pip>
ipykernel                 4.9.0                    py36_0    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.1                      py_0    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                     <pip>
jpeg                      9c                   h470a237_1    conda-forge
jsonschema                2.6.0                    py36_2    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter-contrib-core      0.3.3                     <pip>
jupyter-nbextensions-configurator 0.4.0                     <pip>
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
libcxx                    6.0.1                         0    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.35               ha92aebf_1    conda-forge
libsodium                 1.0.16                        0    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
llvm-meta                 6.0.1                         0    conda-forge
llvmdev                   6.0.1                hf8ce74a_2    conda-forge
Logbook                   1.2.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.1.1                     <pip>
Mako                      1.0.7                     <pip>
markupsafe                1.0              py36h470a237_1    conda-forge
matplotlib                2.2.2            py36h0e0179f_2    conda-forge
mistune                   0.8.3            py36h470a237_2    conda-forge
mkl                       2018.0.1             hfbd8650_4  
multidict                 4.1.0                     <pip>
multipledispatch          0.4.9                     <pip>
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   5.9                          10    conda-forge
networkx                  2.1                       <pip>
notebook                  5.6.0                    py36_1    conda-forge
numexpr                   2.6.4                     <pip>
numpy                     1.14.0          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2n                        0    conda-forge
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
pandoc                    2.2.2                hde52d81_1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parsimonious              0.8.0                     <pip>
parso                     0.3.1                      py_0    conda-forge
patsy                     0.5.0                     <pip>
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.1                    py36_1    conda-forge
prometheus_client         0.3.0                      py_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
pyasn1                    0.4.4                      py_0    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycares                   2.3.0                     <pip>
pycparser                 2.18                       py_1    conda-forge
pycryptodome              3.6.1                     <pip>
pygments                  2.2.0                      py_1    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
pysha3                    1.0.2                     <pip>
python                    3.6.4                hc167b69_3  
python-dateutil           2.7.3                      py_0    conda-forge
python-editor             1.0.3                     <pip>
pytz                      2016.4                    <pip>
pytz                      2018.5                     py_0    conda-forge
PyYAML                    3.13                      <pip>
pyzmq                     17.1.2           py36hae99301_0    conda-forge
qt                        5.6.2                h9e3eb04_4    conda-forge
qtconsole                 4.4.1                    py36_1    conda-forge
readline                  7.0                           0    conda-forge
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     1.0.0           py36_blas_openblas_201  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setuptools                38.4.0                   py36_0    conda-forge
setuptools                40.2.0                    <pip>
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.2                     <pip>
sqlite                    3.22.0                        0    conda-forge
statsmodels               0.8.0                     <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                    py36_1    conda-forge
testpath                  0.3.1                    py36_1    conda-forge
tk                        8.6.7                         0    conda-forge
toolz                     0.9.0                     <pip>
tornado                   5.1              py36h470a237_1    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
twisted                   18.7.0           py36h470a237_1    conda-forge
urllib3                   1.22                      <pip>
virtualenv                15.2.0                    <pip>
wcwidth                   0.1.7                      py_1    conda-forge
web3                      4.4.1                     <pip>
webencodings              0.5.1                      py_1    conda-forge
websockets                5.0                       <pip>
wheel                     0.30.0                   py36_2    conda-forge
widgetsnbextension        3.4.1                    py36_0    conda-forge
wrapt                     1.10.11                   <pip>
xz                        5.2.3                         0    conda-forge
yarl                      1.1.0                     <pip>
zeromq                    4.2.5                hfc679d8_5    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
zope.interface            4.5.0            py36h470a237_1    conda-forge

# What I got?

I have a strategy that produces 52 shorts and 52 longs using this code:
    print("Number of shorts: " +  str(np.sum(perf.shorts_count)))
    print("Number of longs: " + str(np.sum(perf.longs_count)))

When I output my transactions I see this:
    for t in perf.transactions:
        if len(t) > 0:
            print(t)

[{'amount': -35.420799093227544, 'dt': Timestamp('2018-08-27 19:33:00+0000', tz='UTC'), 'price': 142.857, 'order_id': 'c0359baaf04345ed99c2c199f217c218', 'commission': 10.120218192122415, 'fee_currency': None, 'is_quote_live': False, 'sid': Trading Pair zec_usd(265391) Exchange: bitfinex, Introduced On: 2016-10-29 00:00:00+00:00, Base Currency: zec, Quote Currency: usd, Exchange Leverage: 1.0, Minimum Trade Size: 0.08 Last daily ingestion: 2018-09-02 00:00:00+00:00 Last minutely ingestion: 2018-09-02 00:00:00+00:00}, {'amount': 0.7419210937066657, 'dt': Timestamp('2018-08-27 19:33:00+0000', tz='UTC'), 'price': 6747.240499999999, 'order_id': '9bbf66c3afac4ea58e4b2676458ab517', 'commission': 10.011840102523818, 'fee_currency': None, 'is_quote_live': False, 'sid': Trading Pair btc_usd(98871) Exchange: bitfinex, Introduced On: 2013-03-31 00:00:00+00:00, Base Currency: btc, Quote Currency: usd, Exchange Leverage: 1.0, Minimum Trade Size: 0.002 Last daily ingestion: 2018-09-02 00:00:00+00:00 Last minutely ingestion: 2018-09-02 00:00:00+00:00}]
[{'amount': 35.420799093227544, 'dt': Timestamp('2018-08-27 20:02:00+0000', tz='UTC'), 'price': 142.42227999999997, 'order_id': '2897563d6df54e44b0e5bcdbec1186da', 'commission': 10.089421932558796, 'fee_currency': None, 'is_quote_live': False, 'sid': Trading Pair zec_usd(265391) Exchange: bitfinex, Introduced On: 2016-10-29 00:00:00+00:00, Base Currency: zec, Quote Currency: usd, Exchange Leverage: 1.0, Minimum Trade Size: 0.08 Last daily ingestion: 2018-09-02 00:00:00+00:00 Last minutely ingestion: 2018-09-02 00:00:00+00:00}, {'amount': -0.7419210937066657, 'dt': Timestamp('2018-08-27 20:02:00+0000', tz='UTC'), 'price': 6739.0542000000005, 'order_id': '17bf094c65e3492781e3f84535a179ae', 'commission': 9.999692925225, 'fee_currency': None, 'is_quote_live': False, 'sid': Trading Pair btc_usd(98871) Exchange: bitfinex, Introduced On: 2013-03-31 00:00:00+00:00, Base Currency: btc, Quote Currency: usd, Exchange Leverage: 1.0, Minimum Trade Size: 0.002 Last daily ingestion: 2018-09-02 00:00:00+00:00 Last minutely ingestion: 2018-09-02 00:00:00+00:00}]
[{'amount': 33.766100013480454, 'dt': Timestamp('2018-08-28 01:39:00+0000', tz='UTC'), 'price': 147.76762, 'order_id': '0e8b4d92670f4b1a882b4d604a86d125', 'commission': 9.97907247134795, 'fee_currency': None, 'is_quote_live': False, 'sid': Trading Pair zec_usd(265391) Exchange: bitfinex, Introduced On: 2016-10-29 00:00:00+00:00, Base Currency: zec, Quote Currency: usd, Exchange Leverage: 1.0, Minimum Trade Size: 0.08 Last daily ingestion: 2018-09-02 00:00:00+00:00 Last minutely ingestion: 2018-09-02 00:00:00+00:00}, {'amount': -0.7193130460618194, 'dt': Timestamp('2018-08-28 01:39:00+0000', tz='UTC'), 'price': 6917.7753, 'order_id': 'dda44c2e209d44faaf46166e6a04f5df', 'commission': 9.952092046028435, 'fee_currency': None, 'is_quote_live': False, 'sid': Trading Pair btc_usd(98871) Exchange: bitfinex, Introduced On: 2013-03-31 00:00:00+00:00, Base Currency: btc, Quote Currency: usd, Exchange Leverage: 1.0, Minimum Trade Size: 0.002 Last daily ingestion: 2018-09-02 00:00:00+00:00 Last minutely ingestion: 2018-09-02 00:00:00+00:00}]
[{'amount': -33.766100013480454, 'dt': Timestamp('2018-08-28 02:02:00+0000', tz='UTC'), 'price': 148.30154999001002, 'order_id': '36bc96e2b7f24993bd8b8d37886dc768', 'commission': 10.015129938233699, 'fee_currency': None, 'is_quote_live': False, 'sid': Trading Pair zec_usd(265391) Exchange: bitfinex, Introduced On: 2016-10-29 00:00:00+00:00, Base Currency: zec, Quote Currency: usd, Exchange Leverage: 1.0, Minimum Trade Size: 0.08 Last daily ingestion: 2018-09-02 00:00:00+00:00 Last minutely ingestion: 2018-09-02 00:00:00+00:00}, {'amount': 0.7193130460618194, 'dt': Timestamp('2018-08-28 02:02:00+0000', tz='UTC'), 'price': 6931.124199999999, 'order_id': '5b90d0fbfc6546ca918b2ad3ef92bfd4', 'commission': 9.971296121869582, 'fee_currency': None, 'is_quote_live': False, 'sid': Trading Pair btc_usd(98871) Exchange: bitfinex, Introduced On: 2013-03-31 00:00:00+00:00, Base Currency: btc, Quote Currency: usd, Exchange Leverage: 1.0, Minimum Trade Size: 0.002 Last daily ingestion: 2018-09-02 00:00:00+00:00 Last minutely ingestion: 2018-09-02 00:00:00+00:00}]

# Question
I have just a few transactions and I see that when I output leverage value on plot.
Why the number of shorts/longs are too high (52 and 52)?

**Comment by lenak25** [comment]
Hi @lamres ,

Let's first start with the definitions:
`longs_count` - the number of positive positions in the portfolio.
`short_count` - the number of negative positions in the portfolio (please note that this part is a little bit tricky since catalyst does not yet support shorting - #415 - so a negative position might be possible in backtest using leverage or in live mode, once you start your algorithm by selling a position that was achieved beforehand).   
So the information you should inspect is the positions data struct and not the transactions data struct.
Looking at the transactions you've attached, they consist of `btc_usd`  and `zec_usd` pairs. As explained before, each pair should at each iteration contribute one unit to either the `longs_count` (if the pair position amount is positive) or to the `shorts_count` (if the pair position amount is negative).

Hope it makes things more clear.

Lena

**Comment by lamres** [comment]
Thanks! It became more clear, now I know that these ones are not the same.
