### ISSUE TITLE
paper trading bitfinex history(window=1440min) are not consistent,so always can not produce open signal and position

### ISSUE THREAD

**Issue by wkpzwy** [enigmampc/catalyst#459]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
     i use bitfinex exchange,when rolling window is 30,it can run normaly.but when i run with history(window=1440) ,the stats.csv are not consistent,so it can not  produce the open signal

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by lenak25** [comment]
@wkpzwy if you still experience this issue, please share the `history` command you are using.
