### ISSUE TITLE
How to know if a symbol is supported in a given exchange

### ISSUE THREAD

**Issue by kooomix** [enigmampc/catalyst#460]
Hi,

The below refers to live trading.

In my algorithms I extract historical data for a list of assets and not for each asset separately. In case there is at least one symbol that is not supported in the exchange, I an error is returned from the data.history without the data of the other supported symbols.

In order to overcome the above issue, I want to fine-tune my assets list, removing those who are not supported to avoid the data.history error.

I was trying to use the "can_trade" method but it seems like it returns "True" also for symbols that are not supported.

An example is "TradingPair(232770 [hsr_btc])" in binance exchange, which "can_trade" returns True even though it is not traded.

So my question is - how can I identify which assets are supported for a given exchange on live trading? Of course, any other idea to be able to overcome the above problem is much appreciated.

Thanks.

**Comment by lenak25** [comment]
Hi @kooomix ,

Are you referring to live / paper trading mode?

Thanks,

Lena

**Comment by kooomix** [comment]
Yes..

**Comment by lenak25** [comment]
Hi @kooomix , 

Thanks for reporting this!

Several observations:
1. The `can_trade` function indeed does not seem to work correctly in live/paper trading. We will need to address this - I've opened a new github issue #462. 
2. An alternative way for getting the required information is by looking at the `TradingPair` object. The `trading_state` attribute of the `TradingPair` class (the object returned from the API function `symbol`) was utilized for **live and paper trading only** in [this commit](https://github.com/enigmampc/catalyst/commit/be6480f1782e72cf44f438fc1f227c2f79d6d9b1) in develop branch and will be included in our next release.  
3. If the only thing interests you is whether a specific trading pair has historical candles (and not whether the trading pair is currently tradable - which is a bit different) you could loop through the trading pair list, requesting historical candles for one pair at a time and wrapping this part with a try-except clause (excepting the `catalyst.exchange.exchange_errors.NoCandlesReceivedFromExchange` exception thrown when an empty candles list is returned).

Thanks,
Lena

**Comment by kooomix** [comment]
Thanks @lenak25 the second solution you offer might be good enough at the moment.
In what time intervals the trading_state is expected to be updated?

**Comment by lenak25** [comment]
Hi @kooomix ,

Was planned to update just now: we have released version 0.5.20 which includes this update.

Thanks for bringing this up.

**Comment by kooomix** [comment]
yes, I started using it already... My question is when this property is being updated? Every time the symbols function is called? Or by the handle_data frequency? Or daily?

Thanks.

**Comment by lenak25** [comment]
Hi @kooomix ,

Sorry for missing your original question: this parameter gets updated once at the beginning of the algorithm run.
