### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'Series'

### ISSUE THREAD

**Issue by qwzfavor** [enigmampc/catalyst#466]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

* Operating System: Windows Server 2008
* Python Version: 3.6.4
* How did you install Catalyst: conda
* Python packages:

> aiodns                    1.1.1                     <pip>
> aiohttp                   3.0.1                     <pip>
> alembic                   0.9.7                     <pip>
> async-timeout             2.0.0                     <pip>
> attrdict                  2.0.0                     <pip>
> attrs                     17.4.0                    <pip>
> bcolz                     1.2.1                     <pip>
> blas                      1.0                         mkl
> boto3                     1.5.27                    <pip>
> botocore                  1.8.50                    <pip>
> Bottleneck                1.2.1                     <pip>
> ca-certificates           2017.08.26           h94faf87_0
> cchardet                  2.1.1                     <pip>
> ccxt                      1.17.94                   <pip>
> certifi                   2018.1.18                py36_0    conda-forge
> chardet                   3.0.4                     <pip>
> click                     6.7                       <pip>
> contextlib2               0.5.5                     <pip>
> cycler                    0.10.0                     py_1    conda-forge
> cyordereddict             1.0.0                     <pip>
> Cython                    0.27.3                    <pip>
> cytoolz                   0.9.0.1                   <pip>
> decorator                 4.3.0                     <pip>
> docutils                  0.14                      <pip>
> empyrical                 0.2.1                     <pip>
> enigma-catalyst           0.5.20+1.g90d9e4e2           <pip>
> enigma-catalyst           0.5.20                    <pip>
> eth-abi                   1.2.0                     <pip>
> eth-account               0.2.3                     <pip>
> eth-hash                  0.2.0                     <pip>
> eth-keyfile               0.5.1                     <pip>
> eth-keys                  0.2.0b3                   <pip>
> eth-rlp                   0.1.2                     <pip>
> eth-typing                1.3.0                     <pip>
> eth-utils                 1.2.1                     <pip>
> freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
> hexbytes                  0.1.0                     <pip>
> icc_rt                    2017.0.4             h97af966_0
> icu                       58.2                     vc14_0  [vc14]  conda-forge
> idna                      2.6                       <pip>
> idna-ssl                  1.0.0                     <pip>
> intel-openmp              2018.0.0                      8
> intervaltree              2.1.0                     <pip>
> jmespath                  0.9.3                     <pip>
> jpeg                      9b                       vc14_2  [vc14]  conda-forge
> kiwisolver                1.0.1            py36he980bc4_2    conda-forge
> libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
> Logbook                   0.12.5                    <pip>
> lru-dict                  1.1.6                     <pip>
> lxml                      4.2.5                     <pip>
> Mako                      1.0.7                     <pip>
> MarkupSafe                1.0                       <pip>
> matplotlib                2.2.2                    py36_1    conda-forge
> mkl                       2018.0.1             h2108138_4
> multidict                 4.1.0                     <pip>
> multipledispatch          0.4.9                     <pip>
> networkx                  2.1                       <pip>
> numexpr                   2.6.4                     <pip>
> numpy                     1.14.0           py36hb69e940_2
> openssl                   1.0.2n                   vc14_0  [vc14]  conda-forge
> pandas                    0.19.2                    <pip>
> pandas-datareader         0.6.0                     <pip>
> parsimonious              0.8.0                     <pip>
> patsy                     0.5.0                     <pip>
> pip                       9.0.1                    py36_1    conda-forge
> pip                       18.0                      <pip>
> pycares                   2.3.0                     <pip>
> pycryptodome              3.6.6                     <pip>
> pyparsing                 2.2.0                      py_1    conda-forge
> pypiwin32                 223                       <pip>
> pyqt                      5.6.0            py36h764d66f_7    conda-forge
> python                    3.6.4                         0    conda-forge
> python-dateutil           2.7.3                      py_0    conda-forge
> python-dateutil           2.7.3                     <pip>
> python-editor             1.0.3                     <pip>
> pytz                      2016.4                    <pip>
> pytz                      2018.5                     py_0    conda-forge
> pywin32                   223                       <pip>
> qt                        5.6.2                    vc14_1  [vc14]  conda-forge
> redo                      1.6                       <pip>
> requests                  2.18.4                    <pip>
> requests-file             1.4.3                     <pip>
> requests-ftp              0.3.1                     <pip>
> requests-toolbelt         0.8.0                     <pip>
> rlp                       1.0.2                     <pip>
> s3transfer                0.1.13                    <pip>
> scipy                     1.0.0            py36h1260518_0
> setuptools                38.4.0                   py36_0    conda-forge
> setuptools                38.5.1                    <pip>
> sip                       4.18.1           py36h6538335_0    conda-forge
> six                       1.11.0                   py36_1    conda-forge
> sortedcontainers          1.5.9                     <pip>
> SQLAlchemy                1.2.2                     <pip>
> sqlite                    3.22.0                   vc14_0  [vc14]  conda-forge
> statsmodels               0.8.0                     <pip>
> TA-Lib                    0.4.17                    <pip>
> tables                    3.4.2                     <pip>
> tk                        8.6.7                    vc14_0  [vc14]  conda-forge
> toolz                     0.9.0                     <pip>
> tornado                   5.1              py36hfa6e2cd_1    conda-forge
> urllib3                   1.22                      <pip>
> vc                        14                            0    conda-forge
> vs2015_runtime            14.0.25420                    0    conda-forge
> web3                      4.4.1                     <pip>
> websockets                5.0.1                     <pip>
> wheel                     0.30.0                   py36_2    conda-forge
> wincertstore              0.2                      py36_2    conda-forge
> wrapt                     1.10.11                   <pip>
> xz                        5.2.3                         0    conda-forge
> yarl                      1.1.0                     <pip>
> zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

Now that you know a little about me, let me tell you about the issue I am
having:

I installed Catalyst following the instructions and everything works well. I get that error when I try to run any example using the PyCharm IDE.
> AttributeError: module 'pandas' has no attribute 'Series'

I have set the interpreter just like in the attached image
![untitled](https://user-images.githubusercontent.com/43272351/45553114-779d5a80-b822-11e8-89b2-dd4332eb15d6.png)

Should the interpreter be changed to a Conda Environment and not a Virtualenv Environment?

Please let me know how I can run things using PyCharm IDE.

Sincerely,
qwzfavor

**Comment by qwzfavor** [comment]
I fixed it. Problem was not running catalyst correctly.

**Comment by 6-sukesh** [comment]
i am also facing the same problem how should i fix it??

**Comment by fuiked** [comment]
code is correct and was working but it show error now error is below i have not imported pandas any one for help



File "C:\Users\LOOSER\Desktop\New folder (3)\imageclassifier.py", line 78, in imageclassifier
    model.fit(x_train, y_train, epochs=10,batch_size=4,verbose=1, validation_data=(x_test, y_test))

  File "C:\Users\LOOSER\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)

  File "C:\Users\LOOSER\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 815, in fit
    model=self)

  File "C:\Users\LOOSER\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1099, in __init__
    adapter_cls = select_data_adapter(x, y)

  File "C:\Users\LOOSER\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 957, in select_data_adapter
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]

  File "C:\Users\LOOSER\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 957, in <listcomp>
    adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]

  File "C:\Users\LOOSER\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 245, in can_handle
    tensor_types = (ops.Tensor, np.ndarray, pd.Series, pd.DataFrame)

AttributeError: module 'pandas' has no attribute 'Series'
