### ISSUE TITLE
"code":-2010,"msg":"Account has insufficient balance for requested action." binance - when trying to sell

### ISSUE THREAD

**Issue by kooomix** [enigmampc/catalyst#467]
Hi,

I'm running a live algorithm in binance, using the latest catalyst version 0.5.20.

When I tried to create a sell order for npxs_btc (amount to sell: 34802.163, price: 0.0000002079) I got the error:
"code":-2010,"msg":"Account has insufficient balance for requested action."

As this is a sell error, I assume the error caused by something else that is not related with the balance (that I do have, regardless)

I have a feeling it might have something to do with binance precision as the 5 digits left of dot for the amount also gave me errors when trying it on bitfinex (in [this](https://github.com/enigmampc/catalyst/issues/416) thread)

Thanks

**Comment by kooomix** [comment]
I have got the price from the data.history... maybe it is a matter of data
types?
Any suggestion how to generate this precision?

**Comment by lenak25** [comment]
IMHO, the `data.history()` should also return data in the same precision - could you please provide more information regarding the specific parameters calling to data.history (including date), in addition to the command you were using when setting the price for the order? 

Thanks,

Lena

**Comment by kooomix** [comment]
Hi,

I now notice that I indeed have manipulated the data after retrieving it and precision has changed... 
(I actually thought that CCXT / Catalyst make sure precision is aligned with the exchange requirements before opening the orders..)

Can you offer an idea how can I align the desired precision after the calculation? 
I know CCXT maintain a function "decimal_to_precision" - do you think it will be a good idea to somehow use it?

Thanks!

**Comment by FWangTrading** [comment]
@kooomix I use Decimal to trim price, but it doesn't necessarily keep required precision. I would like to know if there is a better way
`from decimal import Decimal`
`dprice = Decimal(0.00000119988899).quantize(Decimal('0.000000001'))`
`order(asset, qty, limit_price = float(dprice))`

**Comment by FWangTrading** [comment]
also keep in mind that you can get error -2010 if there is another sell order placed outside the algo.

**Comment by kooomix** [comment]
Thanks for noting that.
This is not the case, all trades are done through the algo.

**Comment by kooomix** [comment]
Another direction of investigation  - this specific coin has very low activity on the exchange, therefore order is open for quite some time, while other coins usually filled quickly.

I have noticed from my logs that the open ordered was reported, but after I restarted the algorithm (for other reasons), it lost this information and considered it as having no open orders.

Related or not - see this [other issue](https://github.com/enigmampc/catalyst/issues/471) I have opened.

**Comment by FWangTrading** [comment]
@kooomix glad to hear that you pinpointed the issue. context.blotter.open_orders will reset after you restarting the algorithm. To get all orders working on the exchange, I'd use `get_open_orders()`. Please refer to https://github.com/enigmampc/catalyst/blob/master/catalyst/examples/buy_and_hodl.py

**Comment by lenak25** [comment]
@kooomix and @FWangTrading , thanks for your inputs, seems this issue can be closing.
@kooomix if you feel otherwise, feel free to reopen.

**Comment by kooomix** [comment]
@lenak25 Thanks.

I do feel that adjusting the mechanism in a way open orders are properly picked up when the algorithm is restarted is quite essential... 

And more general - as catalyst is still in alpha, and as there are a lot of issues raised from time to time when running an algo, and therefore, a lot of cases in which algo is being restarted, I think it should be considered **on design level**, that an algorithm restarted (under the same namespace) should pick up all relevant information, as if algo never stopped...

**Comment by lenak25** [comment]
Thanks @kooomix for your feedback. 

I think this enhancement is deserved its own ticket, could you please open a new issue with this feature request (or update on #471 if seems relevant).
It will be taken into consideration once the live algorithm state saving mechanism is revised.
Feel free to submit a PR on this matter as well.

Thanks,
Lena

**Comment by kooomix** [comment]
Done. Thanks.
