### ISSUE TITLE
problem with position.cost_basis

### ISSUE THREAD

**Issue by FWangTrading** [enigmampc/catalyst#472]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows
* Python Version: 3.6
* Python Bitness: 
* How did you install Catalyst: pip
* Python packages: catalyst 0.5.20

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I found that the value of positions.cost_basis changes as the position decreases (covering), which is not expected according to the defination. 
here (catalyst\finance\performance\position.py):
![image](https://user-images.githubusercontent.com/14914956/45734903-c2fd9300-bbab-11e8-85bd-8ebd3061b8a3.png)
and here:
https://www.tradingtechnologies.com/help/fix-adapter-reference/pl-calculation-algorithm/understanding-pl-calculations/

I did a test (in backtesting mode) by buying then selling an assets, print out the cost_basis and compare it with fill prices (getting by `context.perf_tracker.todays_performance.processed_transactions`). here is the result:
![image](https://user-images.githubusercontent.com/14914956/45735105-5c2ca980-bbac-11e8-8098-b95718ec6f81.png)
I understand that as position increases, the 'Diff' comes from commission. I expect the catalyst_cost_basis remains the same as position decreases, which is not the case. I would like to know if I miss anything, or this is a bug. 

* What did you expect to happen?
**cost_basis stay the same when position is covering.**
* What happened instead?
**cost_basis updates all the time.**

Here is how you can reproduce this issue on your machine:

## Reproduction Steps
I randomly picked xem.eth to do test. I expect similar result using any different asset.
```
def handle_data(context, data):
	# set context.can_buy = True, context.can_sell = False in initialize()
	bid_price = 999
	ask_price = 0
	quantity = 100
	
	if context.portfolio.positions[context.asset].amount != 0:
		print('{} @ {}'.format(context.portfolio.positions[context.asset].cost_basis, context.portfolio.positions[context.asset].amount))
	if context.can_buy:
		if context.portfolio.positions[context.asset].amount < 1000:
			order(context.asset, quantity, limit_price = bid_price)
		else:
			context.can_sell = True
			context.can_buy = False
	if context.can_sell:
		if context.portfolio.positions[context.asset].amount > 0:
			order(context.asset, -1 * quantity, limit_price = ask_price)
		else:
			return

def analyze(context, perf):
	print(context.perf_tracker.todays_performance.processed_transactions)
```

Sincerely,
Frank

**Comment by lenak25** [comment]
@FWangTrading I am closing this, feel free to reopen if you feel otherwise.
