### ISSUE TITLE
ExchangeAuthEmpty: Please enter your API token key and secret for exchange {exchange} in the following file: {filename}

### ISSUE THREAD

**Issue by wkpzwy** [enigmampc/catalyst#473]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by lenak25** [comment]
Hi @wkpzwy ,

Please provide more information on the issue you are experiencing, it is advisable to follow the guidelines provided when opening a new issue. 
The `ExchangeAuthEmpty` exception mentioned in the subject is thrown when trying to run in live mode without providing the API authentication details. For more details please refer to the [docs](https://enigma.co/catalyst/live-trading.html#authentication).
I am closing this, feel free to reopen if you continue to experience issues after defining the API authentication details in the correct format.

Lena
