### ISSUE TITLE
Can't ingest any data from catalyst

### ISSUE THREAD

**Issue by Janda763884404** [enigmampc/catalyst#476]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:
![image](https://user-images.githubusercontent.com/23626255/46118035-25ebcb80-c237-11e8-9b16-c8d3f1fa3bda.png)

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
![image](https://user-images.githubusercontent.com/23626255/46117971-d4434100-c236-11e8-9eda-6cde130ce0b3.png)

* What did you expect to happen?

* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.catalyst ingest-exchange -x bitfinex -i btc_usd -f daily
2.catalyst ingest-exchange -x bitfinex -i btc_usd -f minute
3.
...

## What steps have you taken to resolve this already?

To solve this, i try to install new env with conda or pip, and finally with the same result~

...beside, i try to change the exchange  and it doesn't work

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by lenak25** [comment]
Hi @Janda763884404 ,

Have you tried to ingest only a single pair? 
How do you know that the ingestion didn't work?
In the snapshot you have attached you are trying to ingest the entire daily/minute data from the exchange which can take some time (depends on your internet connection).
I suggest you do the following:
1. Clean the exchange's bundles to start from scratch using: `catalyst clean-exchange -x bitfinex`
2. Ingest only one pair, for example: `catalyst ingest-exchange -x bitfinex -i btc_usd -f daily`
3. Check the ingestion by running a strategy using this data.

Please let us know if it helped.

Lena

**Comment by Janda763884404** [comment]
Hi @lenak25 
Before I install the catalyst on py3,  this didn't work on py2 after i attempt to follow you guideline.
Then, I try to create the virtualenv about py3, and install visual c++ 2015.
and add some nargin like -s
like the following:

        catalyst ingest-exchange -x bitfinex -i btc_usd -f daily -s 2015-01-01

Strangely, both above is work~
I have no idea about what happen in my envs~

**Comment by lenak25** [comment]
Hi @Janda763884404 ,

The `-s`/`--start` flag defines the start date of the data range being ingested. By default the entire existing data range will be ingested.
The catalyst calendar starts at `2015-3-1` (meaning that currently this is the most recent timestamp of pricing data used by catalyst). So by specifying `2015-01-01` in your command, you basically ingested the entire data range, the same as done if this flag was omitted.

So everything seems to work right now?

**Comment by lenak25** [comment]
@Janda763884404 , I am closing this, feel free to reopen if you still experience issues.
