### ISSUE TITLE
Is it possible to get market cap data?

### ISSUE THREAD

**Issue by lucasgadams** [enigmampc/catalyst#478]
Just wondering if this is built in or if there is some way to do this. What are the possible options for data.current? I know you can get OHLC and volume but is there anything else?

**Comment by lenak25** [comment]
Hi @lucasgadams ,

Catalyst uses pricing data (OHLCV candles) for both backtest and live trading. In backtest, this data should be ingested before trying to run a strategy. 
Catalyst is also integrated with the [marketplace](https://enigma.co/marketplace/) which allows users to contribute data, that other users of the system can then subscribe to and consume. Please refer to the [list](https://enigma.co/marketplace/status/) of the current available data sets on the marketplace, there are several which hold coinmarketcap information.

Lena
