### ISSUE TITLE
Inconsistent Pairsettings for Pairs with quote USD/USDT  --- USD <-> USDT are mixed (Bitfinex, Live Trading)

### ISSUE THREAD

**Issue by avolution** [enigmampc/catalyst#482]
For example a given PairsObject

{  
   'id':'BTCUSD',
   'symbol':'BTC/USDT',
   'base':'BTC',
   'quote':'USDT',
   'baseId':'BTC',
   'quoteId':'USD',
   'active':True,
   'precision':{  
      'price':5,
      'amount':5
   },
   'limits':{  
      'amount':{  
         'min':0.002,
         'max':2000.0
      },
      'price':{  
         'min':1e-05,
         'max':100000.0
      },
      'cost':{  
         'min':2e-08,
         'max':None
      }
   },
   'info':{  
      'pair':'btcusd',
      'price_precision':5,
      'initial_margin':'30.0',
      'minimum_margin':'15.0',
      'maximum_order_size':'2000.0',
      'minimum_order_size':'0.002',
      'expiration':'NA',
      'margin':True
   }
}

Results in some Problems in Live Mode(Algostartup-> no balance error, tradeexecution -> can not trade usdt pairs with usd as quote currency etc.) after updating Catalyst from 0_5_17 to 0_5_20

This is probably a result of the Update of CCXT in the newest version

**Comment by lenak25** [comment]
Hi @avolution ,

There is indeed some inconsistency in Bitfinex and we have an open issue for it: #84
But could you please elaborate on the issues you are having in live mode: what exactly does not seem to work?
BTW, the definition of the `BTCUSD` market object didn't seem to change between the CCXT versions 1.12.131 => 1.17.94, so I am not sure it is related to this upgrade but please let us know what different behaviour is observed on catalyst 0.5.20

Thanks,

Lena

**Comment by lenak25** [comment]
Hi @avolution , 

I am closing this, please feel free to reopen if you feel otherwise.

Thanks,
Lena
