### ISSUE TITLE
Ingest problem

### ISSUE THREAD

**Issue by riopal** [enigmampc/catalyst#49]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows10 `)
* Python Version: `$ anaconda 3`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

The ingest function is not working tried multiple times specifying exchange howevwewr it does not work

(C:\ana) C:\Users\user C-137>activate catalyst

(catalyst) C:\Users\user C-137>catalyst ingest --bittrex-b
Error: no such option: --bittrex-b

(catalyst) C:\Users\user C-137>catalyst ingest --bittrex -b
Error: no such option: --bittrex

(catalyst) C:\Users\user C-137>catalyst ingest -b
Error: -b option requires an argument

(catalyst) C:\Users\user C-137>catalyst ingest
Error: No bundle registered with the name None

(catalyst) C:\Users\user C-137>

**Comment by riopal** [comment]
PS: I also tried specifying the bundle however both times it does not link to the exchange

**Comment by fredfortier** [comment]
This syntax is not supported, see: `catalyst ingest-exchange --help` for details.

The documentation is here: enigmampc.github.io/catalyst
