### ISSUE TITLE
Data History Limit Live Trading

### ISSUE THREAD

**Issue by jzay** [enigmampc/catalyst#490]
Hi, so this isn't a bug in the software but I didn't know where else to get a proper answer for my questions and it does limit the functionality of the software to some extent.  

I am running the strategy live in minute mode and had requested the last 5 days of minute candles with the data.history() function but received only the last 16 hours. 

Is there anyway around this? I'm guessing the function relies on CCXT instead of the stored historical data but I cannot trade my strategy without 5 days of pervious information so i'm a bit stuck. Thank You

**Comment by lenak25** [comment]
Hi @jzay,

In paper trading and live, catalyst fetches OHLCV candles directly from each exchange - using CCXT - and is limited by the restrictions imposed by the exchanges APIs.
From the[ CCXT manual](https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts):

> Most of exchanges will not allow to query detailed candlestick history (like those for 1-minute and 5-minute timeframes) too far in the past. They usually keep a reasonable amount of most recent candles, like 1000 last candles for any timeframe. 

The only option to overcome is to store the fetched data and then being able to merge it with the more recent data fetched in the next iterations. Currently this is not on our roadmap, but you can try implementing this in your strategy.

Lena
