### ISSUE TITLE
Pricing inconsistency in Poloniex historical prices from 07/2018 to 08/2018

### ISSUE THREAD

**Issue by aredare** [enigmampc/catalyst#491]
Dear Catalyst Maintainers,

# My environment:
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

aiodns==1.1.1
aiohttp==3.0.1
alembic==0.9.7
async-timeout==2.0.1
attrdict==2.0.0
attrs==18.1.0
bcolz==1.2.1
boto3==1.5.27
botocore==1.8.50
Bottleneck==1.2.1
cchardet==2.1.1
ccxt==1.12.131
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0.1
decorator==4.3.0
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.18
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.1.0
eth-utils==1.1.2
hexbytes==0.1.0
idna==2.6
idna-ssl==1.1.0
intervaltree==2.1.0
jmespath==0.9.3
kiwisolver==1.0.1
Logbook==0.12.5
lru-dict==1.1.6
lxml==4.2.4
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.2.3
multidict==4.3.1
multipledispatch==0.4.9
networkx==2.1
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.6.0
parsimonious==0.8.0
patsy==0.5.0
pycares==2.3.0
pycryptodome==3.6.5
pyparsing==2.2.0
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2016.4
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==1.0.2
s3transfer==0.1.13
scikit-learn==0.19.2
scipy==1.0.0
six==1.11.0
sklearn==0.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.2
statsmodels==0.8.0
tables==3.4.2
toolz==0.9.0
urllib3==1.22
web3==4.2.1
websockets==6.0
wrapt==1.10.11
yarl==1.1.0

# Description of Issue
I'm not sure what the issue is but I initially noticed I was getting incorrect price data from the data.current function while executing a backtest for August 2018.

if name == 'main':
    run_algorithm(
        capital_base=5000,
        data_frequency='minute',
        initialize=initialize,
        handle_data=handle_data,
        analyze=analyze,
        exchange_name='poloniex',
        quote_currency='usdt',
        algo_namespace=algo_namespace,
        start=pd.to_datetime('2018-8-1', utc=True),        end=pd.to_datetime('2018-8-31', utc=True),   # '2017-11-10
    )

I've pasted examples of the output of the prices I was getting below.
Example output:
2018-08-01 00:00:00+00:00
TradingPair(680958 [etc_usdt])     12.190001
TradingPair(374465 [btc_usdt])    607.573618
TradingPair(23347 [eth_usdt])     296.272790
TradingPair(19201 [ltc_usdt])      51.600000

btc_usdt example
2018-07-31 23:59:00+00:00,8221.15112094,
2018-08-01 00:00:00+00:00,607.5736177,

You can reproduce this output by simply printing the prices obtained from data.history and/or data.current functions with the "price" field selected in the handle_data block.

I tried doing data.history at a future data to see if it was just data.current that was incorrect but that wasn’t the case. The price for that time stamp in data history matched the inconsitent one in data.current I posted earlier.

I originally posted this in the catalyst_dev chat group on Discord and was redirected here. 

Are

**Comment by SOGorman35** [comment]
there was a period from about July 29th to a few weeks ago where Poloniex data wasn't updating correctly, and was either showing the July 29th price, or a price of like $607 for BTC (as you mentioned).  Try cleaning the exchange data and downloading again, it should work.

**Comment by aredare** [comment]
Thanks man. Cleaning the data and downloading it again did the trick.
