### ISSUE TITLE
error in documentation - get_orderbook

### ISSUE THREAD

**Issue by FWangTrading** [enigmampc/catalyst#492]
Dear Catalyst Maintainers,

# Description of Issue

* What did you expect to happen?
    The order_type requires 'bids' / 'asks' / 'all'  as argument instead of 'bid' / 'ask' / 'all' listed in the document: http://enigma.co/catalyst/appendix.html#catalyst.api.get_orderbook
Below is quoted from ccxt
![image](https://user-images.githubusercontent.com/14914956/46879325-59b81b00-ce0b-11e8-9116-62bd881fbc5a.png)

Sincerely,
Frank

**Comment by lenak25** [comment]
@FWangTrading , thanks for reporting, this was fixed.
