### ISSUE TITLE
time.sleep() cripples handle_data

### ISSUE THREAD

**Issue by demontamer** [enigmampc/catalyst#495]
Dear Catalyst Maintainers,

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I noticed including time.sleep(1) in handle_data causes it to stall forever. Though I am using version 0.5.18
* What did you expect to happen?
sleep for one second
* What happened instead?
catalyst stalled 

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. include time.sleep(1) as the first line in handle_data
2. run a backtest using minute frequency
3. 
...

## What steps have you taken to resolve this already?
tried different sleep times including 0.05
...

# Anything else?

...

Sincerely,
`$ demontamer`

**Comment by lenak25** [comment]
Hi @demontamer ,

I wasn't able to reproduce the issue you've described. 
The addition of the sleep interval to each minute tick will increase the period of the entire backtest. 
You can easily suspect the addition of the sleep interval by adding a `print` before/after the `sleep` command: by playing with different intervals you will see the delay between each `print`. 

Lena

**Comment by lenak25** [comment]
@demontamer , I am closing this. Feel free to reopen if you feel otherwise.
