### ISSUE TITLE
data.history for Cryptopia

### ISSUE THREAD

**Issue by Amarchuk** [enigmampc/catalyst#507]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Ubuntu 16.04
* Python Version: 3.6.6
* Python Bitness: 64
* How did you install Catalyst: using pip and virtualenv as described in docs
* Python packages: 
```
absl-py==0.5.0
aiodns==1.1.1
aiohttp==3.4.4
alembic==0.9.7
astor==0.7.1
async-timeout==3.0.0
attrdict==2.0.0
attrs==18.2.0
bcolz==1.2.1
boto3==1.5.27
botocore==1.8.50
Bottleneck==1.2.1
cchardet==2.1.1
ccxt==1.17.94
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0.1
decorator==4.3.0
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.20
eth-abi==1.2.0
eth-account==0.2.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.3.0
eth-utils==1.2.2
gast==0.2.0
grpcio==1.15.0
h5py==2.8.0
hexbytes==0.1.0
idna==2.6
idna-ssl==1.1.0
intervaltree==2.1.0
jmespath==0.9.3
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
Logbook==0.12.5
lru-dict==1.1.6
lxml==4.2.5
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==3.0.0
multidict==4.4.2
multipledispatch==0.4.9
networkx==2.1
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.6.0
parsimonious==0.8.0
patsy==0.5.0
Pillow==5.3.0
protobuf==3.6.1
pycares==2.3.0
pycryptodome==3.6.6
pyparsing==2.2.1
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2016.4
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==1.0.2
s3transfer==0.1.13
scipy==1.0.0
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.2
statsmodels==0.8.0
tables==3.4.2
tensorboard==1.11.0
tensorflow==1.11.0
termcolor==1.1.0
tflearn==0.3.2
toolz==0.9.0
urllib3==1.22
web3==4.4.1
websockets==5.0.1
Werkzeug==0.14.1
wrapt==1.10.11
yarl==1.1.0
```
Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

During live-trading on cryptopia I need to get some historical data before recent date. In `handle_data` I call 
```python
data.history(
        context.assets,
        fields=['close', 'high', 'low'],
        bar_count=31,
        frequency='30T'
    )
```

* What did you expect to happen?

Obtain historical data.

* What happened instead?

The function call finished without any exception, but returned data is empty e.g. instead of shape (3, 31, number_of_assets) I get (3, 0, number_of_assets).

UPD.: This is also true for paper-trading, so can be easily reproduced.
Thanks!
...

Sincerely,
amarch

**Comment by lenak25** [comment]
Hi @Amarchuk , 

Thanks for reporting this, I was able to reproduce this. 

It seems that Cryptopia behaves differently than other crypto exchanges when returning OHLCV candles.
Other exchanges, which are fully supported by catalyst, return OHLCV data in fixed intervals. Meaning that if 30-min candles are requested than the exchange will return the candles in fixed timestamps: 00:00, 00:30, 01:00, etc..
Cryptopia, however does not use fixed intervals. If for example two 30-min candles were requested in 01:43, than 2 candles with the following timestamps will be returned: 01:13, 00:43.
Catalyst does not support this behavior, thus you received an empty list from the `data.history` call.
Note however that the only frequency that **could** have worked correctly is the **1-min** as its behaviour is the same in both approaches, however the minimal interval supported by Cryptopia is 15-min.

Although catalyst integrates with the CCXT library and has the potential to work with all its supported exchanges, some exchanges with non standard behaviour might have issues when using catalyst. We are actively testing and adding support for more exchanges in live mode. 
The current list of the tested and supported exchanges can be found [here](https://enigma.co/catalyst/live-trading.html#supported-exchanges).

Lena

**Comment by Amarchuk** [comment]
@lenak25 thanks for the investigation!

It seems like the only option is to wait for needed round time like 00:30 and collect the data. It is not that good, because it is not always possible to obtain all needed for just one minute.

You can close this issue now, but one last question: how do you know that minimal interval supported by Cryptopia is 15min? I can't find proper link where this is mentioned.

**Comment by lenak25** [comment]
> It seems like the only option is to wait for needed round time like 00:30 and collect the data. It is not that good, because it is not always possible to obtain all needed for just one minute.

Yes, I understand.

Regarding the minimal interval, I used the [CCXT code](https://github.com/ccxt/ccxt/blob/master/python/ccxt/cryptopia.py#L64) to learn about the supported timeframes.
