### ISSUE TITLE
[QUESTION] About future plan of the project

### ISSUE THREAD

**Issue by xiaohai6688** [enigmampc/catalyst#508]
Dear Catalyst Maintainers,

Sorry for putting a question in issue tracker, I didn't find a better place for this.

May I ask about the future plan of this project? In the document I saw there were quite a few new features proposed for 2018, but seems none of them were accomplished. Will catalyst still be maintained in near future or it's being phased out?  I'm asking because we intend to build our trading bot based on catalyst, but if it will not be maintained / enhanced any longer we may have to reconsider.

Thank you.

Regards

R.

**Comment by catalyst-support** [comment]
Hi @xiaohai6688 ,

Besides the Github, you can join the [Catalyst Forum](https://forum.catalystcrypto.io/) for questions around Catalyst, algorithmic trading and technical support. We also have a [Discord](https://discordapp.com/invite/SJK32GY) group with the #catalyst_dev and #catalyst_setup dedicated channels. 

In regards to your question, catalyst continued to be developed and we continue to refine the project goals during the development process. Many of the milestones set for 2018 were accomplished, others were deprioritized. And as any open source project, we welcome any contribution :)

Could you please share the reference to the proposed features for 2018 (we recently removed a page from the docs to avoid confusion, so we'll be happy to know if there are still misleading doc pages)?

Thanks

**Comment by xiaohai6688** [comment]
Hello

Thank you for the response. It's great to know you guys are still refining the catalyst!

I saws the features for 2018 here: https://enigma.co/catalyst/features.html
In the "Upcoming features" section (like pipeline support, web UI etc ...).  Maybe they've been implemented but I didn't find them. Sorry for the confusion if it is the case.

Regards

**Comment by catalyst-support** [comment]
Thanks @xiaohai6688 for sharing. 
We've removed the link for this page from the docs, however it is still possible to access it, sorry for the confusion. 

As mentioned above, some of the milestones set for 2018 were accomplished (API documentation, Support for data ingestion of community-contributed data sets and more), others were deprioritized. 

We are closing this, feel free to reopen if you still have questions, or using any of the other catalyst channels.

Thanks
