### ISSUE TITLE
ModuleNotFoundError: No module named 'mpl_finance' on 'talib_simple.py' example

### ISSUE THREAD

**Issue by chairy11** [enigmampc/catalyst#509]
Hi, I'am trying the  'talib_simple.py' example,  got error 
```
Traceback (most recent call last):
  File "talib_simple.py", line 18, in <module>
    from mpl_finance import candlestick_ohlc
ModuleNotFoundError: No module named 'mpl_finance'
```

so, I install it:

```
 pip install PyHamcrest
pip install https://github.com/matplotlib/mpl_finance/archive/master.zip
```

but still not working.

Since matplotlib.finance has been deprecated, is there any new way to use candlestick_ohlc?  Could you help to update this example?

Thank you very much!

**Comment by lenak25** [comment]
Hi @chairy11 ,

Have you tried installing using `pip install mpl-finance`?

**Comment by chairy11** [comment]
> Hi @chairy11 ,
> @lenak25 
> Have you tried installing using `pip install mpl-finance`?


`pip install mpl-finance` doesn't work, because [mpl_finance project](https://github.com/matplotlib/mpl_finance) was deprecated.  pip and conda could not find the download git.

> This module consists of code extracted from the deprecated matplotlib.finance module along with a few examples of usage.

>The code is provided as is and is basically un-maintained.

**Comment by lenak25** [comment]
> I have tried installing using pip install mpl-finance, but it didn't work.

What exactly did not work? What is the error code you received?

In addition, please share your python version + the list of your installed packages.

**Comment by chairy11** [comment]
@lenak25 

Thank you, I have successfully installed mpl-finance-0.10.0 by the command `pip install mpl-finance`.

I made the mistake to use the command `conda install mpl_finance`.   
The right name is `mpl-finance`, not `mpl_finance` .  Thank you to tell me.

> What exactly did not work? What is the error code you received?

That error occurred when I tried to run the example by `python talib_simple.py`, and the error message was as following:
```
Traceback (most recent call last):
  File "talib_simple.py", line 18, in <module>
    from mpl_finance import candlestick_ohlc
ModuleNotFoundError: No module named 'mpl_finance'
```

so I tried to install mpl_finance using the command 
```
conda install mpl_finance
```
but got the error ：
```
 conda install mpl_finance
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - mpl_finance

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```


But now I solve the problem by `pip install mpl-finance`, thank you.

**Comment by lenak25** [comment]
Happy to hear, closing this.
