### ISSUE TITLE
examples/buy_low_sell_high_live.py not working

### ISSUE THREAD

**Issue by vonpupp** [enigmampc/catalyst#51]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `Linux 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux`)
* Python Version: `Python 2.7.13`
* Python Bitness: `64`
* How did you install Catalyst: (`pip`)
* Python packages: `$ pip freeze`
```
alembic==0.9.6
backports-abc==0.5
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
bcolz==0.12.1
bleach==2.1.1
Bottleneck==1.2.1
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
configparser==3.5.0
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.2
decorator==4.1.2
empyrical==0.2.1
enigma-catalyst==0.3
entrypoints==0.2.3
enum34==1.1.6
functools32==3.2.3.post2
html5lib==1.0b10
idna==2.6
intervaltree==2.1.0
ipykernel==4.6.1
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.0.3
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.3.0
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
mistune==0.8
multipledispatch==0.4.9
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.0
notebook==5.2.0
numexpr==2.6.4
numpy==1.13.3
pandas==0.19.2
pandas-datareader==0.5.0
pandocfilters==1.4.2
pathlib2==2.3.0
patsy==0.4.1
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
pyzmq==16.0.3
qtconsole==4.3.1
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scandir==1.6
scipy==1.0.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.14
statsmodels==0.8.0
subprocess32==3.2.7
tables==3.4.2
terminado==0.6
testpath==0.3.1
toolz==0.8.2
tornado==4.5.2
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.0.6
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

The example `catalyst/catalyst/examples/buy_low_sell_high_live.py` should run live, however it is not. if I remove the comments at the bottom of the file (and comment the prior section with start and end dates) and try to run it with `catalyst run -f buy_low_sell_high_live.py -o buy_low_sell_high_live.pickle`, I am having the following error: `Error: must specify dates with '-s' / '--start' and '-e' / '--end' needs a start and end date.`

* What did you expect to happen?

To run live.

* What happened instead?

I received an error

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Comment lines 149 to 159
2. Uncomment lines from 160 to 168
3. Run it with `catalyst run -f buy_low_sell_high_live.py -o buy_low_sell_high_live.pickle`

## What steps have you taken to resolve this already?

None, I believe that zipline might need some patching to make the start and end date parameters optional

# Anything else?

Sincerely,
Albert.

**Comment by lacabra** [comment]
Hi Albert, and thanks for taking the time to report the issues that you are experiencing with Catalyst. This is not an issue and is the expected behavior of Catalyst. If anything, it's not well-documented enough. Take a look at https://enigmampc.github.io/catalyst/live-trading.html#trading-an-algorithm for the parameters that you need to run an algo in live mode.
Type `catalyst --help` and you will see the two modes that catalyst can run on: `run` for backtesting and `live` for live-trading. You can further type `catalyst run --help` or `catalyst live --help` to learn more about the parameters that each mode takes. Hope this helps!
