### ISSUE TITLE
Live Trading Different from Backtest Results(Bitfinex)

### ISSUE THREAD

**Issue by Decision420s** [enigmampc/catalyst#512]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Ubuntu 16._`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I was live trading an algorithm for the past few weeks and it was sending trades but then I realized that when I ran the backtest there were more trades than those that I did during live trading. And also I was getting this message: WARNING: exchange_algorithm: unable to calculate performance: 'starting_cash'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

Just run an algorithm in live mode

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by lenak25** [comment]
@Decision420s , unless you were using the **exact** same time period in both live and backtest, you shouldn't expect any other behavior.

**Comment by lenak25** [comment]
@Decision420s , we are closing this. Feel free to reopen if you feel otherwise.
