### ISSUE TITLE
How to backtest local data 

### ISSUE THREAD

**Issue by studyquant** [enigmampc/catalyst#517]
Dear Catalyst Maintainers,

How can I backtest local data.   is it possiable it do not connect ccxt?   I know how to backtest by build panel data in zipline. is it same in catalyst?

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by studyquant** [comment]
I have backtest the local data successfully, While, I have questions that , whether catalyst backtest supports futures backtest.  It will automatically understand the short and open ?

**Comment by lenak25** [comment]
Hi @studyquant ,

Currently shorting/margin trading is not supported by catalyst, we have an open issue for it already -#415. 

I am closing this. Feel free to reopen if you feel otherwise.

Thanks, 
Lena

**Comment by studyquant** [comment]
Hello, backtest local data failed.  can u tell me that how to backtest local data？
I have create a  panel data and run_algorithm by following code.  While， it backtested from ingested data not my local data.   How to solve that ?

 perf = run_algorithm(
            capital_base=1000,
            data_frequency='minute',#
            data = panel,
            initialize=initialize,
            handle_data=handle_data,
#            analyze=analyze,
            exchange_name='binance',
            algo_namespace=NAMESPACE,
            quote_currency='usdt',
            start=pd.to_datetime('2018-11-07', utc=True),
            end=pd.to_datetime('2018-11-07', utc=True),
        )
