### ISSUE TITLE
catalyst.api.record fails to record values 

### ISSUE THREAD

**Issue by studyquant** [enigmampc/catalyst#519]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:
catalyst.api.record fails to record values 
# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python 3.5.3 --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by lenak25** [comment]
@studyquant , please provide more information -  both on the issue you are experiencing and regarding the environment you are using.

**Comment by lenak25** [comment]
@studyquant , I am closing this, feel free to reopen and share more data.

**Comment by studyquant** [comment]
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from logbook import Logger

from catalyst import run_algorithm
from catalyst.api import (record, symbol, order_target_percent,)
from catalyst.exchange.utils.stats_utils import extract_transactions
import pytz
from collections import OrderedDict


NAMESPACE = 'dual_moving_average'
log = Logger(NAMESPACE)



def initialize(context):
    context.i = 0
    context.asset = symbol('btc_usdt')
    context.base_price = None


def handle_data(context, data):
    # define the windows for the moving averages
    short_window = 50
    long_window = 200
#    log.info('2')
    # Skip as many bars as long_window to properly compute the average
    context.i += 1
    if context.i < long_window:
        return

    # Compute moving averages calling data.history() for each
    # moving average with the appropriate parameters. We choose to use
    # minute bars for this simulation -> freq="1m"
    # Returns a pandas dataframe.
    short_data = data.history(context.asset,
                              'price',
                              bar_count=short_window,
                              frequency="10T",
                              )

    short_mavg = short_data.mean()
    long_data = data.history(context.asset,
                             'price',
                             bar_count=long_window,
                             frequency="20T",
                             )
    long_mavg = long_data.mean()

    # Let's keep the price of our asset in a more handy variable
    price = data.current(context.asset, 'price')

    # If base_price is not set, we use the current value. This is the
    # price at the first bar which we reference to calculate price_change.
    if context.base_price is None:
        context.base_price = price
    price_change = (price - context.base_price) / context.base_price

    # Save values for later inspection
    record(price=price,
           cash=context.portfolio.cash,
           price_change=price_change,
           short_mavg=short_mavg,
           long_mavg=long_mavg)

    # Since we are using limit orders, some orders may not execute immediately
    # we wait until all orders are executed before considering more trades.
    orders = context.blotter.open_orders
#    if len(orders) > 0:
#        return

    # Exit if we cannot trade
    if not data.can_trade(context.asset):
        return

    # We check what's our position on our portfolio and trade accordingly
    pos_amount = context.portfolio.positions[context.asset].amount

    # Trading logic
    if short_mavg > long_mavg and pos_amount == 0:
        # we buy 100% of our portfolio for this asset
        order_target_percent(context.asset, -0.5)
        
     
    elif short_mavg < long_mavg and pos_amount == 0:
        # we sell all our positions for this asset
        order_target_percent(context.asset, -0.5)

if __name__ == '__main__':


    
    perf = run_algorithm(
            capital_base=1000,
            data_frequency='minute',#minute
            data = panel,
            initialize=initialize,
            handle_data=handle_data,
            analyze=analyze,
            exchange_name='binance',
            algo_namespace=NAMESPACE,
            quote_currency='usdt',
            start=pd.to_datetime('2018-02-07', utc=True),
            end=pd.to_datetime('2018-02-09', utc=True),
        )

    
I try to run above strategy, but it fails to record the value I wish to. such as price, and cash...

**Comment by lenak25** [comment]
@studyquant , could you please share the command you used to run your algorithm?
Have you followed [these](https://enigma.co/catalyst/beginner-tutorial.html#command-line-interface) instructions for saving the algorithm performance `DataFrame` into a binary file (pickle) and then running a Python code to load it?
