### ISSUE TITLE
Ingest deprecated

### ISSUE THREAD

**Issue by riopal** [enigmampc/catalyst#52]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows10)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda` )

So I tried using the command :catalyst ingest-exchange -x {bittrex}

However I get this back.

(C:\ana) C:\Users\user C-137>activate catalyst

(catalyst) C:\Users\user C-137>catalyst ingest-exchange -x {bittrex}
Usage: catalyst ingest-exchange [OPTIONS]

Error: Invalid value for "-x" / "--exchange-name": invalid choice: {bittrex}. (choose from poloniex, bitfinex, bittrex)

(catalyst) C:\Users\user C-137>catalyst ingest-exchange -x {exchange-bittrex}
Usage: catalyst ingest-exchange [OPTIONS]

Error: Invalid value for "-x" / "--exchange-name": invalid choice: {exchange-bittrex}. (choose from poloniex, bitfinex, bittrex)

(catalyst) C:\Users\user C-137>catalyst ingest-exchange -x {exchange_bittrex}
Usage: catalyst ingest-exchange [OPTIONS]

Error: Invalid value for "-x" / "--exchange-name": invalid choice: {exchange_bittrex}. (choose from poloniex, bitfinex, bittrex)

(catalyst) C:\Users\user C-137>catalyst ingest-exchange -x {Poloniex}
Usage: catalyst ingest-exchange [OPTIONS]

Error: Invalid value for "-x" / "--exchange-name": invalid choice: {Poloniex}. (choose from poloniex, bitfinex, bittrex)

(catalyst) C:\Users\user C-137>catalyst ingest-exchange -x {Poloniex}

**Comment by lacabra** [comment]
You should type it without the {}:

`catalyst exchange-ingest -x bitfinex`

or 

`catalyst exchange-ingest -x poloniex`

This is not an issue, this is the expected behavior for Catalyst. If you need help getting started, you can join our discord group, which may be easier than opening issues: https://discord.gg/SJK32GY

**Comment by lacabra** [comment]
Also, in the latest version, you don't need to worry about `ingest` at all. You can just run your trading algorithm, and Catalyst will automatically ingest whatever pricing data you need from the exchange that you trade against :)
