### ISSUE TITLE
Ingest binance: Forbidden

### ISSUE THREAD

**Issue by brandsimon** [enigmampc/catalyst#523]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: CentOS 7 `Linux backtest 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 3.6.6`
* Python Bitness: `64`
* How did you install Catalyst: pip
* Python packages: 
```
aiodns==1.1.1
aiohttp==3.4.4
alembic==0.9.7
async-timeout==3.0.1
attrdict==2.0.0
attrs==18.2.0
bcolz==1.2.1
boto3==1.5.27
botocore==1.8.50
Bottleneck==1.2.1
cchardet==2.1.1
ccxt==1.17.94
certifi==2018.1.18
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0.1
decorator==4.3.0
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.21
eth-abi==1.3.0
eth-account==0.2.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==2.0.0
eth-utils==1.4.0
hexbytes==0.1.0
idna==2.7
idna-ssl==1.1.0
intervaltree==2.1.0
jmespath==0.9.3
Logbook==0.12.5
lru-dict==1.1.6
lxml==4.2.5
Mako==1.0.7
MarkupSafe==1.0
multidict==4.5.2
multipledispatch==0.4.9
networkx==2.1
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.6.0
parsimonious==0.8.1
patsy==0.5.0
pycares==2.3.0
pycryptodome==3.7.2
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2016.4
redo==2.0.1
requests==2.20.1
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==1.0.3
s3transfer==0.1.13
scipy==1.0.0
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.2
statsmodels==0.8.0
tables==3.4.2
toolz==0.9.0
urllib3==1.24.1
web3==4.4.1
websockets==5.0.1
wrapt==1.10.11
yarl==1.1.0
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I want to ingest the binance exchange, but I get the following error:
```
.venv/lib64/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-binance/binance-minute-bnb_pax-2018-11.tar.gz
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. python36 -m venv .venv
2. .venv/bin/pip install enigma-catalyst==0.5.21
3. .venv/bin/catalyst clean-exchange -x binance
4. .venv/bin/catalyst ingest-exchange -x binance -f minute

## What steps have you taken to resolve this already?

None

# Anything else?

No

Sincerely,
`builduser`

**Comment by lenak25** [comment]
@brandsimon , thanks for reporting!
The issue was resolved, please let us know if you still experience any issues, please clear the binance ingested data and reingest.

**Comment by brandsimon** [comment]
@lenak25 Thank you very much, everything is working now.
