### ISSUE TITLE
Numpy multiarray umath

### ISSUE THREAD

**Issue by altcnews** [enigmampc/catalyst#525]
Dear Catalyst Maintainers,
Got this error in catalyst, any helps please
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

Sincerely,

**Comment by nerd-lab** [comment]
How did you solve this issue? I have the same one and can't figure it out

**Comment by sharavsambuu** [comment]
I have same issue after running this
`catalyst ingest-exchange -x bitfinex -i btc_usd`
how did you solved?

**Comment by altcnews** [comment]
> I have same issue after running this
> `catalyst ingest-exchange -x bitfinex -i btc_usd`
> how did you solved?

sorry for late answer, but i was starting from the beginning solved my problem and also installing the requirements one by one.

**Comment by aduriseti** [comment]
Hey - I think I posted a workable soln in issue #529
