### ISSUE TITLE
Stuck at Paper Trade Mode

### ISSUE THREAD

**Issue by altcnews** [enigmampc/catalyst#526]
Hi All,

After installing and ingesting data from market, i can not use live mode always at paper trade, this is the config

if __name__ == '__main__':
    live = True
    if live:
        run_algorithm(
            capital_base=100,
            initialize=initialize,
            handle_data=handle_data,
            analyze=analyze,
            exchange_name='binance',
            live=True,
            algo_namespace=algo_namespace,
            quote_currency='eth',
            simulate_orders=True,
        )

How to fix this?
Thanks & Regards.

**Comment by lenak25** [comment]
Hi @altcnews ,

I recommend carefully reading the [catalyst docs](https://enigma.co/catalyst/) and getting comfortable with backtesting and paper trading before moving to live mode.

As to your question: the parameter used to distinguish between paper mode and live is `simulate_orders`. Once you set it to `false` (it is set to `true` by default) you will be running live mode.

Lena

**Comment by altcnews** [comment]
hi @lenak25 
appreciate for your info. I've changed the config strategy which taken from example folder (simple_loop.py) and edited like this:

<a href="https://imgur.com/2apzdEE"><img src="https://i.imgur.com/2apzdEE.png" title="source: imgur.com" /></a>

and still on paper mode

<a href="https://imgur.com/R6Dzdvv"><img src="https://i.imgur.com/R6Dzdvv.png" title="source: imgur.com" /></a>

Any others setting to be changed? 
Thanks & Regards,

**Comment by lenak25** [comment]
Hi @altcnews ,

I think the root of your confusion is understanding how to define the parameters for the algorithm. 

There are several ways to run your strategy:
1. Using the command line, in which case all the parameters should be passed that way: `catalyst live -f my_algo_code -x bitfinex -c btc -n my_algo_name --no-simulate-orders`
2. Using the `run_algorithm()` function and executing the file as a Python script: `python my_algo_name.py`
3. Using [jupyter-notebook](https://enigma.co/catalyst/beginner-tutorial.html#jupyter-notebook)

In your case you run your algorithm using the command line, however without passing `--no-simulate-orders` making the algorithm use the default mode which is paper trading.
If you want to run your algorithm using the `run_algorithm()` option, the way to run your code (after defining the `run_algorithm` function in your script) is `python simple_loop.py`.

Hope things are clearer now.

Lena

**Comment by altcnews** [comment]
Hi @lenak25 
Definitely works now, that --no-simulate-orders is the case for me :)
Appreciate for your help Lena

thanks & regards.
