### ISSUE TITLE
End data in symbols.json earlier than the actual bundle

### ISSUE THREAD

**Issue by fredfortier** [enigmampc/catalyst#53]
Run:
```
catalyst clean-exchange -x bitfinex
catalyst ingest-exchange -x bitfinex -i btc_usd
```

Notice this entry in `~/.catalyst/data/exchanges/bitfinex/symbols.json`:
```
  "btcusd":{
    "end_daily":"2017-11-01",
    "end_minute":"2017-11-01",
    "start_date":"2013-03-31",
    "symbol":"btc_usd"
  }
```

The `end_daily` value does not match the content of the bundle:
```
2017-10-29 00:00:00+00:00  6150.0  6345.0  5660.0  5719.7  61967.826833
2017-10-30 00:00:00+00:00  6130.0  6239.0  6006.2  6150.0  33217.404640
2017-10-31 00:00:00+00:00  6455.1  6481.5  6082.5  6127.9  38821.109194
2017-11-01 00:00:00+00:00  6739.6  6739.9  6344.5  6455.0  57203.787342
2017-11-02 00:00:00+00:00  7018.8  7350.0  6707.3  6739.2  97337.200722
```

**Comment by fredfortier** [comment]
The issue here is related to synchronization between the bundle and symbols.json file. We will fix that issue, but I'm also making a change to work directly with the bundle dates earlier in the business logic. This should prevent this kind of issue from occurring in the future.

**Comment by lacabra** [comment]
The functions on the server to package the bundles had got out of sync. I've re-sync'ed them, and worked on properly automating the daily re-generation of the bundles to avoid similar issues in the future.
