### ISSUE TITLE
Ingest btt_bnb on binance fails

### ISSUE THREAD

**Issue by brandsimon** [enigmampc/catalyst#536]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Debian Buster
* Python Version: `Python 3.6.8`
* Python Bitness: `64`
* How did you install Catalyst: pip

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
Ingesting works successfully
* What happened instead?
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-binance/binance-minute-btt_bnb-2019-01.tar.gz
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Install catalyst==0.5.21 in a .venv
2. .venv/bin/catalyst ingest-exchange -f minute -x binance -i btt_bnb

## What steps have you taken to resolve this already?

None

# Anything else?

No

Sincerely,
`Simon`

**Comment by zanoo** [comment]
I'm also getting this issue, with the same Environment, except I'm on Debian Stretch. Seems like the AWS file permissions are wrong, as visiting the link shows an Access Denied error.

**Comment by zanoo** [comment]
Is the code that Enigma uses to create these trade data bundles publicly available? Enigma's S3 bucket might be one source for them, but it would help to further decentralize the community and project by making that code public, and allowing others to run and manage data bundle repositories. That way, if something like this happens again, use of Catalyst will not be affected. Users can simply switch to a different data bundle repo. 

I'm also wondering if there's anything the community can do to fix this. I'd like to help.

**Comment by lenak25** [comment]
Thanks for reporting and sorry for the late response. 

The issue in the S3 bucket was fixed.

Thanks again. 
We are closing this, please reopen if you observe any issues.

**Comment by sam31415** [comment]
I tried to ingest and I get the same error:
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-binance/binance-minute-btt_btc-2019-01.tar.gz`

**Comment by lenak25** [comment]
Thanks @sam31415 for pointing this out, the previous fix was indeed partial, now everything should work as expected.

**Comment by zanoo** [comment]
> Is the code that Enigma uses to create these trade data bundles publicly available? Enigma's S3 bucket might be one source for them, but it would help to further decentralize the community and project by making that code public, and allowing others to run and manage data bundle repositories. That way, if something like this happens again, use of Catalyst will not be affected. Users can simply switch to a different data bundle repo.

@lenak25 would you mind commenting on this? Is the code publicly available?

**Comment by sam31415** [comment]
Well, I still get the same error...

**Comment by lenak25** [comment]
@sam31415  , it is because there is a stale config file in your local system, which you can remove by running `catalyst clean-exchange -x binance`. 
This command will delete all downloaded Binance data, so alternatively, you can manually remove only the problematic file by deleting `~/.catalyst/data/exchanges/binance/symbols.json` (or wait up to 24h, when it will be re-downloaded automatically).
@zanoo , thanks for your feedback. At the current moment, as you mentioned, the bundles creation code is not publicly available. 
An alternative, currently available platform for decentralizing the community and project is the [Enigma marketplace](https://enigma.co/marketplace/) which offers users the opportunity to provide and subscribe to other [data sets](https://enigma.co/marketplace/status/).

**Comment by sam31415** [comment]
@lenak25 Ok thanks!

**Comment by zanoo** [comment]
@lenak25 A couple weeks later, and I'm now getting this error: 
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.amazonaws.com/enigmaco/catalyst-bundles/exchange-binance/binance-minute-fet_bnb-2019-02.tar.gz
```
