### ISSUE TITLE
Minute bundles sometimes missing first few bars

### ISSUE THREAD

**Issue by fredfortier** [enigmampc/catalyst#54]
Run this unit test:
`tests/exchange/test_bundle.py:457`

With these parameters:

```python
        exchange_name = 'bitfinex'
        data_frequency = 'minute'
        period = '2017-06'
        symbol = 'etc_btc'
```

Notice that the first minute of the bundle is missing:

```
  | close | high | low | open | volume
-- | -- | -- | -- | -- | --
2017-06-01 00:00:00+00:00 |   |   |   |   | 0
2017-06-01 00:01:00+00:00 | 0.09981799 | 0.09981799 | 0.09981799 | 0.09981799 | 2.25752429
2017-06-01 00:02:00+00:00 | 0.09981799 | 0.09981799 | 0.09981799 | 0.09981799 | 0
2017-06-01 00:03:00+00:00 | 0.0993 | 0.0993 | 0.0993 | 0.0993 | 1621.348101
2017-06-01 00:04:00+00:00 | 0.098705 | 0.0993 | 0.098593 | 0.0993 | 1790.962076
2017-06-01 00:05:00+00:00 | 0.099 | 0.099 | 0.098578 | 0.098705 | 149.5418242
```

I suspect that it's because there is not volume in this particular minute. Since it's at the beginning of the bundle, Pandas cannot ffill the data. A solution might be to make the make the start date earlier by a first periods, then slice out the trailing data.

**Comment by lacabra** [comment]
The server-side scripts that process the data bundles have been updated to properly handle these cases, and data bundles have been re-done. @fredfortier would you like to test it again?

There is something wrong with the following few bundles, which are mostly empty, but that is probably a different issue. For reference:
```
bitfinex-minute-eth_usd-2016-05 
bitfinex-minute-eth_usd-2016-06 
bitfinex-minute-ltc_usd-2015-03 
bitfinex-minute-ltc_usd-2016-06 
bitfinex-minute-ltc_btc-2015-06 
bitfinex-minute-ltc_btc-2016-06 
bitfinex-minute-ltc_btc-2015-03
```

**Comment by fredfortier** [comment]
@lacabra I believe that this is resolve. Can you confirm?

**Comment by fredfortier** [comment]
I believe that this is resolved. We validated the bundles since this issue was reported.
