### ISSUE TITLE
Catalyst Development still alive?

### ISSUE THREAD

**Issue by avolution** [enigmampc/catalyst#547]
@lenak25 
Do you guys plan to continue the development of catalyst?
This repo seems like a bit abandoned

**Comment by lenak25** [comment]
Hi @avolution ,
Our team is currently concentrating our efforts on the Enigma Protocol. Catalyst can be freely and openly used, and we welcome outside contributors.

**Comment by sam31415** [comment]
@lenak25 My pull request #535 has been opened for months. For outside contributors to feel welcome, you should at least review the pull requests and merge them when appropriate.

**Comment by antal0** [comment]
HI @lenak25 - I am glad to read that developing is still alive. May I ask you about the dependencies needed  for creating a workable catalyst environment? 
My objective is offline crypto backtesting - if catalyst is good for that
Thanks
FYI mine env as below:
(zipline) C:\Users\antal>conda list
# packages in environment at C:\Users\antal\Miniconda3\envs\zipline:
#
# Name                    Version                   Build  Channel
alembic                   1.0.9                    pypi_0    pypi
anaconda                  custom           py35h64770cb_0
attrs                     19.1.0                   pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
bcolz                     1.2.1                    pypi_0    pypi
blas                      2.6                         mkl    conda-forge
bleach                    3.1.0                    pypi_0    pypi
bottleneck                1.2.1                    pypi_0    pypi
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2018.8.24             py35_1001    conda-forge
chardet                   3.0.4                    pypi_0    pypi
click                     7.0                      pypi_0    pypi
colorama                  0.4.1                    pypi_0    pypi
contextlib2               0.5.5                    pypi_0    pypi
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.7                   pypi_0    pypi
decorator                 4.4.0                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
empyrical                 0.5.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
freetype                  2.10.0               h5db478b_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                     vc14_0    conda-forge
idna                      2.8                      pypi_0    pypi
intel-openmp              2019.3                      203
intervaltree              3.0.2                    pypi_0    pypi
ipykernel                 5.1.0                    pypi_0    pypi
ipython                   7.4.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.4.2                    pypi_0    pypi
jedi                      0.13.3                   pypi_0    pypi
jinja2                    2.10.1                   pypi_0    pypi
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.0.1                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            5.2.4                    pypi_0    pypi
jupyter-console           6.0.0                    pypi_0    pypi
jupyter-core              4.4.0                    pypi_0    pypi
kiwisolver                1.0.1            py35he980bc4_2    conda-forge
libblas                   3.8.0                     6_mkl    conda-forge
libcblas                  3.8.0                     6_mkl    conda-forge
liblapack                 3.8.0                     6_mkl    conda-forge
liblapacke                3.8.0                     6_mkl    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
logbook                   1.4.3                    pypi_0    pypi
lru-dict                  1.1.6                    pypi_0    pypi
lxml                      4.3.3                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.0.9                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.0.0            py35hd159220_0
mistune                   0.8.4                    pypi_0    pypi
mkl                       2019.3                      203
msys2-conda-epoch         20160418                      1
nbconvert                 5.4.1                    pypi_0    pypi
nbformat                  4.4.0                    pypi_0    pypi
networkx                  2.3                      pypi_0    pypi
notebook                  5.7.8                    pypi_0    pypi
numexpr                   2.6.9                    pypi_0    pypi
numpy                     1.16.3                   pypi_0    pypi
openssl                   1.0.2r               hfa6e2cd_0    conda-forge
pandas                    0.19.2                   pypi_0    pypi
pandas-datareader         0.7.0                    pypi_0    pypi
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.4.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       18.0                  py35_1001    conda-forge
prometheus-client         0.6.0                    pypi_0    pypi
prompt-toolkit            2.0.9                    pypi_0    pypi
pygments                  2.3.1                    pypi_0    pypi
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.9.2            py35h6538335_2
pyrsistent                0.14.11                  pypi_0    pypi
python                    3.5.5                he025d50_2    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-editor             1.0.4                    pypi_0    pypi
pytz                      2019.1                     py_0    conda-forge
pywinpty                  0.5.5                    pypi_0    pypi
pyzmq                     18.0.1                   pypi_0    pypi
qt                        5.9.6            vc14h62aca36_0
qtconsole                 4.4.3                    pypi_0    pypi
requests                  2.21.0                   pypi_0    pypi
scipy                     1.2.1                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                40.4.3                   py35_0    conda-forge
sip                       4.19.8          py35h6538335_1000    conda-forge
six                       1.12.0                   pypi_0    pypi
sortedcontainers          2.1.0                    pypi_0    pypi
sqlalchemy                1.3.3                    pypi_0    pypi
sqlite                    3.26.0            hfa6e2cd_1001    conda-forge
ta-lib                    0.4.9               np114py35_0    quantopian
tables                    3.4.4                    pypi_0    pypi
terminado                 0.8.2                    pypi_0    pypi
testpath                  0.4.2                    pypi_0    pypi
toolz                     0.9.0                    pypi_0    pypi
tornado                   6.0.2                    pypi_0    pypi
trading-calendars         1.7.0                    pypi_0    pypi
traitlets                 4.3.2                    pypi_0    pypi
urllib3                   1.24.2                   pypi_0    pypi
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.32.0                py35_1000    conda-forge
widgetsnbextension        3.4.2                    pypi_0    pypi
win-unicode-console       0.5                      pypi_0    pypi
wincertstore              0.2                   py35_1002    conda-forge
wrapt                     1.11.1                   pypi_0    pypi
zipline                   1.3.0                    pypi_0    pypi
zlib                      1.2.11            h2fa13f4_1004    conda-forge

**Comment by magick93** [comment]
@antal0 - please start another issue for this question as it has nothing to do with this topic. Also, you can find the info youre looking for on https://enigma.co/catalyst/install.html

**Comment by smogili1** [comment]
there are too many products in enigma and too few developers. The classic reason startups fail.

**Comment by guyz** [comment]
Closing this issue. Currently, all of our development work is dedicated to the protocol - and that includes looking into PRs.
