### ISSUE TITLE
catalyst ingest-exchange binance -f minute -i atom_(any valid quote currency) yields 403

### ISSUE THREAD

**Issue by adisojeda** [enigmampc/catalyst#549]
Dear Catalyst Maintainers,
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1a. catalyst ingest-exchange binance -i atom_bnb
**or**
1b. catalyst ingest-exchange binance -i atom_btc
**or**
1c. catalyst ingest-exchange binance -i atom_usdt

## What steps have you taken to resolve this already?
catalyst clean-exchange -x binance
--exclude-symbols
avoid ingesting  denominations of atom
...

# Anything else?
Probably some sort of permissions issue for newly added tar file in aws server (since this token was added 4/28/19)
...

Sincerely,
`$ adisojeda`

**Comment by United-T** [comment]
I have been unable to reproduce the error ingesting binance data for atom, perhaps the error was on binance's end and it has been resolved?

Can you give any other specifics on your installation/ other variables that may be different?

**Comment by adisojeda** [comment]
Yes you're right this issue seems to be resolved now for atom at least.

**Comment by adisojeda** [comment]
I have attached the screenshot of the error below, it happens when I try ingest-exchange on binance
![Screenshot from 2019-07-25 22-33-16](https://user-images.githubusercontent.com/22265132/61922042-232c3680-af2d-11e9-97bd-82c2c4fe1444.png)

I use ubuntu 18.04 with the following environment set up for catalyst:
`  # packages in environment at adiso/anaconda3/envs/catalyst:
#
# Name                    Version                   Build  Channel
aiodns                    1.1.1                    pypi_0    pypi
aiohttp                   3.0.1                    pypi_0    pypi
alembic                   0.9.7                    pypi_0    pypi
async-timeout             2.0.0                    pypi_0    pypi
attrdict                  2.0.0                    pypi_0    pypi
attrs                     17.4.0                   pypi_0    pypi
backcall                  0.1.0                      py_0    conda-forge
bcolz                     1.2.1                    pypi_0    pypi
blas                      1.1                    openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
boto3                     1.5.27                   pypi_0    pypi
botocore                  1.8.41                   pypi_0    pypi
bottleneck                1.2.1                    pypi_0    pypi
ca-certificates           2017.08.26           h1d4fec5_0  
cchardet                  2.1.1                    pypi_0    pypi
ccxt                      1.17.94                  pypi_0    pypi
certifi                   2018.1.18                py36_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
click                     6.7                      pypi_0    pypi
contextlib2               0.5.5                    pypi_0    pypi
cycler                    0.10.0                     py_1    conda-forge
cyordereddict             1.0.0                    pypi_0    pypi
cython                    0.27.3                   pypi_0    pypi
cytoolz                   0.9.0                    pypi_0    pypi
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.3.0                    pypi_0    pypi
defusedxml                0.5.0                      py_1    conda-forge
docutils                  0.14                     pypi_0    pypi
empyrical                 0.2.1                    pypi_0    pypi
enigma-catalyst           0.5.21                   pypi_0    pypi
entrypoints               0.3                   py36_1000    conda-forge
eth-abi                   1.1.1                    pypi_0    pypi
eth-account               0.2.2                    pypi_0    pypi
eth-hash                  0.1.3                    pypi_0    pypi
eth-keyfile               0.5.1                    pypi_0    pypi
eth-keys                  0.2.0b3                  pypi_0    pypi
eth-rlp                   0.1.2                    pypi_0    pypi
eth-utils                 1.0.3                    pypi_0    pypi
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.0               hd36ec8e_5    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
glib                      2.53.6               h5d9569c_2  
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
hexbytes                  0.1.0                    pypi_0    pypi
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.6                      pypi_0    pypi
idna-ssl                  1.0.0                    pypi_0    pypi
intel-openmp              2018.0.0                      8  
intervaltree              2.1.0                    pypi_0    pypi
ipykernel                 5.1.0           py36h24bf2e0_1002    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.13.3                   py36_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jmespath                  0.9.3                    pypi_0    pypi
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.1                    py36_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter-contrib-core      0.3.3                    pypi_0    pypi
jupyter-nbextensions-configurator 0.4.0                    pypi_0    pypi
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_console           5.2.0                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
logbook                   1.2.1                    pypi_0    pypi
lru-dict                  1.1.6                    pypi_0    pypi
lxml                      4.1.1                    pypi_0    pypi
mako                      1.0.7                    pypi_0    pypi
markupsafe                1.0                      pypi_0    pypi
matplotlib                2.2.2            py36h0e671d2_1  
mistune                   0.8.4           py36h14c3975_1000    conda-forge
mkl                       2018.0.1             h19d6760_4  
multidict                 4.1.0                    pypi_0    pypi
multipledispatch          0.4.9                    pypi_0    pypi
nbconvert                 5.5.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.1                      pypi_0    pypi
notebook                  5.7.8                    py36_0    conda-forge
numexpr                   2.6.4                    pypi_0    pypi
numpy                     1.14.0          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2n                        0    conda-forge
pandas                    0.19.2                   pypi_0    pypi
pandas-datareader         0.6.0                    pypi_0    pypi
pandoc                    2.7.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parsimonious              0.8.0                    pypi_0    pypi
parso                     0.4.0                      py_0    conda-forge
patsy                     0.5.0                    pypi_0    pypi
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       9.0.1                    py36_1    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycares                   2.3.0                    pypi_0    pypi
pycryptodome              3.6.1                    pypi_0    pypi
pygments                  2.4.0                      py_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.9.2            py36h751905a_0  
pyrsistent                0.15.2           py36h516909a_0    conda-forge
pysha3                    1.0.2                    pypi_0    pypi
python                    3.6.4                hc3d631a_3  
python-dateutil           2.8.0                      py_0    conda-forge
python-editor             1.0.3                    pypi_0    pypi
pytz                      2016.4                   pypi_0    pypi
pyyaml                    5.1                      pypi_0    pypi
pyzmq                     18.0.1           py36hc4ba49a_1    conda-forge
qt                        5.9.4                h4e5bff0_0  
qtconsole                 4.4.4                      py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
redo                      2.0.1                    pypi_0    pypi
requests                  2.20.1                   pypi_0    pypi
requests-file             1.4.3                    pypi_0    pypi
requests-ftp              0.3.1                    pypi_0    pypi
requests-toolbelt         0.8.0                    pypi_0    pypi
rlp                       0.6.0                    pypi_0    pypi
s3transfer                0.1.12                   pypi_0    pypi
scipy                     1.0.0           py36_blas_openblas_201  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   pypi_0    pypi
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.19.8          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
sortedcontainers          1.5.9                    pypi_0    pypi
sqlalchemy                1.2.2                    pypi_0    pypi
sqlite                    3.22.0               h1bed415_0  
statsmodels               0.8.0                    pypi_0    pypi
ta-lib                    0.4.17                   pypi_0    pypi
tables                    3.4.2                    pypi_0    pypi
terminado                 0.8.2                    py36_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.7                         0    conda-forge
toolz                     0.9.0                    pypi_0    pypi
tornado                   6.0.2            py36h516909a_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
urllib3                   1.22                     pypi_0    pypi
virtualenv                15.2.0                   pypi_0    pypi
wcwidth                   0.1.7                      py_1    conda-forge
web3                      4.4.1                    pypi_0    pypi
webencodings              0.5.1                      py_1    conda-forge
websockets                5.0                      pypi_0    pypi
wheel                     0.30.0                   py36_2    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.10.11                  pypi_0    pypi
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.3                         0    conda-forge
yarl                      1.1.0                    pypi_0    pypi
zeromq                    4.3.1             hf484d3e_1000    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
`

**Comment by adisojeda** [comment]
> I have been unable to reproduce the error ingesting binance data for atom, perhaps the error was on binance's end and it has been resolved?
> 
> Can you give any other specifics on your installation/ other variables that may be different?

I have realized it only fails specifically with the "-f minute" parameter
