### ISSUE TITLE
Support multiple accounts per exchange

### ISSUE THREAD

**Issue by fredfortier** [enigmampc/catalyst#60]
A single user might want to run algos against more than one account of the same exchange. Currently, it not possible because the naming convention under `.catalyst`. Add an alias parameter which can reference specific accounts of an exchange.

**Comment by fredfortier** [comment]
The `run_algorithm` currently has an `auth_alias` parameter which can replace the `auth` key in `auth.json`.
```
        run_algorithm(
            capital_base=2,
            initialize=initialize,
            handle_data=handle_data,
            analyze=analyze,
            exchange_name='binance',
            live=True,
            algo_namespace=NAMESPACE,
            base_currency='eth',
            live_graph=False,
            simulate_orders=True,
            stats_output='s3://conatus-public',
            auth_aliases=dict(binance='auth2')
        )
```
In this example, the algo will look for `auth2.json` in the binance folder.

We still need to add this parameter to the CLI.

**Comment by fredfortier** [comment]
Added to the CLI.

**Comment by lacabra** [comment]
Remember to add this to the documentation as well :)
