### ISSUE TITLE
Exchange argument -x not being used when backtesting and defaults to Poloniex

### ISSUE THREAD

**Issue by mjallman** [enigmampc/catalyst#83]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows Version 1709
* Python Version: Python 3.6.1 Anaconda custom (64-bit)
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages: it's a long list, but don't think it's relevant to my issue.

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* I ran the following command from the beginner tutorial expecting it to execute successfully:
catalyst run -f buy_btc_simple.py -x bitfinex --start 2016-1-1 --end 2017-9-30 -c usd --capital-base 100000 -o buy_btc_simple_out.pickle
* Had error message referring to poloniex.py, which was unexpected as I passed in bitfinex as exchange argument. I think the method _run in run_algo needs to pass in the exchange parameter to TradingEnvironment on line 200 of run_algo.py.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Run this command: catalyst run -f buy_btc_simple.py -x bitfinex --start 2016-1-1 --end 2017-9-30 -c usd --capital-base 100000 -o buy_btc_simple_out.pickle

## What steps have you taken to resolve this already?
I tried passing in the exchange argument to TradingEnvironment, but perhaps this needs to be included as part of the loop through the exchanges list.

Sincerely,
Michael

**Comment by fredfortier** [comment]
I tried to reproduce this, it did not ignore the "-x" argument for me. However, algorithms always use Poloniex to fetch benchmark data which is currently btc_usdt price history. It's likely where you experienced an error.

Feel free to include the error stack for a more precise diagnostic.

**Comment by mjallman** [comment]
Hi Fred,

Thanks for your reply. I've attached the error stack. I think the Poloniex API is failing for me due to the recaptcha check they have there.

<img width="756" alt="error_poloniex" src="https://user-images.githubusercontent.com/22987372/33190899-1c9fd384-d078-11e7-8fc9-c222086fefc5.PNG">

Regards
Michael

**Comment by mjallman** [comment]
Note that if I change loader.py to use bm_symbol = 'btc_usd' and exchange = Bitfinex('', '', '') then the command completes without any error.

**Comment by fredfortier** [comment]
This is interesting. I'm not sure why it fails for you but generally seems to work. But I understand the error condition which you are describing. I'm going to assume that it's similar to this: https://github.com/dutu/poloniex-api-node/issues/20

Did you try logging into Poloniex using your 2FA from the same computer. It may be more discerning with IP address which it does not know.

I'll investigate this further.

**Comment by mjallman** [comment]
Thanks for the link, that looks like the same problem I'm having. I'll try to resolve it and will let you know how it goes.

**Comment by lacabra** [comment]
@mjallman (cc: @fredfortier) I have seen this error before, and I will assume that you are based outside the USA. Poloniex (or the Cloudfare service they use for DDoS) introduces captcha for all their API requests coming from outside the country. Unfortunately, there is nothing we can do. If you have access to one, you may want to set up a VPN to anywhere inside the US, and access Poloniex (or use Catalyst) through the VPN, and the error should go away. 
Admittedly, this limitation on Poloniex makes no sense because it deems the API unusable from abroad, but we have no control over it. @fredfortier and I are actively working to support a large number of new exchanges in our next major release, so hopefully we'll provide you with plenty of alternatives. For now, I can only suggest you use the other two exchanges supported: Bitfinex and Bittrex.

**Comment by mjallman** [comment]
Thanks for the info @lacabra , I'll use other exchanges for now :)

**Comment by fredfortier** [comment]
We've changed our Poloniex implementation so it may work better now. If not, the issue is likely with Poloniex. I'm closing the issue for housekeeping reasons. Please reopen if it still seems like a Catalyst problem.

**Comment by mjallman** [comment]
Thanks for the update.
