### ISSUE TITLE
Users should be able to override slippage and commission

### ISSUE THREAD

**Issue by fredfortier** [enigmampc/catalyst#87]
Zipline has API's to set slippage and comission which Catalyst is not honoring now.

Here is the slippage call:
```
set_slippage() 
```
See "Slippage Models" here: https://www.quantopian.com/help. For the next release, we may only support fixed slippage. Volume based slippage are relevant but we need to make sure that they apply directly.

For commission, we'll use the make and taker parameters instead of a fix commission. The api should look like this:
```
set_commission(maker=0.002, taker=0.001)
```
Related issue #82 addresses the default values of maker and taker, making them dynamic based on each market. This issue addresses the ability to override these values.

**Comment by fredfortier** [comment]
In Release 0.4.0.

**Comment by caioaao** [comment]
@fredfortier I tried using `set_commission(maker=0.0015, taker=0.0025)` and it completely messed with my backtest: I had an __extremely__ overly optimistic backtest result. Later I removed it for unrelated motives (I did my own live trading "framework" that better suited my demands) and the backtest ended up giving negative results.

PS: Extremely overly optimistic = got a 200x return (20,000%) - totally crazy
