### ISSUE TITLE
Poloniex deprecated_dec() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by harir91** [enigmampc/catalyst#94]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

Environment:
* Operating System: MAC OSX, LINUX
* Python Version: Python 2.7.10                                      
* Python Bitness: 64
* How did you install Catalyst: pip

See screenshot.
<img width="1089" alt="screen shot 2017-12-09 at 3 14 42 pm" src="https://user-images.githubusercontent.com/14968486/33800415-2290a524-dcf4-11e7-954b-ec9cc63c8830.png">

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by fredfortier** [comment]
We reworked the Poloniex implementation and retested all interfaces. This should not be an issue in the next release.

**Comment by fredfortier** [comment]
In Release 0.4.0.
