### ISSUE TITLE
cancel_order() on poloniex fails.

### ISSUE THREAD

**Issue by harir91** [enigmampc/catalyst#95]
Environment:
* Operating System: MAC OSX, LINUX
* Python Version: Python 2.7.10                                      
* Python Bitness: 64
* How did you install Catalyst: pip

cancel_order() takes exactly 3 arguments: 2 given.

**Comment by fredfortier** [comment]
We reworked the Poloniex implementation and retested all interfaces. This should not be an issue in the next release.

**Comment by harir91** [comment]
Awesome -- Do you guys have an eta on next release?

**Comment by fredfortier** [comment]
Tuesday

**Comment by fredfortier** [comment]
In Release 0.4.0.

**Comment by dlacombejr** [comment]
I am getting the same error with the same environment @harir91 above using `Catalyst version 0.5.12`:

```
TypeError: cancel_order() takes at least 3 arguments (2 given)
```
I get this when paper trading on the `poloniex` exchange.

**Comment by ykgoon** [comment]
@lenak25 your workaround didn't work for me. I've tried

- `context.exchanges['bitfinex'].cancel_order(<order_id>)` (order **ID** as param)
- `context.exchanges['bitfinex'].cancel_order(<order_obj>)` (order **object** as param)

For both cases I got this error:

```
ValueError: invalid literal for int() with base 10: 'b74f253082774179bdb8f6592d04421e'
```

**Comment by lenak25** [comment]
Hi @ykgoon, what mode are you running? This is only relevant for live trading.
I've update my previous message with a more simpler workaround (you can use both, however the first will retry several times in case of a failure).

**Comment by ykgoon** [comment]
@lenak25 I've tried both workaround methods, both resulted in the same error. Here are my details:

- Catalyst version: 0.5.12
- Exchange: bitfinex
- Mode: live with paper-trade

**Comment by ykgoon** [comment]
I think my issue is confined to Bitfinex. I've opened a new ticket in #346.

**Comment by lenak25** [comment]
You are correct, thanks @ykgoon for validating it and opening a new issue!

**Comment by dlacombejr** [comment]
@lenak25 thanks for your time. The temporary solution you provided isn't working. 

Using the `cancel_order(<order_id>, 'poloniex')` approach with the following code...
```
    for symbol in context.blotter.open_orders:
        for order in context.blotter.open_orders[symbol]:
            cancel_order(order.id, 'poloniex')
```
... I get the same error as above: 
```
TypeError: cancel_order() takes exactly 2 arguments (3 given)
```

Using the `context.exchanges['poloniex'].cancel_order(<order_id>)` approach with the following code...

```
    for symbol in context.blotter.open_orders:
        for order in context.blotter.open_orders[symbol]:
            context.exchanges['poloniex'].cancel_order(order.id)
```

... I get this error: 

```
catalyst.exchange.exchange_errors.ExchangeRequestError: Request failed: poloniex: unknown error: {"error":"Invalid orderNumber parameter."}
```

**Comment by AvishaiW** [comment]
@dlacombejr the fix @lenak25 offered was for live mode only, however, we added a proper fix for all modes that will be added to our next release

**Comment by AvishaiW** [comment]
added to release 0.5.14
